drop table if exists idw.fact_borrows;
CREATE TABLE idw.fact_borrows         
(
	bo_id BIGINT COMMENT '借款ID'
	,p_id BIGINT COMMENT '产品ID'
	,busi_line STRING COMMENT '所属业务线'
	,bp_id BIGINT COMMENT '预发标ID'
	,user_id BIGINT COMMENT '用户ID'
	,bo_aim STRING COMMENT '借款目的'
	,bo_title STRING COMMENT '借款标题'
	,bo_repaysrc STRING COMMENT '还款来源'
	,bo_price DECIMAL(38,10) COMMENT '借款金额'
	,bo_finish_price DECIMAL(38,10) COMMENT '完成金额'
	,bo_expect INT COMMENT '借款期限'
	,bo_expect_cat INT COMMENT '借款期限单位'
	,bo_bidding_type INT COMMENT '标的类型'
	,bo_safeguard_type INT COMMENT '保障方式'
	,bo_type INT COMMENT '借款类型'
	,is_assurance INT COMMENT '是否请求担保'
	,bo_rate DECIMAL(38,10) COMMENT '借款年利率'
	,bo_time INT COMMENT '有效时间'
	,bo_paytype STRING COMMENT '还款方式'
	,bo_is_index INT COMMENT '是否推荐'
	,bo_is_state INT COMMENT '借款状态'
	,publish_time STRING COMMENT '发布时间'
	,bo_finish_rate DECIMAL(38,10) COMMENT '完成度'
	,bo_is_finish INT COMMENT '是否完成'
	,bo_finish_time STRING COMMENT '完成时间'
	,bo_sign_am_id BIGINT COMMENT '签约人员'
	,bo_sign_time STRING COMMENT '签约时间'
	,bo_sign_result INT COMMENT '签约结果'
	,bo_audit_am_id BIGINT COMMENT '审核人员'
	,bo_audit_time STRING COMMENT '审核时间'
	,bo_audit_remark STRING COMMENT '审核备注'
	,bo_is_success INT COMMENT '是否审核通过 1:通过 2:拒绝 3:超时流标 4:回退'
	,bo_can_success INT COMMENT '是否可以审核通过'
	,bo_is_republish INT COMMENT '是否已重发'
	,bo_is_case INT COMMENT '是否推荐案例'
	,bo_guid STRING COMMENT '电子协议guid'
	,bo_extno STRING COMMENT '协议编号'
	,bo_agree_generated INT COMMENT '协议是否生成'
	,bo_agree_time STRING COMMENT '协议生成时间'
	,bo_all_repayed INT COMMENT '借款还款结束'
	,all_repayed_time STRING COMMENT '还款结束时间'
	,bo_sorce_talk INT COMMENT '谈吐分值'
	,bo_sorce_instrument INT COMMENT '仪表分值'
	,bo_sorce_face INT COMMENT '面相分值'
	,bo_sorce_cooperation INT COMMENT '配合度分值'
	,bo_pledge INT COMMENT '是否抵押'
	,bo_house STRING COMMENT '房产信息'
	,creator BIGINT COMMENT '创建人'
	,updator BIGINT COMMENT '更新人'
	,create_time STRING COMMENT '创建时间'
	,update_time STRING COMMENT '更新时间'
	,bo_purpose STRING COMMENT '借款用途'
	,zx_price DECIMAL(38,10) COMMENT '咨询费'
	,zx_status INT COMMENT '咨询费状态 0:暂扣 1:退换 2:逾期扣除'
	,is_repeat_borrow INT COMMENT '是否复借'
	,is_video_audit INT COMMENT '是否提交视频'
	,video_audit_time STRING COMMENT '视频提交时间'
	,first_audit_time STRING COMMENT '首次初审时间'
	,last_audit_pass_time STRING COMMENT '最近初审通过时间'
	,last_confirm_time STRING COMMENT '最近终审时间'
	,confirm_pass_time STRING COMMENT '终审通过时间'
	,repay_begin_day STRING COMMENT '起始还款日'
	,is_first_repay_overdue INT COMMENT '是否首还逾期'
	,first_repay_overdue_days INT COMMENT '首还逾期天数'
	,interest_rate_cut DECIMAL(38,10) COMMENT '减息'
	,repayment_coupon DECIMAL(38,10) COMMENT '还款券金额'
	,dw_create_by STRING COMMENT '系统字段-创建者'
	,dw_create_time STRING COMMENT '系统字段-创建时间'
	,dw_update_by STRING COMMENT '系统字段-修改者'
	,dw_update_time STRING COMMENT '系统字段-修改时间'
	,cur_status STRING COMMENT '当前状态'
	,audit_status STRING COMMENT '初审状态'
	,confirm_status STRING COMMENT '终审状态'
	,audit_reject_time STRING COMMENT '初审拒绝时间'
	,confirm_reject_time STRING COMMENT '终审拒绝时间'
	,reject_time STRING COMMENT '拒绝时间'
	,audit_cancel_time STRING COMMENT '初审取消时间'
	,confirm_cancel_time STRING COMMENT '终审取消时间'
	,fail_time STRING COMMENT '流标时间'
	,category_name_01 STRING COMMENT '产品分类01'
	,biz_code_01 STRING COMMENT '业务线编码01'
	,biz_name_01 STRING COMMENT '业务线名称01'
	,depository_flag INT COMMENT '存管标记 0:初始 1:走存管 2:不走存管'
	,first_overdue_expect_num INT COMMENT '首次逾期期数'
	,first_overdue_br_time STRING COMMENT '首次逾期应还时间'
	,transfer_account_time STRING COMMENT '实际划转成功时间'
	,p_name STRING COMMENT '产品名称'
	,monthly_repayment_amt DECIMAL(38,10) COMMENT '月还款金额'
	,bo_success_time STRING COMMENT '放款时间'
	,bo_success_num INT COMMENT '成功放款批次'
	,bo_confirm_num INT COMMENT '终审通过批次'
	,user_identity_type INT COMMENT '用户身份： 1-无业，2-白领，3-蓝领'
	,total_amount DECIMAL(38,10) COMMENT '总额度'
	,base_amount DECIMAL(38,10) COMMENT '基础额度'
	,used_amount DECIMAL(38,10) COMMENT '已使用可借额度'
	,increase_amount DECIMAL(38,10) COMMENT '增信额度'
	,top_amount DECIMAL(38,10) COMMENT '额度上限:个人最高额度限制'
	,lbs_access_city STRING COMMENT '准入时获取的LBS地址'
	,lbs_complete_data_city STRING COMMENT '生成正式标的LBS地址'
	,credit_type INT COMMENT '授信模式类型 1-基础项提额项模式, 2-高学历模式, 3-消费能力模式'
	,bp_channel INT COMMENT '申请渠道'
	,rc_id BIGINT COMMENT '资方id'
	,rc_name STRING COMMENT '资方名称'
	,p_key INT COMMENT '产品代理键'
	,pass_time STRING COMMENT '审核通过时间'
	,ml_time STRING COMMENT '进件时间'
	,bo_last_repayed_time STRING COMMENT '最近还款时间'
	,ml_price DECIMAL(38,10) COMMENT '进件金额'
	,confirm_pass_price DECIMAL(38,10) COMMENT '审批金额'
	,is_borrows_raise INT COMMENT '是否一键再借'
	,is_stock_campaign INT COMMENT '是否存量战役' 
	,is_graduate STRING COMMENT '是否已毕业'
)
COMMENT '借款表' 
STORED AS PARQUET 
;
