CREATE TABLE IF NOT EXISTS DMT_MXD.FACT_MXD_OPERATION
    (
   TAG_DATE             string comment '数据时间',
   P_ID                 bigint comment '产品ID',
   BO_PURPOSE           string comment '借款用途',
   USER_ID              bigint comment '用户ID',
   BO_ID                bigint comment '借款ID',
   REGISTER_USER_ID     bigint comment '注册用户ID',
   STU_AUTH_USER_ID     bigint comment '学籍验证通过用户ID',
   APPLY_USER_ID        bigint comment '申请用户ID',
   BO_USER_ID           bigint comment '放款用户ID',
   VIDEO_AUDIT_BO_ID    bigint comment '提交视频借款ID',
   LOAN_BO_ID           bigint comment '已放款借款ID',
   BO_AMT               decimal(38,10) comment '放款金额',
   BO_TIME              string comment '放款时间',
   SEVEN_BO_USER_ID     bigint comment '注册7天放款用户ID',
   RE_BO_USER_ID        bigint comment '复借用户ID',
   RE_BO_AMT            decimal(38,10) comment '复借金额',
   IS_FIRST_REPAY_OVERDUE int comment '是否首还逾期',
   FIRST_REPAY_OVERDUE_B decimal(38,10) comment '首还逾期本金',
   IS_FIRST_REPAY_OVERDUE_UNREPAY int comment '是否首还逾期目前未还',
   FIRST_REPAY_OVERDUE_UNREPAY_B decimal(38,10) comment '首还逾期目前未还本金',
   IS_FIRST_REPAY       int comment '是否首次还款',
   FIRST_REPAY_B        decimal(38,10) comment '首次还款本金',
   IS_OVERDUE           int comment '是否逾期',
   OVERDUE_B            decimal(38,10) comment '逾期本金',
   IS_OVERDUE_UNREPAY   int comment '是否逾期未还',
   OVERDUE_UNREPAY_B    decimal(38,10) comment '逾期未还本金',
   BR_PRICE             decimal(38,10) comment '还款金额',
   BR_PRICE_B           decimal(38,10) comment '本金',
   BR_PRICE_L           decimal(38,10) comment '利息',
   BR_PRICE_PUNISH      decimal(38,10) comment '罚息和违约金',
   UNREPAY_PRICE_B      decimal(38,10) comment '未还本金',
   UNREPAY_PRICE_L      decimal(38,10) comment '未还利息',
   UNREPAY_PRICE_PUNISH decimal(38,10) comment '未还罚息',
   IS_FIRST_OVERDUE     int comment '是否首次逾期',
   FIRST_OVERDUE_B      decimal(38,10) comment '首次逾期本金',
   IS_FIRST_OVERDUE_UNREPAY int comment '是否首次逾期未还',
   FIRST_OVERDUE_UNREPAY_B decimal(38,10) comment '首次逾期未还本金',
   IS_NEVER_OVERDUE     int comment '是否截止上期无逾期',
   NEVER_OVERDUE_B      decimal(38,10) comment '截止上期无逾期本金',
   DATA_TYPE            int comment '数据类型 1 注册 2 学籍验证通过 3 借款申请 4 视频提交 5 已放款借款 6 借入者计划还款 7 借入者实际还款',
   SRC_ID               bigint comment '源表主键',
   DW_CREATE_BY         string comment '系统字段-创建者',
   DW_CREATE_TIME       string comment '系统字段-创建时间',
   DW_UPDATE_BY         string comment '系统字段-修改者',
   DW_UPDATE_TIME       string comment '系统字段-修改时间',
   BO_APPLY_AMT         decimal(38,10) comment '申请金额'
    )
    COMMENT '名校贷运营报表'
    ROW FORMAT DELIMITED
      NULL DEFINED AS ''
    STORED AS PARQUET TBLPROPERTIES ("parquet.compression"="SNAPPY");