DROP TABLE IF EXISTS DMT_MXD.FACT_OPERATION_REPORT_DAILY;
CREATE TABLE IF NOT EXISTS DMT_MXD.FACT_OPERATION_REPORT_DAILY
(
DW_CREATE_BY         string comment '系统字段-创建者'
,DW_CREATE_TIME       string comment '系统字段-创建时间'
,DW_UPDATE_BY         string comment '系统字段-修改者'
,DW_UPDATE_TIME       string comment '系统字段-修改时间'
,register_user_cnt_h5 int comment'注册用户数-H5'
,register_user_cnt_mxd int comment'注册用户数-白领贷'
,register_user_cnt_bld int comment'注册用户数-名校贷'
,register_user_cnt_mzjk int comment'注册用户数-麦子借款'
,real_name_user_cnt_mzjk  int comment'实名认证用户数-麦子借款'
,real_name_user_cnt_bld  int comment'实名认证用户数-麦子借款'
,real_name_user_cnt int comment'实名认证用户数'
,sx_submit_user_new_h5 int comment'授信提交用户数-H5注册且新客'
,sx_submit_user_old int comment'授信提交用户数-老客'
,sx_submit_user_new  int comment'授信提交用户数-新客'
,sx_submit_user_cnt  int comment'授信提交用户数'
,sx_success_user_old int comment'授信成功老客'
,sx_success_user_new int comment'授信成功新客'
,sx_success_user_cnt int comment'授信成功用户数'
,promote_user_cnt int comment'提额用户数'
,apply_user_cnt  int comment'借款申请用户数'
,apply_user_cnt_mzjk int comment'借款申请用户数-麦子借款'
,apply_user_cnt_bld int comment'借款申请用户数-白领贷'
,apply_user_cnt_mxd int comment'借款申请用户数-名校贷'
,apply_user_cnt_old int comment'借款申请用户数-老客'
,apply_user_cnt_new int comment'借款申请用户数-新客'
,ml_user_cnt  int comment'进件用户数'
,ml_user_cnt_mzjk int comment'进件用户数-麦子借款'
,ml_user_cnt_bld int comment'进件用户数-白领贷'
,ml_user_cnt_mxd int comment'进件用户数-名校贷'
,ml_user_cnt_old int comment'进件用户数-老客'
,ml_user_cnt_new int comment'进件用户数-新客'
,confirm_user_cnt  int comment'放款用户数'
,confirm_user_cnt_mzjk int comment'放款用户数-麦子借款'
,confirm_user_cnt_bld int comment'放款用户数-白领贷'
,confirm_user_cnt_mxd int comment'放款用户数-名校贷'
,confirm_user_cnt_old int comment'放款用户数-老客'
,confirm_user_cnt_new int comment'放款用户数-新客'
,confirm_user_cnt_mzjk_old int comment'放款用户数-麦子借款老客'
,confirm_user_cnt_mzjk_new int comment'放款用户数-麦子借款新客'
,confirm_user_cnt_bld_old int comment'放款用户数-白领贷老客'
,confirm_user_cnt_bld_new int comment'放款用户数-白领贷新客'
,confirm_user_cnt_mxd_old int comment'放款用户数-名校贷老客'
,confirm_user_cnt_mxd_new int comment'放款用户数-名校贷新客'
)
COMMENT '运营日报'
PARTITIONED BY (stat_date STRING COMMENT '统计日期 年-月-日')
ROW FORMAT DELIMITED
  NULL DEFINED AS ''
STORED AS PARQUET 
TBLPROPERTIES ("parquet.compression"="SNAPPY");