USE DMT_RM;

DROP TABLE IF EXISTS DMT_RM.FACT_HOR_DATA;

CREATE TABLE IF NOT EXISTS  DMT_RM.FACT_HOR_DATA(
  ID STRING COMMENT 'ID',
  HEADER_ID INT COMMENT '表头ID',
  COLUMN_ID INT COMMENT '解析字段ID',
  USER_CERT_NO STRING COMMENT '被查询用户证件号(默认身份证号)',
  CHANNEL_CODE STRING COMMENT '调用第三方渠道CODE',
  CHANNEL_NAME STRING COMMENT '调用第三方渠道',
  VERSION INT COMMENT '数据版本号(解析规则版本)',
  PLATFORM_ID INT COMMENT '平台ID',
  PLATFORM_NAME STRING COMMENT '平台名称',
  USER_CERT_TYPE STRING COMMENT'被查询用户证件类型',
  STATUS INT COMMENT '数据状态，0无效，1正常',
  COLUMN_NAME STRING COMMENT '解析字段名，对应第三方返回的数据字段',
  VALUE STRING COMMENT '具体数据',
  BO_ID BIGINT COMMENT '申请ID',
  CREATE_TIME STRING COMMENT '业务库创建时间',
  UPDATE_TIME STRING COMMENT '业务库更新时间',
  DW_CREATE_BY STRING COMMENT '系统字段-创建者', 
  DW_CREATE_TIME STRING COMMENT '系统字段-创建时间', 
  DW_UPDATE_BY STRING COMMENT '系统字段-修改者', 
  DW_UPDATE_TIME STRING COMMENT '系统字段-修改时间'
)
COMMENT '风控征信整合表'
PARTITIONED BY (DAY_ID STRING COMMENT '日期')
STORED AS PARQUET TBLPROPERTIES ("PARQUET.COMPRESSION"="SNAPPY");
