USE DMT_RM;

DROP TABLE IF EXISTS DMT_RM.FACT_HOR_DATA_STATIC;

CREATE TABLE IF NOT EXISTS  DMT_RM.FACT_HOR_DATA_STATIC(
  ID int,
  USER_CERT_TYPE STRING COMMENT'被查询用户证件类型',
  USER_CERT_NO STRING COMMENT '被查询用户证件号(默认身份证号)',
  BO_ID STRING,
  ZM_ZMSCORE STRING COMMENT '芝麻反欺诈分',
  ZM_IVSSCORE STRING COMMENT '芝麻IVS分',
  ZM_MATCHED STRING COMMENT '芝麻行业关注名单',
  TONGDUN_7DAYMORES STRING COMMENT '同盾7天多投',
  TONGDUN_BLACKSTYPE STRING COMMENT '命中同盾黑名单类型',
  TONGDUN_FINALSCORE STRING COMMENT '同盾-风险分数',
  TONGDUN_FINALDECISION STRING COMMENT '同盾-风险结果',
  TXSK_MOBILE STRING COMMENT '天行数科-查询号码',
  TXSK_ONLINETIME STRING COMMENT '天行数科-在网时长',
  TXSK_RESULTSTATUS STRING COMMENT '天行数科-查询状态',
  BAIQISHI_FINALDECISION STRING COMMENT '白骑士-风险名单比对结果码',
  BAIQISHI_FINALSCORE STRING COMMENT '白骑士-最终评分',
  BR_RULEFINALDECISION STRING COMMENT '百融-最终决策结果',
  BR_RULEFINALWEIGHT STRING COMMENT '百融-最终规则评分',
  BR_ALSM3IDNBANKALLNUM STRING COMMENT '百融-近3个月身份证在百融非银合作机构申请次数',
  DW_CREATE_BY STRING COMMENT '系统字段-创建者', 
  DW_CREATE_TIME STRING COMMENT '系统字段-创建时间', 
  DW_UPDATE_BY STRING COMMENT '系统字段-修改者', 
  DW_UPDATE_TIME STRING COMMENT '系统字段-修改时间'
)
COMMENT '风控征信款表'
PARTITIONED BY (DAY_ID STRING)
STORED AS PARQUET TBLPROPERTIES ("PARQUET.COMPRESSION"="SNAPPY");