DROP TABLE IF EXISTS DMT_RM.FACT_APPLY_MAIYA_DATA;
CREATE TABLE IF NOT EXISTS DMT_RM.FACT_APPLY_MAIYA_DATA
(
   dw_create_by string COMMENT '系统字段-创建者', 
   dw_create_time string COMMENT '系统字段-创建时间',
   dw_update_by string COMMENT '系统字段-修改者', 
   dw_update_time string COMMENT '系统字段-修改时间',
   order_no string COMMENT '订单编号', 
   apply_no bigint COMMENT '申请号',
   apply_name string COMMENT '用户姓名', 
   order_status string COMMENT '订单状态', 
   return_remark string COMMENT '回退原因',
   refuse_reason string COMMENT '人工拒绝原因大类',
   sub_refuse_reason string COMMENT '人工拒绝原因小类',
   idcard string COMMENT '身份证号', 
   sex string COMMENT '性别',
   education string COMMENT '学历',
   mobile string COMMENT '联系电话', 
   email string COMMENT '邮箱地址',
   position string COMMENT '工作职位', 
   company_name string COMMENT '公司名称', 
   current_province string COMMENT '当前省份', 
   current_city string COMMENT '当前城市', 
   create_time string COMMENT '下单时间',
   order_begin_date string COMMENT '订单开始时间', 
   pass_time string COMMENT '审核通过时间',
   lending_time string COMMENT '放款时间', 
   practical_money decimal(38,10) COMMENT '实际放款金额',
   total_parts int COMMENT '订单总期数',
   channel int COMMENT '渠道', 
   source int COMMENT '用户来源',
   phonecall_flag int COMMENT '是否拨打电话',
   family_income_amt int COMMENT '薪水', 
   fraud_flag int COMMENT '是否欺诈',
   shop_id int COMMENT '商户ID', 
   face_id string COMMENT '门店ID',
   merchant_name string COMMENT '商户名称',
   merchant_type string COMMENT '商户类型',
   score string COMMENT '同盾分', 
   level string COMMENT '信用等级',
   apply_amount decimal(38,10) COMMENT '申请金额', 
   apply_parts int COMMENT '申请期限', 
   dic_item string COMMENT '商户行业', 
   cancel_reason string COMMENT '取消原因',
   cancel_remark string COMMENT '取消备注',
   user_id int COMMENT '下单用户ID', 
   user_name string COMMENT '麦芽用户名', 
   phone_provice string COMMENT '手机号码归属地', 
   work_type string COMMENT '客户工作行业单位',
   credit_node string COMMENT '信用评级node',
   bd_name string COMMENT 'bd姓名',
   auto_reject_reason string COMMENT '自动审批拒绝原因', 
   nono_user_id int COMMENT 'nono用户ID',
   goods_id int COMMENT '产品ID，区分麦芽进件还是美呗进件',
   review_source string comment '是否渠道审核（0是麦芽审核，1是代渠道审核）',
   qd_pass string comment '渠道是否审核通过/渠道担保成功 1',
   fachannel_name string comment '父渠道名',
   subchannel_name STRING COMMENT '子渠道名')
COMMENT '麦芽申请表'
PARTITIONED BY (STAT_DATE int COMMENT '统计日期 年月日')
ROW FORMAT DELIMITED
NULL DEFINED AS ''
STORED AS PARQUET 
TBLPROPERTIES ("parquet.compression"="SNAPPY");
