drop table if exists DMT_RM.FACT_MLD_HOR_STATIC;

CREATE TABLE DMT_RM.FACT_MLD_HOR_STATIC (
  `ORDER_ID` INT COMMENT '订单ID', 
  `ORDER_NO` STRING COMMENT '订单号', 
  `APPLY_NO` STRING COMMENT 'NONO申请号(NONO BOID)', 
  `USER_ID` INT COMMENT '用户ID',
  `NONO_USERID` INT COMMENT 'NONO用户ID',
  `ORDER_CREATE_DATE` STRING COMMENT '订单创建时间',
  `ORDER_STATUS` INT    COMMENT '订单状态',
  `APPLY_STAUS` INT   COMMENT '发标状态',
  ZM_SCORE STRING COMMENT '芝麻分',
  ZM_IVS_SCORE STRING COMMENT '芝麻IVS分',
  ZM_HYGZLIST_MATCHED STRING COMMENT '芝麻行业关注名单',
  TD_FINALSCORE STRING COMMENT '同盾,风险分数',
  TD_FINALDECISION STRING COMMENT '同盾,风险结果',
  TD_MUL_INVEST_7D STRING COMMENT '7天内申请人在多个平台申请借款次数（同盾）',
  TD_MUL_INVEST_1M STRING COMMENT '1个月内申请人在多个平台申请借款次数（同盾）',
  TD_MUL_INVEST_3M STRING COMMENT '3个月内申请人在多个平台申请借款次数（同盾）',
  TD_MUL_INVEST_6M STRING COMMENT '6个月内申请人在多个平台申请借款次数（同盾）',
  FACE_SCORE STRING COMMENT '水纹照与活体识别照对比分数',
  TX_ONLINE_DURATION STRING COMMENT '天行数科-在网时长'
  ,DW_CREATE_BY          STRING    COMMENT '系统字段-创建者'
  ,DW_CREATE_TIME        STRING    COMMENT '系统字段-创建时间'
  ,DW_UPDATE_BY          STRING    COMMENT '系统字段-修改者'
  ,DW_UPDATE_TIME        STRING    COMMENT '系统字段-修改时间')
COMMENT 'MLD订单征信款表'
STORED AS PARQUET 
TBLPROPERTIES ('parquet.compression'='SNAPPY');