drop table if exists DMT_RM.FACT_LOAN_AFTER_STATIC_DAILY;
create table if not exists DMT_RM.FACT_LOAN_AFTER_STATIC_DAILY
(
  APPLY_NO bigint COMMENT '借款ID',
  DISBURSED_DATE string COMMENT '协议生成时间',
  DISBURSED_AMT decimal(18,2)  COMMENT '完成金额',
  TERM int COMMENT '借款期限',
  TERM_UNIT int COMMENT '借款期限单位',
  INTEREST_RATE decimal(18,2)  COMMENT '借款年利率',
  STATUS string COMMENT '还款状态',
  OVERDUE_DAY int COMMENT '当前最大逾期未还天数',
  OVERDUE_DAY_MAX bigint COMMENT '截止当前最大逾期天数',
  OVERDUE_TERM decimal(23,0) COMMENT '未还逾期数',
  OVERDUE_TERM_MAX bigint COMMENT'最大逾期期数',
  OVERDUE_AMT decimal(38,2) ,
  OVERDUE_AMT_MAX decimal(38,2),
  OUTSTANDING_AMT decimal(38,2) COMMENT '未还本金',
  TERM_PAID decimal(23,0) COMMENT '已还期数',
  FILE_DATE string COMMENT '文件日期',
  OVERDUE_PRINCIPAL_AMT decimal(38,2)  COMMENT '逾期未还本金',
  MAX_OVERDUE_PRINCIPAL_AMT decimal(38,2)  COMMENT '最大逾期未还本金',
  PRODUCT string  COMMENT '产品名称',
  PRINCIPAL_TMONTH_AMT decimal(38,2) COMMENT '本月还款本金' ,
  USER_ID bigint  COMMENT '用户ID',
  IS_FIRST_REPAY_OVERDUE_7D int  COMMENT '是否首还逾期大于7天',
  OVERDUE_UNREPAY_AMT decimal(38,2)  COMMENT '逾期未还金额',
  OVERDUE_UNREPAY_L decimal(38,2)  COMMENT '逾期未还利息',
  OVERDUE_UNREPAY_SERVICE_FEE decimal(38,2)  COMMENT '逾期未还平台服务费',
  OVERDUE_UNREPAY_PUNISH decimal(38,2)  COMMENT '逾期未还罚息',
  REPAY_AMT_THIS_MONTH decimal(38,2)  COMMENT '当月1号截止到当前还款金额',
  REPAY_L_THIS_MONTH decimal(38,2)  COMMENT '当月1号截止到当前还款利息',
  REPAY_PUNISH_THIS_MONTH decimal(38,2)  COMMENT '当月1号截止到当前还款罚息',
  REPAY_SERVICE_FEE_THIS_MONTH decimal(38,2)  COMMENT '当月1号截止到当前还款平台服务费',
  SHOULD_B_THIS_MONTH decimal(38,2)  COMMENT '月底之前该还并且未还本金',
  SHOULD_L_THIS_MONTH decimal(38,2)  COMMENT '月底之前该还并且未还利息',
  SHOULD_REPAY_CNT int COMMENT '月底之前该还并且未还期数',
  REPAY_BEGIN_DAY string  COMMENT '起始还款日',
  ZX_PRICE decimal(38,2)  COMMENT '咨询费',
  DW_CREATE_BY         string comment '系统字段-创建者',
  DW_CREATE_TIME       string comment '系统字段-创建时间',
  DW_UPDATE_BY         string comment '系统字段-修改者',
  DW_UPDATE_TIME       string comment '系统字段-修改时间',
  OVERDUE_REPAY_PRICE_B DECIMAL(38,2)  COMMENT '逾期已还本金',
  REPAYED_AMT DECIMAL(38,2)  COMMENT '累计已还金额',
  REPAYED_PRICE_B DECIMAL(38,2)  COMMENT '累计已还本金',
  UNREPAYED_AMT DECIMAL(38,2)  COMMENT '剩余金额',
  ALL_REPAYED_TIME string  COMMENT '结清日期',
  USER_NAME string  COMMENT '用户名',
  OVERDUE_REPAY_PRICE DECIMAL(38,2)  COMMENT '逾期已还金额',
  BR_PRICE_PER_EXPECT DECIMAL(38,2)  COMMENT '每期应还金额',
  REPAYMENT_TYPE STRING  COMMENT '还款方式',
  ACCU_PAID_INT DECIMAL(38,2)  COMMENT '累计已还利息',
  ACCU_PAID_PULISH DECIMAL(38,2)  COMMENT '累计已还罚息', 
  FIRST_REPAY_DATE  string COMMENT '第一次实际还款的日期', 
  RC_NAME  string COMMENT '资方名称',
  REPAYED_OVERDUE_PRICE_B_THIS_MONTH decimal(38,10) COMMENT '本月逾期已还本金',   
  REPAYED_OVERDUE_PRICE_THIS_MONTH decimal(38,10) COMMENT '本月逾期已还利息',   
  SETTLEMENT_SHOULD_REPAY_AMT decimal(38,10) COMMENT '提前结清金额',  
  LAST_REPAYED_TIME string COMMENT '最近还款时间',
  GOODS_ID int COMMENT '产品ID，区分麦芽进件还是美呗进件',
  CUR_PRICE DECIMAL(38,2)  COMMENT '当月应该还的本金')
COMMENT '借款快照'
PARTITIONED BY (STAT_DATE STRING COMMENT '统计日期 年-月-日')
ROW FORMAT DELIMITED
  NULL DEFINED AS ''
STORED AS PARQUET 
TBLPROPERTIES ("parquet.compression"="SNAPPY");
