drop table if exists DMT_RM.FACT_MLD_CREDIT;

CREATE TABLE IF NOT EXISTS DMT_RM.FACT_MLD_CREDIT(
   EXTENTION_NO STRING COMMENT'授信编号',
   CREATE_TIME STRING COMMENT'授信开始时间',
   FINISH_TIME STRING COMMENT'授信完成时间',
   SUCCESS_STATU STRING COMMENT'授信状态',
   FAILED_REASON STRING COMMENT'拒绝原因',
   CREDIT_LINE DECIMAL(38,10) COMMENT'授信额度（基础额度）',
   LBS_XY STRING COMMENT'申请时所在地址（授信位置）',
   NONO_USERID STRING COMMENT'诺诺用户ID',
   CHANNEL_ID STRING COMMENT'用户注册',
   IDCARD STRING COMMENT'身份证',
   SEX INT COMMENT'性别，0：未知，1：男，2：女',
   MOBILE STRING COMMENT'电话',
   USER_TYPE STRING COMMENT'在校大学生学生/已工作',
   COMPANY_NAME STRING COMMENT'公司名称',
   COMPANY_PHONE STRING COMMENT'公司电话号码',
   DETAIL_ADDRESS STRING COMMENT'常住地址',
   MOBILE_CONTACTS INT COMMENT'通讯录联系人个数',
   BLACK_CONTACTS INT COMMENT'通讯录高危标签命中数',
   DW_CREATE_BY     STRING COMMENT'系统字段-创建者',
   DW_CREATE_TIME   STRING COMMENT'系统字段-创建时间',
   DW_UPDATE_BY     STRING COMMENT'系统字段-修改者',
   DW_UPDATE_TIME   STRING COMMENT'系统字段-修改时间'
)
COMMENT'麦粒贷授信表'
STORED AS PARQUET TBLPROPERTIES ("parquet.compression"="SNAPPY");


,FROM_UNIXTIME(UNIX_TIMESTAMP(create_time),'yyyyMMdd') AS STAT_DATE

set hive.map.aggr=true;
set mapreduce.job.queuename = etl-dw;
set hive.groupby.orderby.position.alias=true;
set hive.exec.dynamic.partition.mode=nostrict;
set hive.exec.max.dynamic.partitions.pernode=100000000;
set hive.exec.max.dynamic.partitions=100000000;
set mapreduce.job.name=DMT_RM_FACT_MLD_CREDIT;

INSERT OVERWRITE TABLE DMT_RM.FACT_MLD_CREDIT
SELECT T1.EXTENTION_NO,T1.CREATE_TIME,T1.FINISH_TIME,T1.SUCCESS_STATU,T1.FAILED_REASON,T1.CREDIT_LINE,T1.LBS_XY
,T2.NONO_USERID,T2.CHANNEL_ID,T2.IDCARD,T2.SEX,T2.MOBILE
,(CASE WHEN T3.USER_TYPE=1 THEN '已工作' WHEN T3.USER_TYPE=2 THEN '学生' END) AS USER_TYPE
,T3.COMPANY_NAME,T3.COMPANY_PHONE,T3.DETAIL_ADDRESS
,T4.MOBILE_CONTACTS,T4.BLACK_CONTACTS
,'SYS' AS DW_CREATE_BY
,FROM_UNIXTIME(UNIX_TIMESTAMP(), 'yyyy-MM-dd HH:mm:SS') AS DW_CREATE_TIME
,'SYS' AS DW_UPDATE_BY
,FROM_UNIXTIME(UNIX_TIMESTAMP(), 'yyyy-MM-dd HH:mm:SS') AS DW_UPDATE_TIME
FROM (SELECT EXTENTION_NO,USER_ID,MIN(CREATE_TIME) AS CREATE_TIME,MAX(UPDATE_TIME) AS FINISH_TIME,MAX(SUCCESS) AS SUCCESS_STATU
,MAX(FAILED_REASON) AS FAILED_REASON,MAX(CREDIT_LINE) AS CREDIT_LINE,MAX(LBS_XY) AS LBS_XY
FROM ODS.T_USR_CREDIT_EXTENTION_HIST UCE
WHERE DISABLED=0
AND NVL(EXTENTION_NO,'') <>''
GROUP BY EXTENTION_NO,USER_ID) T1 INNER JOIN ODS.T_USR_USER_HIST T2 
ON T2.ID=T1.USER_ID
AND T2.DISABLED=0
LEFT OUTER JOIN ODS.T_USR_USER_DETAIL_HIST T3
 ON T3.USER_ID = T2.ID
 AND T3.LATEST=1 
 AND T3.DISABLED=0
 LEFT OUTER JOIN (SELECT USER_ID, COUNT(*) AS MOBILE_CONTACTS,SUM(IF( FLAG=1,1,0)) AS BLACK_CONTACTS
 FROM ODS.T_USR_MOBILE_CONTACTS_HIST 
 GROUP BY USER_ID) T4
 ON T2.ID=T4.USER_ID;