
USE mysql;

--  创建用户
CREATE USER  IDW   IDENTIFIED BY 'IDW_MZ_2016';

-- 查看用户权限
SHOW GRANTS FOR IDW;

-- 赋予权限
GRANT ALL PRIVILEGES ON IDW.* TO IDW;
GRANT ALL PRIVILEGES ON TMP.* TO IDW;

-- 权限生效
FLUSH  PRIVILEGES ; -- 注意：修改完权限以后 一定要刷新服务，或者重启服务，刷新服务用：FLUSH PRIVILEGES。

