set mapreduce.job.queuename=etl-dw;

set mapreduce.job.name=IDW_FACT_USER_TAG_10_01;

set hive.groupby.skewindata = true ;
set hive.map.aggr = true ; 
set hive.enforce.bucketing = true;

set hive.exec.parallel=true ;
set hive.exec.dynamic.partition=true;
set hive.exec.dynamic.partition.mode=nonstrict;
set hive.exec.max.dynamic.partitions.pernode=100000000;
set hive.exec.max.dynamic.partitions=100000000;
set hive.exec.max.created.files=100000000;

FROM 
(
  SELECT USER_ID,
         MAX(CASE
               WHEN ID_ASC = 1 THEN
                INVEST_TIME
             END) AS NONO_FIRST_INVEST_TIME,
         MAX(CASE
               WHEN ID_ASC = 1 THEN
                INVEST_AMT
             END) AS NONO_FIRST_INVEST_AMT,
         MAX(CASE
               WHEN ID_ASC = 1 THEN
                INVEST_AMT_YEARLY
             END) AS NONO_FIRST_INVEST_AMT_YEARLY,
         MAX(CASE
               WHEN ID_ASC = 1 THEN
                P_SCOPE
             END) AS NONO_FIRST_INVEST_PRODUCT_SCOPE,
         MAX(CASE
               WHEN ID_ASC = 1 THEN
                EXPECT
             END) AS NONO_FIRST_INVEST_EXPECT,
         MAX(CASE
               WHEN ID_ASC = 2 THEN
                INVEST_TIME
             END) AS NONO_SECOND_INVEST_TIME,
         MAX(CASE
               WHEN ID_ASC = 2 THEN
                INVEST_AMT
             END) AS NONO_SECOND_INVEST_AMT,
         MAX(CASE
               WHEN ID_ASC = 2 THEN
                INVEST_AMT_YEARLY
             END) AS NONO_SECOND_INVEST_AMT_YEARLY,
         MAX(CASE
               WHEN ID_ASC = 2 THEN
                P_SCOPE
             END) AS NONO_SECOND_INVEST_PRODUCT_SCOPE,
         MAX(CASE
               WHEN ID_ASC = 2 THEN
                EXPECT
             END) AS NONO_SECOND_INVEST_EXPECT,
         MAX(CASE
               WHEN ID_ASC = 3 THEN
                INVEST_TIME
             END) AS NONO_THIRD_INVEST_TIME,
         MAX(CASE
               WHEN ID_ASC = 3 THEN
                INVEST_AMT
             END) AS NONO_THIRD_INVEST_AMT,
         MAX(CASE
               WHEN ID_ASC = 3 THEN
                INVEST_AMT_YEARLY
             END) AS NONO_THIRD_INVEST_AMT_YEARLY,
         MAX(CASE
               WHEN ID_ASC = 3 THEN
                P_SCOPE
             END) AS NONO_THIRD_INVEST_PRODUCT_SCOPE,
         MAX(CASE
               WHEN ID_ASC = 3 THEN
                EXPECT
             END) AS NONO_THIRD_INVEST_EXPECT,
         MAX(CASE
               WHEN ID_DESC = 1 THEN
                INVEST_TIME
             END) AS NONO_LAST_INVEST_TIME,
         MAX(CASE
               WHEN ID_DESC = 1 THEN
                INVEST_AMT
             END) AS NONO_LAST_INVEST_AMT,
         MAX(CASE
               WHEN ID_DESC = 1 THEN
                INVEST_AMT_YEARLY
             END) AS NONO_LAST_INVEST_AMT_YEARLY,
         MAX(CASE
               WHEN ID_DESC = 1 THEN
                P_SCOPE
             END) AS NONO_LAST_INVEST_PRODUCT_SCOPE,
         MAX(CASE
               WHEN ID_DESC = 1 THEN
                EXPECT
             END) AS NONO_LAST_INVEST_EXPECT,
         SUM(CASE
               WHEN INVEST_TIME >= date_sub(current_date(), 30) THEN
                1
               ELSE
                0
             END) AS NONO_LAST_30_DAYS_INVEST_CNT,
         COUNT(1) AS NONO_INVEST_CNT,
         SUM(INVEST_AMT) AS NONO_TOTAL_INVEST_AMT,
         SUM(INVEST_AMT_YEARLY) AS NONO_TOTAL_INVEST_AMT_YEARLY,
         SUM(case
               when INVEST_SRC_TAB = 'vip_form' then
                1
             end) AS NONO_TOTAL_PLAN_INVEST_CNT,
         SUM(case
               when INVEST_SRC_TAB = 'vip_form' then
                INVEST_AMT
             end) AS NONO_TOTAL_PLAN_INVEST_AMT,
         SUM(case
               when INVEST_SRC_TAB = 'vip_form' then
                INVEST_AMT_YEARLY
             end) AS NONO_TOTAL_PLAN_INVEST_AMT_YEARLY
    FROM (SELECT A.USER_ID,
                 A.INVEST_TIME,
                 A.INVEST_AMT,
                 A.INVEST_AMT_YEARLY,
                 A.INVEST_SRC_TAB,
                 PRODUCT_CATEGORY P_SCOPE,
                 case expect_unit_code
                   when 1 then
                    concat(cast(expect as string), '日')
                   when 2 then
                    concat(cast(expect as string), '月')
                   when 3 then
                    concat(cast(expect as string), '年')
                   else
                    'NA'
                 end EXPECT,
                 INVEST_NUM ID_ASC,
                 ROW_NUMBER() OVER(PARTITION BY USER_ID ORDER BY INVEST_TIME DESC) ID_DESC
            FROM IDW.FACT_BIZ_NONO_INVEST AS A) AS A
   GROUP BY USER_ID
) OUTPUT
INSERT OVERWRITE TABLE IDW.USER_TAG_TMP_01 PARTITION(TAG_ID=64) SELECT  USER_ID,NONO_FIRST_INVEST_TIME, 4
INSERT OVERWRITE TABLE IDW.USER_TAG_TMP_01 PARTITION(TAG_ID=65) SELECT  USER_ID,NONO_FIRST_INVEST_AMT, 4
INSERT OVERWRITE TABLE IDW.USER_TAG_TMP_01 PARTITION(TAG_ID=66) SELECT  USER_ID,NONO_FIRST_INVEST_PRODUCT_SCOPE, 4
INSERT OVERWRITE TABLE IDW.USER_TAG_TMP_01 PARTITION(TAG_ID=67) SELECT  USER_ID,NONO_SECOND_INVEST_TIME, 4
INSERT OVERWRITE TABLE IDW.USER_TAG_TMP_01 PARTITION(TAG_ID=68) SELECT  USER_ID,NONO_SECOND_INVEST_AMT, 4
INSERT OVERWRITE TABLE IDW.USER_TAG_TMP_01 PARTITION(TAG_ID=69) SELECT  USER_ID,NONO_SECOND_INVEST_PRODUCT_SCOPE, 4
INSERT OVERWRITE TABLE IDW.USER_TAG_TMP_01 PARTITION(TAG_ID=70) SELECT  USER_ID,NONO_THIRD_INVEST_TIME, 4
INSERT OVERWRITE TABLE IDW.USER_TAG_TMP_01 PARTITION(TAG_ID=71) SELECT  USER_ID,NONO_THIRD_INVEST_AMT, 4
INSERT OVERWRITE TABLE IDW.USER_TAG_TMP_01 PARTITION(TAG_ID=72) SELECT  USER_ID,NONO_THIRD_INVEST_PRODUCT_SCOPE, 4
INSERT OVERWRITE TABLE IDW.USER_TAG_TMP_01 PARTITION(TAG_ID=73) SELECT  USER_ID,NONO_LAST_INVEST_TIME, 4
INSERT OVERWRITE TABLE IDW.USER_TAG_TMP_01 PARTITION(TAG_ID=74) SELECT  USER_ID,NONO_LAST_INVEST_AMT, 4
INSERT OVERWRITE TABLE IDW.USER_TAG_TMP_01 PARTITION(TAG_ID=75) SELECT  USER_ID,NONO_LAST_INVEST_PRODUCT_SCOPE, 4
INSERT OVERWRITE TABLE IDW.USER_TAG_TMP_01 PARTITION(TAG_ID=84) SELECT  USER_ID,NONO_LAST_30_DAYS_INVEST_CNT, 4
INSERT OVERWRITE TABLE IDW.USER_TAG_TMP_01 PARTITION(TAG_ID=85) SELECT  USER_ID,NONO_INVEST_CNT, 4
INSERT OVERWRITE TABLE IDW.USER_TAG_TMP_01 PARTITION(TAG_ID=183) SELECT  USER_ID,NONO_TOTAL_INVEST_AMT, 4
INSERT OVERWRITE TABLE IDW.USER_TAG_TMP_01 PARTITION(TAG_ID=221) SELECT  USER_ID,NONO_TOTAL_INVEST_AMT_YEARLY, 4
INSERT OVERWRITE TABLE IDW.USER_TAG_TMP_01 PARTITION(TAG_ID=226) SELECT  USER_ID,NONO_FIRST_INVEST_AMT_YEARLY, 4
INSERT OVERWRITE TABLE IDW.USER_TAG_TMP_01 PARTITION(TAG_ID=227) SELECT  USER_ID,NONO_FIRST_INVEST_EXPECT, 4
INSERT OVERWRITE TABLE IDW.USER_TAG_TMP_01 PARTITION(TAG_ID=228) SELECT  USER_ID,NONO_SECOND_INVEST_AMT_YEARLY, 4
INSERT OVERWRITE TABLE IDW.USER_TAG_TMP_01 PARTITION(TAG_ID=229) SELECT  USER_ID,NONO_SECOND_INVEST_EXPECT, 4
INSERT OVERWRITE TABLE IDW.USER_TAG_TMP_01 PARTITION(TAG_ID=230) SELECT  USER_ID,NONO_THIRD_INVEST_AMT_YEARLY, 4
INSERT OVERWRITE TABLE IDW.USER_TAG_TMP_01 PARTITION(TAG_ID=231) SELECT  USER_ID,NONO_THIRD_INVEST_EXPECT, 4
INSERT OVERWRITE TABLE IDW.USER_TAG_TMP_01 PARTITION(TAG_ID=232) SELECT  USER_ID,NONO_LAST_INVEST_AMT_YEARLY, 4
INSERT OVERWRITE TABLE IDW.USER_TAG_TMP_01 PARTITION(TAG_ID=233) SELECT  USER_ID,NONO_LAST_INVEST_EXPECT, 4
INSERT OVERWRITE TABLE IDW.USER_TAG_TMP_01 PARTITION(TAG_ID=234) SELECT  USER_ID,NONO_TOTAL_PLAN_INVEST_CNT, 4
INSERT OVERWRITE TABLE IDW.USER_TAG_TMP_01 PARTITION(TAG_ID=235) SELECT  USER_ID,NONO_TOTAL_PLAN_INVEST_AMT, 4
INSERT OVERWRITE TABLE IDW.USER_TAG_TMP_01 PARTITION(TAG_ID=236) SELECT  USER_ID,NONO_TOTAL_PLAN_INVEST_AMT_YEARLY, 4
;
-- -------------------------------------------------------------------------------------------------
set mapreduce.job.queuename=etl-dw;

set mapreduce.job.name=IDW_FACT_USER_TAG_10_02;

set hive.exec.parallel=true ;
set hive.groupby.skewindata = true ;
set hive.map.aggr = true ; 
set hive.auto.convert.join=true;
set hive.enforce.bucketing = true;

set hive.exec.dynamic.partition=true;
set hive.exec.dynamic.partition.mode=nonstrict;
set hive.exec.max.dynamic.partitions.pernode=100000000;
set hive.exec.max.dynamic.partitions=100000000;
set hive.exec.max.created.files=100000000;

INSERT OVERWRITE TABLE   IDW.USER_TAG_HIST  PARTITION(TAG_ID,HASH_PARTITION_ID)
SELECT   USER_ID       
        ,TAG_VALUE
        ,'SYS' AS DW_CREATE_BY
        ,FROM_UNIXTIME(UNIX_TIMESTAMP(),'yyyy-MM-dd HH:mm:ss') AS DW_CREATE_TIME
        ,'SYS' AS DW_UPDATE_BY
        ,FROM_UNIXTIME(UNIX_TIMESTAMP(),'yyyy-MM-dd HH:mm:ss') AS DW_UPDATE_TIME
        ,TAG_ID
        ,CAST(PMOD(USER_ID,10) AS INT) HASH_PARTITION_ID 
FROM    IDW.USER_TAG_TMP_01  
WHERE ((TAG_ID >=64 AND TAG_ID <=75) OR TAG_ID in (84,85,183,221) OR (TAG_ID >=226 AND TAG_ID <=236))
  AND USER_ID   IS NOT NULL 
  AND TAG_VALUE IS NOT NULL 
  ;   