
set mapreduce.job.name = IDW_FACT_HOR_DATA;
set mapreduce.job.queuename = etl-dw;
set hive.exec.parallel=true;
set hive.exec.max.created.files=100000000;
set hive.groupby.skewindata=true;

INSERT OVERWRITE TABLE IDW.FACT_HOR_DATA
SELECT concat('01_',DD.ID) AS ID, DH.UUID,DH.USER_CERT_TYPE,DH.USER_CERT_NO,DH.CHANNEL_CODE,DH.CHANNEL_NAME,DC.COLUMN_NAME
,DD.VALUE,DH.STATUS,DH.ID AS HEADER_ID,DD.COLUMN_ID,DH.VERSION as COLUMN_VERSION
,DH.PLATFORM_ID,DH.PLATFORM_NAME,DH.CREATE_TIME as HEADER_CREATE_TIME,DH.UPDATE_TIME as HEADER_UPDATE_TIME
,'SYS' AS DW_CREATE_BY,FROM_UNIXTIME(UNIX_TIMESTAMP(),'yyyy-MM-dd HH:mm:ss') AS DW_CREATE_TIME
,'SYS' AS DW_UPDATE_BY,FROM_UNIXTIME(UNIX_TIMESTAMP(),'yyyy-MM-dd HH:mm:ss') AS DW_UPDATE_TIME
FROM ODS.T_HOR_DATA_HEADER_HIST AS DH INNER JOIN ODS.T_HOR_DATA_COLUMN_HIST AS DC
ON DH.CHANNEL_CODE = DC.CHANNEL_CODE
AND DH.VERSION=DC.VERSION
AND DH.DISABLED=0
AND DC.DISABLED=0
INNER JOIN ODS.T_HOR_DATA_DETAIL_HIST AS DD
ON DD.HEADER_ID = DH.ID
AND DD.COLUMN_ID = DC.ID
AND DD.DISABLED=0
UNION ALL
SELECT concat('02_',DD.ID) AS ID,DH.UUID,DH.USER_CERT_TYPE,DH.USER_CERT_NO,DH.CHANNEL_CODE,DH.CHANNEL_NAME,DD.ITEM_NAME AS COLUMN_NAME
,DD.VALUE,DH.STATUS,DH.ID AS HEADER_ID,NULL AS COLUMN_ID,DH.VERSION as COLUMN_VERSION
,DH.PLATFORM_ID,DH.PLATFORM_NAME,DH.CREATE_TIME as HEADER_CREATE_TIME,DH.UPDATE_TIME as HEADER_UPDATE_TIME
,'SYS' AS DW_CREATE_BY,FROM_UNIXTIME(UNIX_TIMESTAMP(),'yyyy-MM-dd HH:mm:ss') AS DW_CREATE_TIME
,'SYS' AS DW_UPDATE_BY,FROM_UNIXTIME(UNIX_TIMESTAMP(),'yyyy-MM-dd HH:mm:ss') AS DW_UPDATE_TIME
FROM  ODS.T_HOR_TD_DATA_DETAIL_HIST DD INNER JOIN ODS.T_HOR_DATA_HEADER_HIST DH
ON DD.DATA_UUID=DH.UUID
AND DD.DISABLED=0
AND DH.DISABLED=0;
