CREATE TABLE NONO_90_DAYS_AVG_INVEST_CHANGE_LOG (
  STAT_DATE VARCHAR(20)  NOT NULL COMMENT '数据所属日期',
  USER_ID INT NOT NULL COMMENT 'USERID',
  TYPE INT COMMENT '类型：0 存续金额变更，1注册',
  INVEST_AMT DECIMAL(38,10)  COMMENT '昨日投资金额',
  AVG_INVEST_AMT_90 DECIMAL(38,10)  COMMENT '90天平均投资金额',
  DW_CREATE_BY VARCHAR(4) DEFAULT 'SYS' COMMENT '系统字段-创建者',
  DW_CREATE_TIME DATETIME DEFAULT NULL COMMENT '系统字段-创建时间',
  DW_UPDATE_BY VARCHAR(4) DEFAULT 'SYS' COMMENT '系统字段-修改者',
  DW_UPDATE_TIME DATETIME DEFAULT NULL COMMENT '系统字段-修改时间',
  PRIMARY KEY (STAT_DATE,USER_ID)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT='用户存续投资总额变更增量日志表'