CREATE TABLE USER_EXPECTED_REVENUE_YDAY (
  STAT_DATE varchar(20) NOT NULL COMMENT '统计日期',
  USER_ID int(11) NOT NULL COMMENT '用户ID',
  PRO_TYPE varchar(64) NOT NULL COMMENT '产品分类',
  EXPECTED_REVENUE decimal(38,10) unsigned DEFAULT NULL COMMENT '用户收益',
  DW_CREATE_BY varchar(4) DEFAULT 'SYS' COMMENT '系统字段-创建者',
  DW_CREATE_TIME datetime DEFAULT NULL COMMENT '系统字段-创建时间',
  DW_UPDATE_BY varchar(4) DEFAULT 'SYS' COMMENT '系统字段-修改者',
  DW_UPDATE_TIME datetime DEFAULT NULL COMMENT '系统字段-修改时间',
  PRIMARY KEY (STAT_DATE,USER_ID,PRO_TYPE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='用户昨日收益表';