DROP TABLE IF EXISTS DMT_BF.DH_FACT_OVERDUE_BORROWS_END_DAILY;

CREATE TABLE IF NOT EXISTS DMT_BF.DH_FACT_OVERDUE_BORROWS_END_DAILY
(
   OVERDUE_CNT      DECIMAL(38,0) COMMENT '今日逾期总额',
   FIRST_OVERDUE_CNT      DECIMAL(38,0) COMMENT '今日首逾金额',
   FIRST_OVERDUE_RATE DECIMAL(38,10) COMMENT '今日首次逾期率',
   OVERDUE_UNREPAY_PRICE_B DECIMAL(38,10) COMMENT '今日逾期未还本金',
   OVERDUE_UNREPAY_PRICE_L DECIMAL(38,10) COMMENT '今日逾期未还利息',
   OVERDUE_UNREPAY_PRICE_PUNISH DECIMAL(38,10) COMMENT '今日逾期未还罚息',
   OVERDUE_UNREPAY_SERVICE_FEE DECIMAL(38,10) COMMENT '今日逾期未还服务费',
   FIRST_OVERDUE_UNREPAY_PRICE_B DECIMAL(38,10) COMMENT '今日首次逾期未还本金',
   FIRST_OVERDUE_UNREPAY_PRICE_L DECIMAL(38,10) COMMENT '今日首次逾期未还利息',
   FIRST_OVERDUE_UNREPAY_PRICE_PUNISH DECIMAL(38,10) COMMENT '今日首次逾期未还罚息',
   FIRST_OVERDUE_UNREPAY_SERVICE_FEE DECIMAL(38,10) COMMENT '今日首次逾期未还服务费',
   DW_CREATE_BY         STRING COMMENT '系统字段-创建者',
   DW_CREATE_TIME       STRING COMMENT '系统字段-创建时间',
   DW_UPDATE_BY         STRING COMMENT '系统字段-修改者',
   DW_UPDATE_TIME       STRING COMMENT '系统字段-修改时间'
)
COMMENT '每天逾期信息'
PARTITIONED BY (STAT_DATE STRING COMMENT '统计日期 年-月-日')
ROW FORMAT DELIMITED
  NULL DEFINED AS ''
STORED AS PARQUET 
TBLPROPERTIES ("PARQUET.COMPRESSION"="SNAPPY")
;