set mapreduce.job.queuename=etl-dw;
set mapreduce.job.name=DMT_CS_CSYY_USER_INFO_FOR_INC_UPDATE_01;

INSERT OVERWRITE TABLE DMT_CS.CSYY_USER_INFO_FOR_INC_UPDATE
  select USER_ID,
         USER_NAME,
         substr(REAL_NAME,1,1) LAST_NAME,
         case GENDER when 1 then 0 when 2 then 1 else -1 end GENDER,
         FINANCE_ADVISOR,
         RECOMMENDER,
         CURRENT_CITY_NAME,
         BIRTHDAY,
         REGISTER_TIME,
         LAST_LOGIN_TIME,
         CSYY_CHANNEL_NAME,
         CSYY_MAX_AUM,
         CSYY_AUM,
         'SYS' AS DW_CREATE_BY,
         FROM_UNIXTIME(UNIX_TIMESTAMP(),'yyyy-MM-dd HH:mm:ss') AS DW_CREATE_TIME,
         'SYS' AS DW_UPDATE_BY,
         FROM_UNIXTIME(UNIX_TIMESTAMP(),'yyyy-MM-dd HH:mm:ss') AS DW_UPDATE_TIME
    from (SELECT t1.USER_ID,
                 NVL(MAX(CASE WHEN TAG_ID=2 THEN CAST(TAG_VALUE AS STRING) END),NULL) AS USER_NAME,
                 NVL(MAX(CASE WHEN TAG_ID=3 THEN CAST(TAG_VALUE AS STRING) END),NULL) AS REAL_NAME,
                 NVL(MAX(CASE WHEN TAG_ID=4 THEN CAST(TAG_VALUE AS INT) END),NULL) AS GENDER, 
                 NVL(MAX(CASE WHEN TAG_ID=186 THEN CAST(TAG_VALUE AS BIGINT) END),NULL) AS FINANCE_ADVISOR,
                 NVL(MAX(CASE WHEN TAG_ID=46 THEN CAST(TAG_VALUE AS BIGINT) END),NULL) AS RECOMMENDER,
                 NVL(MAX(CASE WHEN TAG_ID=90 THEN CAST(TAG_VALUE AS STRING) END),NULL) AS CURRENT_CITY_NAME,
                 NVL(MAX(CASE WHEN TAG_ID=20 THEN CAST(TAG_VALUE AS STRING) END),NULL) AS BIRTHDAY,
                 NVL(MAX(CASE WHEN TAG_ID=8 THEN CAST(TAG_VALUE AS STRING) END),NULL) AS REGISTER_TIME,
                 NVL(MAX(CASE WHEN TAG_ID=41 THEN CAST(TAG_VALUE AS STRING) END),NULL) AS LAST_LOGIN_TIME,
                 NVL(MAX(CASE WHEN TAG_ID=175 THEN CAST(TAG_VALUE AS STRING) END),NULL) AS CSYY_CHANNEL_NAME,
                 NVL(MAX(CASE WHEN TAG_ID=115 THEN CAST(TAG_VALUE AS DECIMAL(38,10)) END),NULL) AS CSYY_MAX_AUM,
                 NVL(MAX(CASE WHEN TAG_ID=114 THEN CAST(TAG_VALUE AS DECIMAL(38,10)) END),NULL) AS CSYY_AUM,
                 NVL(MAX(CASE WHEN TAG_ID=97 THEN CAST(TAG_VALUE AS STRING) END),NULL) AS CSYY_FIRST_INVEST_TIME,
                 NVL(MAX(CASE WHEN TAG_ID=185 THEN CAST(TAG_VALUE AS STRING) END),NULL) AS REGISTER_BIZ,
                 NVL(MAX(CASE WHEN TAG_ID=14 THEN CAST(TAG_VALUE AS INT) END),NULL) AS IS_CHEAT
            FROM IDW.USER_TAG_HIST t1
            join ods.t_user_info_hist t2
              on t1.user_id = t2.id
           WHERE TAG_ID in (2, 3, 4, 186, 46, 90, 20, 8, 41, 175, 115, 114, 97, 185, 14)
           GROUP BY t1.USER_ID) x
   where (CSYY_FIRST_INVEST_TIME is not null or REGISTER_BIZ = 'csyy')
     and user_id not in (12027, 920272)
     and IS_CHEAT = 0;