drop table if exists idw.fact_in_repay_borrows_plus_snapshot;


CREATE TABLE idw.fact_in_repay_borrows_plus_snapshot 
(
    bo_id                                       bigint              comment '借款ID'
    ,user_id                                    bigint              comment '用户ID'
    ,statis_dt                                  string              comment '统计日期'
    ,p_key                                      int                 comment 'p_key'
    ,bia_prduct                                 string              comment 'BIA产品名称'
    ,biz_name                                   string              comment 'BIA业务线'
    
    ,is_overdue_unrepay                         int                 comment '是否当前逾期未还'
    ,overdue_unrepay_days                       int                 comment '当前逾期未还天数'
    ,overdue_unrepay_expect_cnt                 bigint              comment '当前逾期未还期数'
    ,aging                                      string              comment '账龄'
    
    ,is_overdue                                 int                 comment '是否有过逾期'
    ,max_overdue_days                           int                 comment '最大逾期天数'
    ,overdue_expect_cnt                         bigint              comment '历史累计逾期期数'
    
    ,unrepay_cnt                                bigint              comment '未还期数'
    ,unrepay_price                              decimal(38,10)      comment '未还金额'
    ,unrepay_price_b                            decimal(38,10)      comment '未还本金'
    ,unrepay_price_l                            decimal(38,10)      comment '未还利息'
    ,unrepay_price_punish                       decimal(38,10)      comment '未还罚息'
    ,unrepay_service_fee                        decimal(38,10)      comment '未还服务费'
    ,unrepay_price_return                       decimal(38,10)      comment '未返还金额'
    ,unrepay_extra_fee                          decimal(38,10)      comment '未还贷后管理费'
    ,unrepay_service_fee_other                  decimal(38,10)      comment '未还第三方服务费'
    ,unrepay_post_consult_fee                   decimal(38,10)      comment '未还后置咨询费'
    
    ,due_repaid_cnt                             bigint              comment '到期已还期数'
    ,due_repaid_price_b                         decimal(38,10)      comment '到期已还本金'
    ,due_repaid_price_l                         decimal(38,10)      comment '到期已还利息'
    ,due_repaid_punish                          decimal(38,10)      comment '到期已还罚息'
    ,due_repaid_service_fee                     decimal(38,10)      comment '到期已还服务费'
    ,due_repaid_extra_fee                       decimal(38,10)      comment '到期已还贷后管理费'
    ,due_repaid_service_fee_other               decimal(38,10)      comment '到期已还第三方服务费'
    ,due_repaid_post_consult_fee                decimal(38,10)      comment '到期已还后置咨询费'
    
    ,due_unrepay_cnt                            bigint              comment '到期未还期数'    
    ,due_unrepay_price_b                        decimal(38,10)      comment '到期未还本金'
    ,due_unrepay_price_l                        decimal(38,10)      comment '到期未还利息'
    ,due_unrepay_punish                         decimal(38,10)      comment '到期未还罚息'
    ,due_unrepay_service_fee                    decimal(38,10)      comment '到期未还服务费'
    ,due_unrepay_extra_fee                      decimal(38,10)      comment '到期未还贷后管理费'
    ,due_unrepay_service_fee_other              decimal(38,10)      comment '到期未还第三方服务费'
    ,due_unrepay_post_consult_fee               decimal(38,10)      comment '到期未还后置咨询费'
    
    ,due_cnt                                    bigint              comment '应还期数'
    ,due_price                                  decimal(38,10)      comment '应还金额'
    ,due_price_b                                decimal(38,10)      comment '应还本金'
    ,due_price_l                                decimal(38,10)      comment '应还利息'
    ,due_price_punish                           decimal(38,10)      comment '应还罚息'
    ,due_service_fee                            decimal(38,10)      comment '应还服务费'
    ,due_price_return                           decimal(38,10)      comment '应返还金额'
    ,due_extra_fee                              decimal(38,10)      comment '应还贷后管理费'
    ,due_service_fee_other                      decimal(38,10)      comment '应还第三方服务费'
    ,due_post_consult_fee                       decimal(38,10)      comment '应还后置咨询费'
    
    ,repayed_cnt                                bigint              comment '已还期数'
    ,repayed_price                              decimal(38,10)      comment '已还金额'
    ,repayed_price_b                            decimal(38,10)      comment '已还本金'
    ,repayed_price_l                            decimal(38,10)      comment '已还利息'
    ,repayed_price_punish                       decimal(38,10)      comment '已还罚息'
    ,repayed_service_fee                        decimal(38,10)      comment '已还服务费'
    ,repayed_price_return                       decimal(38,10)      comment '已还服务费'
    ,repayed_extra_fee                          decimal(38,10)      comment '已还贷后管理费'
    ,repayed_service_fee_other                  decimal(38,10)      comment '已还第三方服务费'
    ,repayed_post_consult_fee                   decimal(38,10)      comment '已还后置咨询费'
    
    ,repayed_cnt_this_month                     bigint              comment '本月已还期数'
    ,repayed_price_this_month                   decimal(38,10)      comment '本月已还金额'
    ,repayed_price_b_this_month                 decimal(38,10)      comment '本月已还本金'
    ,repayed_price_l_this_month                 decimal(38,10)      comment '本月已还利息'
    ,repayed_price_punish_this_month            decimal(38,10)      comment '本月已还罚息'
    ,repayed_service_fee_this_month             decimal(38,10)      comment '本月已还服务费'
    ,repayed_price_return_this_month            decimal(38,10)      comment '本月已返还金额'
    ,repayed_extra_fee_this_month               decimal(38,10)      comment '本月已还贷后管理费'
    ,repayed_service_fee_other_this_month       decimal(38,10)      comment '本月已还第三方服务费'
    ,repayed_post_consult_fee_this_month        decimal(38,10)      comment '本月已还后置咨询费'
    
    ,compensate_amt                             decimal(38,10)      comment '代偿金额'
    ,compensate_price_b                         decimal(38,10)      comment '代偿本金'
    ,repayed_compensate_amt                     decimal(38,10)      comment '已还代偿金额'
    ,repayed_compensate_price_b                 decimal(38,10)      comment '已还代偿本金'
    ,unrepay_compensate_amt                     decimal(38,10)      comment '未还代偿金额'
    ,unrepay_compensate_price_b                 decimal(38,10)      comment '未还代偿本金'
    
    ,overdue_repayed_price                      decimal(38,10)      comment '逾期已还金额'
    
    ,repay_begin_day                            string              comment '起始计划还款日'
    ,repay_end_day                              string              comment '最终计划还款日'
    ,first_repay_time                           string              comment '首次还款时间'
    ,last_repayed_time                          string              comment '最近还款时间'
    ,overdue_unrepay_price                      decimal(38,10)      comment '逾期未还金额'
    ,overdue_unrepay_price_b                    decimal(38,10)      comment '逾期未还本金'
    ,overdue_unrepay_price_l                    decimal(38,10)      comment '逾期未还利息'
    ,overdue_unrepay_price_punish               decimal(38,10)      comment '逾期未还罚息'
    ,overdue_unrepay_service_fee                decimal(38,10)      comment '逾期未还服务费'
    ,cur_price                                  decimal(38,10)      comment '当期应还金额'
    ,cur_price_b                                decimal(38,10)      comment '当期应还本金'
    ,cur_price_l                                decimal(38,10)      comment '当期应还利息'
    ,cur_service_fee                            decimal(38,10)      comment '当期应还平台服务费'
    ,overdue_returned_price                     decimal(38,10)      comment '逾期已返还金额'
    ,overdue_unreturned_price                   decimal(38,10)      comment '逾期未返还金额'
    ,overdue_unrepay_earliest_br_time           string              comment '逾期未还最早还应还时间'
    
    ,settlement_should_repay_amt                decimal(38,12)      comment '提前结清需还金额'
    ,posted_bill_num                            bigint              comment '已出账单期数'
    ,posted_bill_unrepay_amt                    decimal(38,10)      comment '已出账单未还金额'
    ,pending_bill_unrepay_b                     decimal(38,10)      comment '未出账单本金'
    
    ,dun_company                                bigint              comment '催收服务商'
    ,dun_company_name                           string              comment '催收服务商名称'
    ,dun_start_time                             string              comment '催收开始时间'
    ,dun_end_time                               string              comment '催收结束时间'
    ,dun_type                                   int                 comment '催收类型 0:委外 1:内催'
    ,is_dunning                                 int                 comment '是否在催收'
    
    ,max_continuous_overdue_price_b             decimal(38,10)      comment '最大连续逾期本金'
    ,max_continuous_overdue_cnt                 int                 comment '最大连续逾期期数'
    
    ,is_first_repay_overdue                     int                 comment '是否首还逾期'
    ,first_repay_overdue_days                   int                 comment '首还逾期天数'
    ,bo_success_time                            string              comment '完成时间'
    ,bo_finish_price                            decimal(38,10)      comment '完成金额'
    ,bo_rate                                    decimal(38,10)      comment '借款年利率'
    ,bo_expect                                  int                 comment '借款期限'
    ,bo_expect_cat                              int                 comment '借款期限单位'
    ,bo_audit_time                              string              comment '审核时间'
    ,bo_agree_time                              string              comment '协议生成时间'
    ,depository_flag                            int                 comment '存管标记 0:初始 1:走存管 2:不走存管'
    ,interest_rate_cut                          decimal(38,10)      comment '减息'
    ,first_overdue_expect_num                   int                 comment '首次逾期期数'
    ,first_overdue_br_time                      string              comment '首次逾期应还时间'
    ,monthly_repayment_amt                      decimal(38,10)      comment '月还款金额'
    ,transfer_account_time                      string              comment '实际划转成功时间'
    ,p_id                                       bigint              comment '产品ID'
    ,category_name_01                           string              comment '产品分类01'
    ,p_name                                     string              comment '产品名称'
    ,biz_code_01                                string              comment '业务线编码01'
    ,biz_name_01                                string              comment '业务线名称01'
    ,busi_line                                  string              comment '所属业务线'
    ,dw_create_by                               string              comment '系统字段-创建者'
    ,dw_create_time                             string              comment '系统字段-创建时间'
    ,dw_update_by                               string              comment '系统字段-修改者'
    ,dw_update_time                             string              comment '系统字段-修改时间'
)
comment '在还快照表'
partitioned by (stat_date string comment '统计日期 年-月-日')
row format delimited
null defined as ''
stored as parquet
tblproperties ("parquet.compression"="snappy")
;


