USE IDWOPR;
DROP VIEW IF EXISTS IDWOPR.USER_TAG_HIST;
CREATE VIEW IF NOT EXISTS IDWOPR.USER_TAG_HIST (
TAG_ID                   COMMENT '标签ID',
HASH_PARTITION_ID           COMMENT '二级分区',
USER_ID          COMMENT '用户ID',
TAG_VALUE         COMMENT '标签值',
DW_CREATE_BY      COMMENT '数据更新人',
DW_CREATE_TIME     COMMENT '数据更新时间',
DW_UPDATE_BY      COMMENT '数据更新人',
DW_UPDATE_TIME     COMMENT '数据更新时间'
)AS
SELECT 
TAG_ID
,HASH_PARTITION_ID
,USER_ID
,TAG_VALUE
,DW_CREATE_BY
,DW_CREATE_TIME
,DW_UPDATE_BY
,DW_UPDATE_TIME
FROM IDW.USER_TAG_HIST;