DROP TABLE IF EXISTS DMT_CRM.NONO_USER_ACTIVITY_LABEL;

CREATE TABLE DMT_CRM.NONO_USER_ACTIVITY_LABEL(
  USER_ID BIGINT COMMENT '用户ID',
  CURRENT_USER_ACTIVE_STATUS STRING COMMENT '用户当前活跃状态',
  BEFORE30D_USER_ACTIVE_STATUS STRING COMMENT '用户30天前活跃状态',
  DW_CREATE_TIME STRING COMMENT '创建时间',
  DW_UPDATE_TIME STRING COMMENT '更新时间'
) COMMENT '诺诺用户活跃度'
STORED AS PARQUET TBLPROPERTIES ("PARQUET.COMPRESSION"="SNAPPY");