CREATE TABLE DMT_CRM.NONO_USER_ACTIVITY_LABEL(
  USER_ID BIGINT COMMENT '用户ID',
  CURRENT_USER_ACTIVE_STATUS VARCHAR(16) COMMENT '用户当前活跃状态',
  BEFORE30D_USER_ACTIVE_STATUS  VARCHAR(16) COMMENT '用户30天前活跃状态',
  DW_CREATE_BY VARCHAR(64)  COMMENT '创建人',
  DW_CREATE_TIME  DATETIME   COMMENT '创建时间',
  DW_UPDATE_BY VARCHAR(64) COMMENT '修改人',
  DW_UPDATE_TIME DATETIME COMMENT '更新时间',
  PRIMARY KEY(USER_ID)
);