-- JOB 层面监控 ，从昨天00:00:00 到 当前时间点
-- 日报
SELECT 
        
         B.JOB_TYPE
        , A.JOB_ID
        ,COUNT(JOB_ID) AS TOTAL_CNT -- 总运行次数
        ,SUM(TASK_QTY) AS TOTAL_QTY
        
        ,COUNT(CASE WHEN STATUS= 0 THEN JOB_ID ELSE NULL END) AS S_CNT 
        ,SUM(CASE WHEN STATUS= 0 THEN TASK_QTY ELSE NULL END) AS S_QTY  
        
        ,COUNT(CASE WHEN STATUS= -1 THEN JOB_ID ELSE NULL END) AS F_CNT -- 包含运行任务失败的和初始化失败的
        ,SUM(CASE WHEN STATUS= -1 THEN TASK_F_QTY ELSE NULL END) AS F_QTY          
              
        ,COUNT(CASE WHEN STATUS= 1  THEN JOB_ID ELSE NULL END) AS RUNNING_CNT  -- 运行中
        ,COUNT(CASE WHEN STATUS= -3 THEN JOB_ID ELSE NULL END) AS DISABLE_CNT  -- 手动禁用
        ,COUNT(CASE WHEN STATUS= -2 THEN JOB_ID ELSE NULL END) AS CONFLICT_CNT  -- 冲突禁用
        
        ,ROUND(MIN(CASE WHEN STATUS NOT IN (1,-2,-3) AND TASK_QTY<>0 THEN TIMESTAMPDIFF(MINUTE,JOB_BEGIN_DATE,JOB_END_DATE) END ),2) AS MIN_TIME
        ,ROUND(AVG(TIMESTAMPDIFF(MINUTE,JOB_BEGIN_DATE,JOB_END_DATE)) ,2)  AS AVGTIME    
        ,ROUND(MAX(TIMESTAMPDIFF(MINUTE,JOB_BEGIN_DATE,JOB_END_DATE)),2) AS MAX_TIME   
FROM
        ETL.ETL_CONTROL_JOB_LOG A
        LEFT JOIN ETL.ETL_CONTROL_JOB B
        ON A.JOB_ID=B.ID
        WHERE  JOB_BEGIN_DATE>= DATE_ADD(CURDATE(),INTERVAL -1 DAY)  -- 从昨天00:00:00 到 当前时间点
GROUP BY B.JOB_TYPE
        , A.JOB_ID
ORDER BY  A.JOB_ID

