-- task 层面监控 ，从昨天00:00:00 到 当前时间点
-- 日报
SELECT        

         A.TASK_ID
         ,IFNULL(B.`TO_TABLE_NAME`,C.`TASK_NAME`) TASK_NAME
         ,IFNULL(B.`REFRESH_FREQ_NAME`,C.`REFRESH_FREQ_NAME`) `REFRESH_FREQ_NAME`
         ,IFNULL(B.`JOB_TYPE`,C.`JOB_TYPE`) JOB_TYPE
         
        ,COUNT(TASK_ID) AS TOTAL_CNT -- 总运行次数
        ,COUNT(CASE WHEN STATUS= 0 THEN TASK_ID ELSE NULL END) AS S_CNT         
        ,COUNT(CASE WHEN STATUS= -1 THEN TASK_ID ELSE NULL END) AS F_CNT -- 包含运行任务失败的和初始化失败的 
        ,COUNT(CASE WHEN STATUS= 1  THEN TASK_ID ELSE NULL END) AS RUNNING_CNT  -- 运行中
       
        
        ,ROUND(MIN(CASE WHEN STATUS NOT IN (1,-1)  THEN TIMESTAMPDIFF(MINUTE,TASK_BEGIN_TIME,TASK_END_TIME) END ),2) AS MIN_TIME
        ,ROUND(AVG(CASE WHEN STATUS NOT IN (1,-1)  THEN TIMESTAMPDIFF(MINUTE,TASK_BEGIN_TIME,TASK_END_TIME) END ),2)  AS AVGTIME    
        ,ROUND(MAX(CASE WHEN STATUS NOT IN (1,-1)  THEN TIMESTAMPDIFF(MINUTE,TASK_BEGIN_TIME,TASK_END_TIME) END ),2) AS MAX_TIME         
        
FROM
        ETL.ETL_CONTROL_TASK_LOG A
                LEFT JOIN ETL_CONTROL_TASK_M2M B 
                ON A.TASK_ID = B.ID 
        LEFT JOIN ETL_CONTROL_TASK_DW C 
                ON A.TASK_ID = C.ID 
        WHERE  (B.RUN_FLAG = 1 OR C.RUN_FLAG = 1 ) AND TASK_BEGIN_TIME>=DATE_ADD(CURDATE(),INTERVAL -1 DAY)  -- 从昨天00:00:00 到 当前时间点
GROUP BY  A.TASK_ID
         ,IFNULL(B.`TO_TABLE_NAME`,C.`TASK_NAME`)
         ,IFNULL(B.`REFRESH_FREQ_NAME`,C.`REFRESH_FREQ_NAME`) 
         ,IFNULL(B.`JOB_TYPE`,C.`JOB_TYPE`) 

