-- task 超时监控
-- 时报或更短
SELECT     
          A.JOB_ID   
         ,IFNULL(B.JOB_TYPE,C.JOB_TYPE) JOB_TYPE  
         ,A.RUN_ID  
         ,A.TASK_ID
         ,IFNULL(B.TO_TABLE_NAME,C.TASK_NAME) TASK_NAME
         ,IFNULL(B.REFRESH_FREQ_NAME,C.REFRESH_FREQ_NAME) REFRESH_FREQ_NAME
         ,A.TASK_BEGIN_TIME  
FROM
        ETL.ETL_CONTROL_TASK_LOG A
                LEFT JOIN ETL_CONTROL_TASK_M2M B 
                ON A.TASK_ID = B.ID 
        LEFT JOIN ETL_CONTROL_TASK_DW C 
                ON A.TASK_ID = C.ID 
        WHERE  (B.RUN_FLAG = 1 OR C.RUN_FLAG = 1 ) AND TASK_BEGIN_TIME>=DATE_ADD(CURDATE(),INTERVAL -1 DAY)   -- 从昨天00:00:00 到 当前时间点
        AND (A.STATUS=1 OR A.TASK_END_TIME IS NULL)
        AND (TIMESTAMPDIFF(MINUTE,A.TASK_BEGIN_TIME,SYSDATE()) >B.RUN_TIME_LENGTH  OR TIMESTAMPDIFF(MINUTE,A.TASK_BEGIN_TIME,SYSDATE()) >C.RUN_TIME_LENGTH )

