drop table if exists idw.fact_borrows_repayment;
CREATE TABLE idw.fact_borrows_repayment         
(
	br_id BIGINT COMMENT '还款ID'
	,p_id BIGINT COMMENT '产品ID'
	,busi_line STRING COMMENT '所属业务线'
	,user_id BIGINT COMMENT '用户ID'
	,bo_id BIGINT COMMENT '借款ID'
	,br_price DECIMAL(38,10) COMMENT '还款金额'
	,br_price_b DECIMAL(38,10) COMMENT '本金'
	,br_price_l DECIMAL(38,10) COMMENT '利息'
	,br_price_punish DECIMAL(38,10) COMMENT '罚息和违约金'
	,br_service_fee DECIMAL(38,10) COMMENT '平台服务费'
	,price_return DECIMAL(38,10) COMMENT '使用减息券之后平台返回给借入者的资金'
	,br_price_punish_lender DECIMAL(38,10) COMMENT '罚金借出者收取'
	,br_price_punish_pc DECIMAL(38,10) COMMENT '罚金机构收取'
	,br_time STRING COMMENT '计划还款时间'
	,br_repay_time STRING COMMENT '实际还款时间'
	,br_is_repay INT COMMENT '是否还款'
	,br_repay_status INT COMMENT '还款状态'
	,br_transfer_fa_id BIGINT COMMENT '债转对应的fa_id'
	,br_call_record STRING COMMENT '电话记录'
	,br_repayed_tech_fee DECIMAL(38,10) COMMENT '当期归还的技术的服务费'
	,dunning_way STRING COMMENT '催收方式'
	,br_locked INT COMMENT '是否锁定'
	,br_overdue_terms INT COMMENT '当前逾期总数'
	,br_is_hnapay_deduct INT COMMENT '是否代划扣'
	,br_is_send_sms INT COMMENT '是否已发送短信通知'
	,br_expect_num INT COMMENT '当前标的第几期还款数据'
	,is_first_repay_overdue INT COMMENT '是否首还逾期'
	,is_first_overdue INT COMMENT '是否首次逾期'
	,is_compensate INT COMMENT '是否代偿'
	,compensate_time STRING COMMENT '代偿时间'
	,is_compensate_returned INT COMMENT '是否归还代偿'
	,compensate_returned_time STRING COMMENT '代偿归还时间'
	,creator BIGINT COMMENT '创建人'
	,updator BIGINT COMMENT '更新人'
	,create_time STRING COMMENT '创建时间'
	,update_time STRING COMMENT '更新时间'
	,dw_create_by STRING COMMENT '系统字段-创建者'
	,dw_create_time STRING COMMENT '系统字段-创建时间'
	,dw_update_by STRING COMMENT '系统字段-修改者'
	,dw_update_time STRING COMMENT '系统字段-修改时间'
	,bo_agree_time STRING COMMENT '协议生成时间'
	,category_name_01 STRING COMMENT '产品分类01'
	,biz_code_01 STRING COMMENT '业务线编码01'
	,biz_name_01 STRING COMMENT '业务线名称01'
	,depository_flag INT COMMENT '存管标记 0:初始 1:走存管 2:不走存管'
	,transfer_account_time STRING COMMENT '实际划转成功时间'
	,p_name STRING COMMENT '产品名称'
	,p_key INT COMMENT '产品代理键'
	,br_extra_fee DECIMAL(38,10) COMMENT '额外费用'
	,br_service_fee_other DECIMAL(38,10) COMMENT '其他服务费(星河服务费)'
	,br_post_consult_fee DECIMAL(38,10) COMMENT '后置咨询费' 
    ,is_graduate STRING COMMENT '是否已毕业'
)
COMMENT '借入者还款表'
STORED AS PARQUET
;

