set mapreduce.job.name = DMT_RM_FACT_HOR_DATA;
set mapreduce.job.queuename = etl-dw;
set hive.exec.dynamic.partition.mode=nostrict;
set hive.exec.max.dynamic.partitions.pernode=100000000;
set hive.exec.max.dynamic.partitions=100000000;
set hive.exec.parallel=true;

INSERT OVERWRITE TABLE DMT_RM.FACT_HOR_DATA PARTITION (DAY_ID)
SELECT T.ID,T.HEADER_ID,T.COLUMN_ID,T.USER_CERT_NO,T.CHANNEL_CODE,T.CHANNEL_NAME,T.VERSION,T.PLATFORM_ID,T.PLATFORM_NAME
,T.USER_CERT_TYPE,T.STATUS,T.COLUMN_NAME,T.VALUE,UCI.BO_ID,T.CREATE_TIME,T.UPDATE_TIME
,'SYS' AS DW_CREATE_BY,
FROM_UNIXTIME(UNIX_TIMESTAMP(),'yyyy-MM-dd HH:mm:ss') AS DW_CREATE_TIME
,'SYS' AS DW_UPDATE_BY,FROM_UNIXTIME(UNIX_TIMESTAMP(),'yyyy-MM-dd HH:mm:ss') AS DW_UPDATE_TIME
,FROM_UNIXTIME(UNIX_TIMESTAMP(T.CREATE_TIME),'yyyy-MM-dd') AS DAY_ID
FROM (SELECT concat('01_',DD.ID) AS ID, DH.ID AS HEADER_ID,DD.COLUMN_ID,DH.USER_CERT_NO,DH.CHANNEL_CODE,DH.CHANNEL_NAME,DH.VERSION,DH.PLATFORM_ID
,DH.PLATFORM_NAME,DH.USER_CERT_TYPE,DH.STATUS,DC.COLUMN_NAME,DD.VALUE,DH.CREATE_TIME,DH.UPDATE_TIME,DH.UUID
FROM ODS.T_HOR_DATA_HEADER_HIST AS DH INNER JOIN ODS.T_HOR_DATA_COLUMN_HIST AS DC
ON DH.CHANNEL_CODE = DC.CHANNEL_CODE
AND DH.VERSION=DC.VERSION
AND DH.DISABLED=0
AND DC.DISABLED=0
INNER JOIN ODS.T_HOR_DATA_DETAIL_HIST AS DD
ON DD.HEADER_ID = DH.ID
AND DD.COLUMN_ID = DC.ID
AND DD.DISABLED=0
UNION ALL
SELECT concat('02_',DD.ID) AS ID, DH.ID AS HEADER_ID,NULL AS COLUMN_ID,DH.USER_CERT_NO,DH.CHANNEL_CODE,DH.CHANNEL_NAME,DH.VERSION,DH.PLATFORM_ID
  ,DH.PLATFORM_NAME,DH.USER_CERT_TYPE,DH.STATUS,DD.ITEM_NAME AS COLUMN_NAME,DD.VALUE,DH.CREATE_TIME,DH.UPDATE_TIME,DH.UUID
FROM  ODS.T_HOR_TD_DATA_DETAIL_HIST DD INNER JOIN ODS.T_HOR_DATA_HEADER_HIST DH
ON DD.DATA_UUID=DH.UUID
AND DD.DISABLED=0
AND DH.DISABLED=0) T
LEFT OUTER JOIN (
select REPORT_ID,max(bo_id) as bo_id from  ODS.T_USER_CREDIT_INVESTIGATION_HIST 
group by REPORT_ID
) AS UCI
ON T.UUID=UCI.REPORT_ID;