-- 代码0
-- 1.创建表语句
DROP TABLE IF EXISTS IDW.DIM_USER_TAG_CODE;

CREATE TABLE IF NOT EXISTS IDW.DIM_USER_TAG_CODE
(
   ID                   INT    COMMENT '代理键（主键）',
   TAG_NAME             STRING COMMENT '标签名（英文字段名）',
   TAG_NAME_CN          STRING COMMENT '标签名中文',
   TAG_DESC             STRING COMMENT '标签描述',
   TAG_CLASS            STRING COMMENT '标签类型',
   TAG_CATEGORY_01      STRING COMMENT '标签分类1',
   TAG_CATEGORY_02      STRING COMMENT '标签分类2',
   TAG_CATEGORY_03      STRING COMMENT '标签分类3',
   NULL_VALUE           STRING COMMENT '空值填充值',
   TAG_DATA_TYPE        STRING COMMENT '标签数据类型',
   DW_CREATE_BY         STRING COMMENT '系统字段-创建者',
   DW_CREATE_TIME       STRING COMMENT '系统字段-创建时间',
   DW_UPDATE_BY         STRING COMMENT '系统字段-修改者',
   DW_UPDATE_TIME       STRING COMMENT '系统字段-修改时间'
) 
COMMENT '用户标签维表'
STORED AS PARQUET TBLPROPERTIES ("parquet.compression"="SNAPPY");
;


DROP TABLE IF EXISTS IDW.USER_TAG_HIST;
CREATE TABLE IF NOT EXISTS IDW.USER_TAG_HIST
(   
   USER_ID              BIGINT COMMENT '用户唯一标识',  
   TAG_VALUE            STRING COMMENT '用户标签值',
   DW_CREATE_BY         STRING COMMENT '系统字段-创建者',
   DW_CREATE_TIME       STRING COMMENT '系统字段-创建时间',
   DW_UPDATE_BY         STRING COMMENT '系统字段-修改者',
   DW_UPDATE_TIME       STRING COMMENT '系统字段-修改时间'
) 
COMMENT '用户标签事实表'
PARTITIONED BY (TAG_ID INT COMMENT '用户标签编码', HASH_PARTITION_ID INT COMMENT '用户唯一标识哈希值')
STORED AS PARQUET TBLPROPERTIES ("parquet.compression"="SNAPPY");
;

USE IDWOPR;
DROP VIEW IF EXISTS IDWOPR.USER_TAG_HIST;
CREATE VIEW IF NOT EXISTS IDWOPR.USER_TAG_HIST 
(
    TAG_ID              COMMENT '标签ID',
    HASH_PARTITION_ID   COMMENT '二级分区',
    USER_ID             COMMENT '用户ID',
    TAG_VALUE           COMMENT '标签值',
    DW_CREATE_BY        COMMENT '数据更新人',
    DW_CREATE_TIME      COMMENT '数据更新时间',
    DW_UPDATE_BY        COMMENT '数据更新人',
    DW_UPDATE_TIME      COMMENT '数据更新时间'
)
AS
SELECT 
    TAG_ID
    ,HASH_PARTITION_ID
    ,USER_ID
    ,TAG_VALUE
    ,DW_CREATE_BY
    ,DW_CREATE_TIME
    ,DW_UPDATE_BY
    ,DW_UPDATE_TIME
FROM IDW.USER_TAG_HIST;



/* 标签覆盖方法 
    0：直接覆盖； 
    1：取最小值； 
    2：取最大值；
    3：在历史数据上追加 A|B|C；
    4: 每次均全量计算（不需要做merge）； 
*/

USE IDW ;
DROP TABLE IF EXISTS IDW.USER_TAG_TMP_01;
CREATE TABLE IF NOT EXISTS IDW.USER_TAG_TMP_01
( 
    USER_ID BIGINT COMMENT'用户ID' 
    ,TAG_VALUE STRING COMMENT'用户标签值'
    ,TAG_COVER_TYPE_IND STRING COMMENT'用户标签覆盖方式'
)
PARTITIONED BY(TAG_ID INT) 
CLUSTERED BY (USER_ID) SORTED BY (USER_ID ASC) INTO 10 BUCKETS
STORED AS PARQUET; 


USE IDW ;
DROP TABLE IF EXISTS IDW.USER_TAG_TMP_02;
CREATE TABLE IDW.USER_TAG_TMP_02
( 
    USER_ID BIGINT COMMENT'用户ID' 
    ,TAG_VALUE STRING COMMENT'用户标签值'
    ,TAG_COVER_TYPE_IND STRING COMMENT'用户标签覆盖方式'
)
COMMENT'用户标签增量表' 
PARTITIONED BY(TAG_ID INT) 
CLUSTERED BY (USER_ID) SORTED BY (USER_ID ASC) INTO 10 BUCKETS
STORED AS PARQUET;  

--添加分区
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=1);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=2);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=3);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=4);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=5);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=6);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=7);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=8);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=9);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=10);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=11);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=12);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=13);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=14);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=15);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=16);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=17);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=18);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=19);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=20);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=21);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=22);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=23);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=24);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=25);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=26);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=27);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=28);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=29);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=30);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=31);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=32);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=33);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=34);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=35);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=36);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=37);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=38);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=39);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=40);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=41);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=42);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=43);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=44);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=45);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=46);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=47);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=48);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=49);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=50);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=51);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=52);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=53);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=54);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=55);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=56);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=57);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=58);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=59);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=60);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=61);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=62);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=63);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=64);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=65);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=66);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=67);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=68);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=69);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=70);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=71);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=72);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=73);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=74);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=75);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=76);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=77);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=78);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=79);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=80);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=81);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=82);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=83);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=84);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=85);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=86);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=87);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=88);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=89);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=90);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=91);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=92);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=93);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=94);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=95);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=96);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=97);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=98);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=99);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=100);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=101);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=102);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=103);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=104);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=105);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=106);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=107);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=108);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=109);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=110);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=111);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=112);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=113);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=114);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=115);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=116);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=117);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=118);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=119);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=120);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=121);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=122);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=123);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=124);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=125);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=126);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=127);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=128);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=129);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=130);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=131);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=132);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=133);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=134);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=135);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=136);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=137);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=138);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=139);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=140);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=141);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=142);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=143);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=144);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=145);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=146);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=147);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=148);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=149);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=150);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=151);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=152);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=153);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=154);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=155);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=156);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=157);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=158);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=159);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=160);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=161);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=162);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=163);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=164);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=165);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=166);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=167);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=168);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=169);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=170);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=171);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=172);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=173);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=174);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=175);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=176);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=177);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=178);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=179);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=180);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=181);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=182);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=183);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=184);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=185);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=186);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=187);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=188);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=189);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=190);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=191);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=192);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=193);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=194);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=195);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=196);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=197);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=198);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=199);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=200);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=201);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=202);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=203);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=204);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=205);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=206);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=207);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=208);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=209);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=210);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=211);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=212);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=213);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=214);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=215);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=216);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=217);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=218);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=219);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=220);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=221);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=222);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=223);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=224);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=225);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=226);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=227);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=228);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=229);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=230);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=231);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=232);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=233);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=234);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=235);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=236);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=237);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=238);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=239);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=240);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=241);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=242);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=243);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=244);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=245);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=246);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=247);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=248);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=249);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=250);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=251);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=252);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=253);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=254);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=255);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=256);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=257);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=258);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=259);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=260);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=261);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=262);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=263);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=264);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=265);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=266);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=267);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=268);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=269);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=270);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=271);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=272);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=273);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=274);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=275);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=276);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=277);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=278);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=279);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=280);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=281);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=282);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=283);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=284);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=285);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=286);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=287);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=288);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=289);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=290);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=291);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=292);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=293);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=294);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=295);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=296);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=297);
ALTER TABLE IDW.USER_TAG_TMP_01 ADD PARTITION(TAG_ID=298);

ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=1);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=2);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=3);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=4);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=5);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=6);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=7);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=8);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=9);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=10);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=11);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=12);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=13);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=14);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=15);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=16);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=17);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=18);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=19);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=20);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=21);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=22);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=23);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=24);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=25);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=26);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=27);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=28);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=29);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=30);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=31);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=32);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=33);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=34);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=35);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=36);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=37);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=38);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=39);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=40);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=41);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=42);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=43);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=44);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=45);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=46);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=47);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=48);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=49);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=50);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=51);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=52);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=53);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=54);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=55);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=56);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=57);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=58);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=59);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=60);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=61);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=62);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=63);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=64);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=65);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=66);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=67);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=68);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=69);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=70);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=71);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=72);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=73);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=74);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=75);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=76);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=77);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=78);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=79);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=80);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=81);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=82);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=83);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=84);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=85);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=86);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=87);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=88);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=89);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=90);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=91);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=92);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=93);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=94);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=95);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=96);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=97);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=98);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=99);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=100);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=101);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=102);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=103);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=104);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=105);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=106);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=107);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=108);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=109);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=110);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=111);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=112);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=113);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=114);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=115);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=116);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=117);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=118);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=119);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=120);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=121);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=122);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=123);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=124);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=125);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=126);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=127);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=128);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=129);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=130);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=131);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=132);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=133);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=134);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=135);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=136);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=137);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=138);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=139);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=140);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=141);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=142);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=143);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=144);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=145);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=146);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=147);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=148);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=149);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=150);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=151);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=152);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=153);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=154);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=155);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=156);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=157);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=158);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=159);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=160);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=161);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=162);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=163);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=164);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=165);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=166);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=167);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=168);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=169);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=170);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=171);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=172);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=173);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=174);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=175);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=176);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=177);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=178);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=179);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=180);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=181);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=182);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=183);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=184);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=185);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=186);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=187);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=188);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=189);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=190);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=191);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=192);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=193);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=194);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=195);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=196);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=197);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=198);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=199);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=200);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=201);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=202);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=203);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=204);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=205);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=206);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=207);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=208);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=209);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=210);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=211);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=212);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=213);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=214);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=215);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=216);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=217);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=218);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=219);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=220);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=221);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=222);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=223);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=224);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=225);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=226);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=227);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=228);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=229);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=230);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=231);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=232);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=233);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=234);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=235);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=236);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=237);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=238);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=239);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=240);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=241);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=242);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=243);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=244);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=245);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=246);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=247);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=248);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=249);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=250);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=251);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=252);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=253);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=254);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=255);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=256);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=257);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=258);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=259);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=260);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=261);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=262);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=263);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=264);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=265);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=266);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=267);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=268);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=269);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=270);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=271);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=272);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=273);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=274);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=275);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=276);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=277);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=278);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=279);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=280);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=281);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=282);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=283);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=284);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=285);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=286);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=287);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=288);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=289);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=290);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=291);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=292);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=293);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=294);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=295);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=296);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=297);
ALTER TABLE IDW.USER_TAG_TMP_02 ADD PARTITION(TAG_ID=298);
