--第一版数据结构

--对象表(用户手工填写)
CREATE TABLE `ETL_DQ_OBJECT` (
  id INT NOT NULL AUTO_INCREMENT COMMENT '主键',
  `object_name` VARCHAR(20) NOT NULL COMMENT 'object_name',
  `object_type` INT COMMENT '如table 1，多个file内容对比',
  `jndi_id` INT(11)  COMMENT 'jndi_id 或文件路径',
   is_valid INT COMMENT '0 inactive;1 active',
  `DW_CREATE_BY` VARCHAR(64) DEFAULT 'SYS' COMMENT '系统字段-创建者',
  `DW_CREATE_TIME` DATETIME DEFAULT NULL COMMENT '系统字段-创建时间',
  `DW_UPDATE_BY` VARCHAR(64) DEFAULT 'SYS' COMMENT '系统字段-修改者',
  `DW_UPDATE_TIME` DATETIME DEFAULT NULL COMMENT '系统字段-修改时间',
  PRIMARY KEY (id)
) ENGINE=INNODB DEFAULT CHARSET=utf8 ;

--表存储位置(系统自带配置)
CREATE TABLE `ETL_DQ_JNDI` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键 ID',
  `JNDI_NAME` VARCHAR(64) NOT NULL COMMENT 'JNDI名称',
  `JNDI_1` CHAR(255) NOT NULL COMMENT 'IP地址或文件路径',
  `JNDI_2` CHAR(255) NOT NULL COMMENT '端口',
  `JNDI_3` CHAR(255) NOT NULL COMMENT 'SCHEMA',
  `JNDI_4` CHAR(255) NOT NULL COMMENT 'N',
  `JNDI_5` CHAR(255) NOT NULL COMMENT 'P',
  `JNDI_DESC` VARCHAR(1024) DEFAULT NULL,
  `DW_CREATE_BY` VARCHAR(64) DEFAULT 'SYS' COMMENT '系统字段-创建者',
  `DW_CREATE_TIME` DATETIME DEFAULT NULL COMMENT '系统字段-创建时间',
  `DW_UPDATE_BY` VARCHAR(64) DEFAULT 'SYS' COMMENT '系统字段-修改者',
  `DW_UPDATE_TIME` DATETIME DEFAULT NULL COMMENT '系统字段-修改时间',
  PRIMARY KEY (`ID`)
) ENGINE=INNODB AUTO_INCREMENT=41 DEFAULT CHARSET=utf8  

--规则(系统自带配置)
CREATE TABLE `ETL_DQ_RULE` (
  id INT NOT NULL AUTO_INCREMENT COMMENT '',
  `rule_name` VARCHAR(20) NOT NULL COMMENT 'rule_name',
  `rule_DES`  VARCHAR(1000) COMMENT 'rule_DES',
  is_valid INT COMMENT '0 inactive;1 active',
  `DW_CREATE_BY` VARCHAR(64) DEFAULT 'SYS' COMMENT '系统字段-创建者',
  `DW_CREATE_TIME` DATETIME DEFAULT NULL COMMENT '系统字段-创建时间',
  `DW_UPDATE_BY` VARCHAR(64) DEFAULT 'SYS' COMMENT '系统字段-修改者',
  `DW_UPDATE_TIME` DATETIME DEFAULT NULL COMMENT '系统字段-修改时间',
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 ;



--指标统计项配置表(用户手工填写)
CREATE TABLE `ETL_DQ_ITEM` (
  id VARCHAR(20)  NOT NULL  COMMENT 'I开头',
  `ITEM_name` VARCHAR(20) NOT NULL COMMENT 'ITEM_name',
  `ITEM_DES`  VARCHAR(1000) COMMENT 'ITEM_DES',
  object_id INT COMMENT '关联object',
  rule_id INT COMMENT '关联rule 非自定义时填写',
  col1 VARCHAR(64) COMMENT '字段1 非自定义时填写',
  col2 VARCHAR(64) COMMENT '字段2 非自定义时填写',
  col3 VARCHAR(64) COMMENT '字段3 非自定义时填写',
  col4 VARCHAR(64) COMMENT '字段3 非自定义时填写',
  col5 VARCHAR(64) COMMENT '字段3 非自定义时填写',
  sqltext text COMMENT '自定义sql，第一版本不允许聚合操作,多表关联也只允许同一DB内，后续允许最多6列/多行',
  is_valid INT COMMENT '0 false;1 true',
  `DW_CREATE_BY` VARCHAR(64) DEFAULT 'SYS' COMMENT '系统字段-创建者',
  `DW_CREATE_TIME` DATETIME DEFAULT NULL COMMENT '系统字段-创建时间',
  `DW_UPDATE_BY` VARCHAR(64) DEFAULT 'SYS' COMMENT '系统字段-修改者',
  `DW_UPDATE_TIME` DATETIME DEFAULT NULL COMMENT '系统字段-修改时间',
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 ;

--指标统计项结果表
CREATE TABLE `ETL_DQ_ITEM_RESULT` (
  id INT NOT NULL AUTO_INCREMENT COMMENT '',
  `ITEM_ID` VARCHAR(20)   COMMENT 'ITEM_ID',
  object_id INT COMMENT '关联object--冗余',
  rule_id INT COMMENT '关联rule--冗余',
  sqltext text COMMENT 'sqltext KPI具体sql内容',
  sqlresult VARCHAR(64) COMMENT '语句执行结果，当前版本一条sql只允许一列一行的结果值',
  `STATUS` INT COMMENT '状态0成功；1进行中；-1失败;2 待统计',
  `start_TIME` DATETIME DEFAULT NULL COMMENT '起始时间',
  `end_TIME` DATETIME DEFAULT NULL COMMENT '起始时间',
  `DW_CREATE_BY` VARCHAR(64) DEFAULT 'SYS' COMMENT '系统字段-创建者', -- STAT_DATE
  `DW_CREATE_TIME` DATETIME DEFAULT NULL COMMENT '系统字段-创建时间',
  `DW_UPDATE_BY` VARCHAR(64) DEFAULT 'SYS' COMMENT '系统字段-修改者',
  `DW_UPDATE_TIME` DATETIME DEFAULT NULL COMMENT '系统字段-修改时间',
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 ;

--比对配置表(用户手工填写)
CREATE TABLE `ETL_DQ_COMPARE` (
  id VARCHAR(20) NOT NULL COMMENT 'C开头',
  `COMPARE_NAME` VARCHAR(64) COMMENT '对比名称', 
  `COMPARE_DES` VARCHAR(64) COMMENT '对比描述', 
  `ITEM_PRIMARY` VARCHAR(20) COMMENT 'kpi_ID--驱动主object',
  `ITEM_COMPARE_01` VARCHAR(20) COMMENT 'kpi_ID--被驱动/从object当前设置以下最多4个 BCDE',
  `ITEM_COMPARE_02` VARCHAR(20) COMMENT 'kpi_ID',
  `ITEM_COMPARE_03` VARCHAR(20) COMMENT 'kpi_ID',
  `ITEM_COMPARE_04` VARCHAR(20) COMMENT 'kpi_ID',
   `COMPARE_method` VARCHAR(64) COMMENT '格式要求：X [比较符号] Y [运算符号] ...Yn 如A=B或A=B+C+D-E或者A>0，不允许A+B=C+D', 
   `COMPARE_PRIORITY` INT COMMENT '对比优先级',
   is_valid INT COMMENT '0 false;1 true',
  `DW_CREATE_BY` VARCHAR(64) DEFAULT 'SYS' COMMENT '系统字段-创建者',
  `DW_CREATE_TIME` DATETIME DEFAULT NULL COMMENT '系统字段-创建时间',
  `DW_UPDATE_BY` VARCHAR(64) DEFAULT 'SYS' COMMENT '系统字段-修改者',
  `DW_UPDATE_TIME` DATETIME DEFAULT NULL COMMENT '系统字段-修改时间',
    PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 ;



--比对结果表
CREATE TABLE `ETL_DQ_COMPARE_RESULT` (
  id INT NOT NULL AUTO_INCREMENT COMMENT '',
  object_id INT COMMENT 'A的object_name (报表特殊需求)',
  `COMPARE_ID` VARCHAR(20) NOT NULL COMMENT 'COMPARE_ID',
   COMPARE_content text COMMENT 'compare content 具体对比内容, 0+10=2+8',
   `result` INT COMMENT '0 true/1 false 报表汇总展现',
    `STATUS` INT COMMENT '状态0成功；1进行中；-1失败;2 待统计',
 `STATE_TIME` DATETIME DEFAULT NULL COMMENT '对比起始时间',
  `DW_CREATE_BY` VARCHAR(64) DEFAULT 'SYS' COMMENT '系统字段-创建者',
  `DW_CREATE_TIME` DATETIME DEFAULT NULL COMMENT '系统字段-创建时间',
  `DW_UPDATE_BY` VARCHAR(64) DEFAULT 'SYS' COMMENT '系统字段-修改者',
  `DW_UPDATE_TIME` DATETIME DEFAULT NULL COMMENT '系统字段-修改时间',
      PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 ;


--后台调度详细日志
CREATE TABLE `ETL_DQ_LOG_DETAIL` (
  `ID`  VARCHAR(20)  COMMENT 'ID',
    `EVENT_TYPE` VARCHAR(64) NOT NULL COMMENT '事件类型',
  `EVENT_name` VARCHAR(64) NOT NULL COMMENT '事件名称',
  `EVENT_TIME` VARCHAR(64) NOT NULL COMMENT '事件时间',
  `EVENT_DESC` VARCHAR(2048) DEFAULT NULL COMMENT '事件描述',
    PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT='Kettle详细日志表';
