DROP TABLE IF EXISTS `BBS_ARTICLE_WDZJ`;

CREATE TABLE `BBS_ARTICLE_WDZJ` (
  `ID` int(10) NOT NULL AUTO_INCREMENT COMMENT "自增id",
  `RUN_ID` varchar(20) DEFAULT NULL COMMENT "任务id",
  `ARTICLE_NAME` varchar(100) DEFAULT NULL COMMENT "文章名称",
  `ARTICLE_ID` varchar(20) DEFAULT NULL COMMENT "文章id",
  `ARTICLE_URL` varchar(100) DEFAULT NULL COMMENT "文章url",
  `ARTICLE_USER` varchar(20) DEFAULT NULL COMMENT "文章作者",
  `ARTICLE_TIME` datetime DEFAULT NULL COMMENT "文章时间",
  `ARTICLE_THEME` varchar(20) DEFAULT NULL COMMENT "文章主题",
  `ARTICLE_CONTENT` TEXT DEFAULT NULL COMMENT "文章内容",
  `ARTICLE_TAGS` varchar(50) DEFAULT NULL COMMENT "文章标签",
  `ARTICLE_PV` int(10) DEFAULT NULL COMMENT "文章浏览量",
  `ARTICLE_REPLIED` int(10) DEFAULT NULL COMMENT "文章回复数",
  `ARTICLE_KEYWORDS` varchar(50)  DEFAULT NULL COMMENT "文章关键字",
  `INSERT_TIME` datetime DEFAULT NULL COMMENT "插入时间",
  `UPDATE_TIME` datetime DEFAULT NULL COMMENT "更新时间",
  `UPDATE_NUM` int(10) NOT NULL DEFAULT '0' COMMENT "更新次数",
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT "网贷之家BBS文章";