DROP TABLE IF EXISTS `BBS_REPLY_WDZJ`;

CREATE TABLE `BBS_REPLY_WDZJ` (
  `ID` int(10) NOT NULL AUTO_INCREMENT COMMENT "自增id",
  `RUN_ID` varchar(20) DEFAULT NULL COMMENT "任务id",
  `ARTICLE_ID` varchar(20) DEFAULT NULL COMMENT "文章id",
  `REPLY_USER` varchar(20) DEFAULT NULL COMMENT "回复作者",
  `REPLY_TIME` datetime DEFAULT NULL COMMENT "回复时间",
  `REPLY_CONTENT` TEXT DEFAULT NULL COMMENT "回复内容",
  `REPLY_ID` varchar(20) DEFAULT NULL COMMENT "回复id",
  `INSERT_TIME` datetime DEFAULT NULL COMMENT "插入时间",
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT "网贷之家BBS文章回复";