CREATE TABLE `IPC_PAIPAIDAI_PRODUCT_PAIHUOBAO` (
  `ID` int(10) NOT NULL AUTO_INCREMENT COMMENT '自增ID',
  `RUN_ID` varchar(50) DEFAULT NULL COMMENT '任务ID',
  `PRODUCT_NAME` varchar(50) DEFAULT NULL COMMENT '产品名称',
  `PRODUCT_URL` varchar(255) DEFAULT NULL COMMENT '产品URL',
  `PROFIT` varchar(50) DEFAULT NULL COMMENT '收利率',
  `PROFIT_INFO` varchar(50) DEFAULT NULL COMMENT '收利率相关信息',
  `BANLANCE` int(50) DEFAULT NULL COMMENT '剩余',
  `ACCUMULATE_INVEST` int(50) DEFAULT NULL COMMENT '累积投资金额',
  `ACCUMULATE_PEOPLE` int(50) DEFAULT NULL COMMENT '累计购买人数',
  `ACCUMULATE_PROFIT` int(50) DEFAULT NULL COMMENT '累计收益金额',
  `OTHER_INFO` varchar(50) DEFAULT NULL COMMENT '其他信息',
  `INSERT_TIME` datetime NOT NULL COMMENT '插入时间',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8 COMMENT='行业产品-拍拍贷产品-拍活宝表';