CREATE TABLE `IPC_PAIPAIDAI_PRODUCT_CAIHONGJIHUA` (
  `ID` int(10) NOT NULL AUTO_INCREMENT COMMENT '自增id',
  `RUN_ID` varchar(50) DEFAULT NULL COMMENT '任务ID',
  `PRODUCT_NAME` varchar(50) DEFAULT NULL COMMENT '产品名称',
  `PRODUCT_URL` varchar(255) DEFAULT NULL COMMENT '产品URL',
  `COMMODITY_NAME` varchar(50) DEFAULT NULL COMMENT '商品名称',
  `COMMODITY_URL` varchar(255) DEFAULT NULL COMMENT '商品url',
  `COMMODITY_INVEST_TERM` varchar(50) DEFAULT NULL COMMENT '商品期限',
  `COMMODITY_PROFIT` varchar(50) DEFAULT NULL COMMENT '商品收益率',
  `COMMODITY_SCHEDULE` varchar(50) DEFAULT NULL COMMENT '商品投资进度',
  `COMMODITY_BANLANCE` int(50) DEFAULT NULL COMMENT '商品',
  `OTHER_INFO` varchar(50) DEFAULT NULL COMMENT '其他信息',
  `INSERT_TIME` datetime NOT NULL COMMENT '插入时间',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=183 DEFAULT CHARSET=utf8 COMMENT='行业产品-拍拍贷产品-彩虹计划表';