DROP TABLE IF EXISTS `KEY_WORDS_CRAWL`;

CREATE TABLE `KEY_WORDS_CRAWL` (
  `ID` int(10) NOT NULL AUTO_INCREMENT COMMENT "自增id",
  `PLATFORM_ID` int(10) DEFAULT NULL COMMENT "平台id",
  `PLATFORM_NAME` varchar(20) DEFAULT NULL COMMENT "平台名称",
  `PLATFORM_URL` varchar(100) DEFAULT NULL COMMENT "平台url",
  `KEYWORD` varchar(20) DEFAULT NULL COMMENT "关键字",
  `KEYWORD_URL` varchar(100) DEFAULT NULL COMMENT "关键字url",
  `FREQUENCY` varchar(10) DEFAULT NULL COMMENT "抓取频率",
  `ENABLED` int(10) DEFAULT NULL COMMENT "是否启用",
  `INSERT_TIME` datetime DEFAULT NULL COMMENT "插入时间",
  `UPDATE_TIME` datetime DEFAULT NULL COMMENT "修改时间",
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT "爬取关键字表";