DROP TABLE IF EXISTS `KEYWORD_FREQ_CRAWL`;

CREATE TABLE `KEYWORD_FREQ_CRAWL` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT COMMENT "自增id",
  `RUN_TIME` DATETIME DEFAULT NULL COMMENT "运行时间",
  `CREATE_TIME` DATETIME DEFAULT NULL COMMENT "创建时间",
  `PLATFORM_NAME` VARCHAR(20) DEFAULT NULL COMMENT "平台名称",
  `KEYWORD` VARCHAR(20) DEFAULT NULL COMMENT "关键字",
  `RELATED_WORDS` VARCHAR(20) DEFAULT NULL COMMENT "相关字",
  `IS_COMMENDATORY_TERM`  INT(10) NULL COMMENT "是否为褒义词 1:褒义词 0:贬义词",
  `FREQ`  INT(10) NULL COMMENT "相关字频数",
  `INSERT_TIME`  DATETIME DEFAULT NULL COMMENT "插入时间",
  PRIMARY KEY (`ID`)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8  COMMENT"关键字解析结果表"; 