DROP TABLE IF EXISTS `NLP_CRAWL`;

CREATE TABLE `NLP_CRAWL` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT COMMENT "自增id",
  `TASK_ID` VARCHAR(20) DEFAULT NULL COMMENT "任务id",
  `PLATFORM_ID` VARCHAR(20) DEFAULT NULL COMMENT "平台id {1:POSTS_BDTB表;2:POST_CONTENTS_BDTB表;3:BBS_ARTICLE_WDZJ表;4:BBS_REPLY_WDZJ表}",
  `CONTENT_ID` VARCHAR(20) DEFAULT NULL COMMENT "内容id{POSTS_BDTB表:POST_ID;POST_CONTENTS_BDTB表:FLOOR_ID;BBS_ARTICLE_WDZJ表:ARTICLE_ID;BBS_REPLY_WDZJ表:REPLY_ID}",
  `CODE` INT(10) DEFAULT NULL COMMENT "错误码",
  `MESSAGE` VARCHAR(20) DEFAULT NULL COMMENT "错误信息",
  `NEG_KEYWORD_TF` VARCHAR(100) DEFAULT NULL COMMENT "TOP10负面情感词词频",
  `NEGATIVE` VARCHAR(20) DEFAULT NULL COMMENT "负面情感概率",
  `POS_KEYWORD_TF` VARCHAR(100) DEFAULT NULL COMMENT "TOP10正面情感词词频",
  `POSITIVE` VARCHAR(20) DEFAULT NULL COMMENT "正面情感概率",
  `INSERT_TIME` DATETIME DEFAULT NULL COMMENT "插入时间",
  PRIMARY KEY (`ID`)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT  CHARSET=utf8 COMMENT "自然语言分析结果表";