DROP TABLE IF EXISTS `NLP_FEEDBACK_NZT`; 

CREATE TABLE `NLP_FEEDBACK_NZT` (
  `TASK_ID` varchar(20) DEFAULT NULL COMMENT '任务id',
  `TABLE_NAME` varchar(18) NOT NULL COMMENT '数据来源表名',
  `NEG_KEYWORD_TF` varchar(100) DEFAULT NULL COMMENT '负分词频',
  `NEGATIVE` varchar(20) DEFAULT NULL COMMENT '负分',
  `POS_KEYWORD_TF` varchar(100) DEFAULT NULL COMMENT '正分词频',
  `POSITIVE` varchar(20) DEFAULT NULL COMMENT '正分',
  `NLP_COMMENTS` mediumtext DEFAULT NULL COMMENT '参与NPL的数据',
  `URL` varchar(100) DEFAULT NULL COMMENT '相关内容网站',
  `SCORE_BY_NZT` float DEFAULT NULL COMMENT '牛子铜个人评分',
  `INSERT_TIME` datetime DEFAULT NULL COMMENT '插入时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '自然语言评分反馈表';