
DROP TABLE IF EXISTS `POSTS_BDTB`;

CREATE TABLE `POSTS_BDTB` (
  `ID` int(10) NOT NULL AUTO_INCREMENT COMMENT "自增id",
  `RUN_ID` varchar(20) DEFAULT NULL COMMENT "任务id",
  `TB_NAME` varchar(20) DEFAULT NULL COMMENT "贴吧名",
  `POST_ID` varchar(20) DEFAULT NULL COMMENT "帖子id",
  `POST_USER` varchar(20) DEFAULT NULL COMMENT "帖子作者",
  `POST_TITLE` varchar(100) DEFAULT NULL COMMENT "帖子名称",
  `IS_GOOD` int(10) NOT NULL COMMENT "是否加精",
  `POST_REP_NUM` int(10) DEFAULT NULL COMMENT "回复数量",
  `LAST_REP_USER` varchar(20) DEFAULT NULL COMMENT "最后回复人",
  `LAST_REP_DATE` varchar(20) DEFAULT NULL COMMENT "最后回复时间",
  `INSERT_TIME` datetime DEFAULT NULL COMMENT "插入时间",
  `UPDATE_TIME` datetime DEFAULT NULL COMMENT "更新时间",
  `UPDATE_NUM` int(10) NOT NULL DEFAULT '0' COMMENT "更新数量",
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT "百度贴吧帖子索引";