DROP TABLE IF EXISTS `POST_CONTENTS_BDTB`;

CREATE TABLE `POST_CONTENTS_BDTB` (
  `ID` int(10) NOT NULL AUTO_INCREMENT COMMENT "自增id",
  `RUN_ID` varchar(20) DEFAULT NULL COMMENT "任务id",
  `POST_ID` varchar(20) DEFAULT NULL COMMENT "帖子id",
  `FLOOR_ID` varchar(20) DEFAULT NULL COMMENT "楼层id",
  `FLOOR_USER` varchar(50) DEFAULT NULL COMMENT "楼层作者",
  `USER_TITLE` varchar(50) DEFAULT NULL COMMENT "作者贴吧登记",
  `FLOOR_CONTENTS` TEXT DEFAULT NULL COMMENT "楼层内容",
  `FLOOR_IN_FLOOR_NUM` int(10) DEFAULT NULL COMMENT "楼中楼数量",
  `FLOOR_NUM` int(10) DEFAULT NULL COMMENT "楼层数",
  `CREATE_TIME` datetime DEFAULT NULL COMMENT "楼层建立时间",
  `INSERT_TIME` datetime DEFAULT NULL COMMENT "插入时间",
  `UPDATE_TIME` datetime DEFAULT NULL COMMENT "更新时间",
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT "百度贴吧帖子回复";