
DROP TABLE IF EXISTS `TASK_CRAWL`;

CREATE TABLE `TASK_CRAWL` (
  `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT "自增id",
  `TASK_ID` varchar(20) DEFAULT NULL COMMENT "任务id",
  `PLATFORM_ID` varchar(20) DEFAULT NULL COMMENT "平台id",
  `START_TIME` datetime DEFAULT NULL COMMENT "开始时间",
  `END_TIME` datetime DEFAULT NULL COMMENT "结束时间",
  `REQUEST_COUNT` int(10) DEFAULT NULL COMMENT "请求数量",
  `RESPONSE_COUNT` int(10) DEFAULT NULL COMMENT "响应数量",
  `EXCEPTION_COUNT` int(10) DEFAULT NULL COMMENT "异常数量",
  `RESPONSE_STATUS_200_COUNT` int(10) DEFAULT NULL COMMENT "200响应数量",
  `ERROR_COUNT` int(10) DEFAULT NULL COMMENT "错误数量",
  `INSERT_TIME` datetime DEFAULT NULL COMMENT "插入时间",
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT "爬虫任务结果表";