set mapreduce.job.name = DMT_FACT_NONO_USER_ACTIVITY_INFO_01;
set mapreduce.job.queuename = etl-dw;
set hive.exec.dynamic.partition.mode=nonstrict;

INSERT OVERWRITE TABLE DMT.FACT_NONO_USER_ACTIVITY_INFO PARTITION(STAT_DATE) 
SELECT USER_ID,
       NVL(MAX(CASE WHEN TAG_ID=8 THEN CAST(TAG_VALUE AS STRING) END),NULL) AS REGISTER_TIME  ,
       NVL(MAX(CASE WHEN TAG_ID=9 THEN CAST(TAG_VALUE AS INT) END),NULL) AS IS_AUTHENTICATION  ,
       NVL(MAX(CASE WHEN TAG_ID=57 THEN CAST(TAG_VALUE AS STRING) END),NULL) AS FIRST_BIND_CARD_TIME  ,
       NVL(MAX(CASE WHEN TAG_ID=64 THEN CAST(TAG_VALUE AS STRING) END),NULL) AS FIRST_INVEST_TIME  ,
       NVL(MAX(CASE WHEN TAG_ID=92 THEN CAST(TAG_VALUE AS INT) END),NULL) AS LAST_30_DAYS_LOGIN_CNT  ,
       NVL(MAX(CASE WHEN TAG_ID=93 THEN CAST(TAG_VALUE AS INT) END),NULL) AS LAST_60_DAYS_LOGIN_CNT  ,
       NVL(MAX(CASE WHEN TAG_ID=94 THEN CAST(TAG_VALUE AS INT) END),NULL) AS LAST_30_DAYS_VIEW_COLUMN_CNT  ,
       NVL(MAX(CASE WHEN TAG_ID=95 THEN CAST(TAG_VALUE AS INT) END),NULL) AS LAST_30_DAYS_VIEW_PRODUCT_CNT  ,
       NVL(MAX(CASE WHEN TAG_ID=84 THEN CAST(TAG_VALUE AS INT) END),NULL) AS LAST_30_DAYS_INVEST_CNT  ,
       NVL(MAX(CASE WHEN TAG_ID=85 THEN CAST(TAG_VALUE AS INT) END),NULL) AS INVEST_CNT  ,
       NVL(MAX(CASE WHEN TAG_ID=68 THEN CAST(TAG_VALUE AS DECIMAL(38,10)) END),NULL) AS SECOND_INVEST_AMT  ,
       NVL(MAX(CASE WHEN TAG_ID=96 THEN CAST(TAG_VALUE AS INT) END),NULL) AS LAST_30_DAYS_CLICK_THIRD_ICON_CNT  ,
       NVL(MAX(CASE WHEN TAG_ID=86 THEN CAST(TAG_VALUE AS INT) END),NULL) AS PROLOCUTOR_INVITE_REGISTER_CNT  ,      
       'SYS' AS DW_CREATE_BY
       ,FROM_UNIXTIME(UNIX_TIMESTAMP(),'yyyy-MM-dd HH:mm:ss') AS DW_CREATE_TIME
       ,'SYS' AS DW_UPDATE_BY
       ,FROM_UNIXTIME(UNIX_TIMESTAMP(),'yyyy-MM-dd HH:mm:ss') AS DW_UPDATE_TIME,        
       FROM_UNIXTIME(UNIX_TIMESTAMP() -1*24*60*60,'yyyy-MM-dd') AS STAT_DATE
FROM IDW.USER_TAG_HIST
WHERE TAG_ID IN (8,9,57,64,92,93,94,95,84,85,68,96,86)
GROUP BY USER_ID;