set mapreduce.job.name = IDW_FACT_RM_DES_MAIN;
set mapreduce.job.queuename = etl-dw;
set hive.exec.parallel=true;

INSERT OVERWRITE TABLE IDW.FACT_RM_DES_MAIN
  select 'SYS' as dw_create_by,
         from_unixtime(unix_timestamp(), 'yyyy-MM-dd HH:mm:ss') as dw_create_time,
         'SYS' as dw_update_by,
         from_unixtime(unix_timestamp(), 'yyyy-MM-dd HH:mm:ss') as dw_update_time,
         t.bp_id,
         bp.p_id,
         p.category_name_01,
         p.biz_code_01,
         p.biz_name_01,
         t.user_id,
         t.user_name,
         t.real_name,
         t.query_name,
         t.user_age,
         t.user_census_address,
         t.current_address,
         t.home_address,
         t.province_code,
         t.province_name,
         t.email,
         t.user_gender,
         t.user_id_number,
         t.user_mobile,
         t.user_kin_mobile,
         t.school_academy,
         t.school_company_address,
         t.school_company_name,
         t.school_company_phone,
         t.student_education,
         t.student_edu_start_date,
         t.student_grade,
         t.student_school_type,
         t.student_term_process,
         t.user_school_province,
         t.vocational_school_three,
         t.friend_mobile,
         t.friend2_mobile,
         t.friend3_mobile,
         t.friend_phone_call_result_status,
         t.friend_phone_call_result_status_des,
         t.parent_mobile,
         t.parent_mobile_in_the_contact,
         t.parent_name,
         t.parent_phone_call_result_status,
         t.parent_phone_call_result_status_des,
         t.tech_mobile,
         t.tech_phone_call_result_status,
         t.tech_phone_call_result_status_des,
         t.last_loan_amt,
         t.last_loan_time,
         t.last_mobile,
         t.latest_rtn_loan_date,
         t.loan_status_normal,
         t.loan_status_overdue,
         t.max_overdue_days,
         t.overdue_term,
         t.overdue_7days_4times,
         t.overdue_30days_1times,
         t.previous_is_repayed,
         t.reject_in_30days,
         t.rtn_term,
         t.bo_id,
         t.audit_amt,
         t.type,
         t.term,
         t.product_id,
         t.loan_amt,
         t.loan_apply_date,
         t.channel_code,
         t.is_jxhj,
         t.is_stock_campaign,
         t.is_new_user,
         t.is_retained_user,
         t.lbs_city,
         t.lbs_code_not_peer_num_top_three_3m,
         t.lbs_code_not_peer_num_top_three_6m,
         t.zhima_uuid,
         t.zhima_score,
         t.tongdun_uuid,
         t.hit_tongdun_repeate_loan_one_weekend,
         t.hit_tongdun_repeate_loan_one_month,
         t.hit_tongdun_repeate_loan_three_month,
         t.hit_tongdun_repeate_loan_six_month,
         t.tongdun_repeate_loan_one_weekend_div_one_month,
         t.id_hit_tongdun_court_black_list,
         t.id_hit_tongdun_court_execute_list,
         t.id_hit_tongdun_crime_black_list,
         t.id_hit_tongdun_legal_person_black_list,
         t.id_hit_tongdun_loan_black_list,
         t.id_hit_tongdun_lost_contact_list,
         t.id_name_hit_tongdun_fuzzy_court_black_list,
         t.id_name_hit_tongdun_fuzzy_court_execute_list,
         t.id_name_hit_tongdun_fuzzy_loan_black_list,
         t.mobile_hit_tongdun_legal_person_black_list,
         t.mobile_hit_tongdun_loan_black_intermediary,
         t.mobile_hit_tongdun_loan_black_list,
         t.mobile_hit_tongdun_lost_contact_list,
         t.contact_mobile_hit_tongdun_loan_black_intermediary,
         t.borrow_time_short_in_device,
         t.move_distance_exception_in_device,
         t.one_hour_many_account_in_device,
         t.one_hour_much_account_all,
         t.one_hour_much_account_in_device,
         t.one_day_many_account_in_device,
         t.one_day_much_account_all,
         t.one_day_much_account_in_device,
         t.seven_day_much_account_all,
         t.seven_day_much_account_in_device,
         t.tongdun_final_score,
         t.create_time,
         t.face_similar_percent,
         t.idcard_similar_percent,
         t.user_risk_bill,
         t.id_hit_our_black_list,
         t.immediate_family_mobile_hit_our_black_list,
         t.mobile_hit_our_black_list,
         t.score_level,
         t.score_result,
         t.is_need_telephone_audit,
         t.final_des,
         case
           when dd.ED_RULE_ID = '' then
            null
           else
            dd.ED_RULE_ID
         end ED_RULE_ID,
         case
           when dd.ED_REASON_ID = '' then
            null
           else
            dd.ED_REASON_ID
         end ED_REASON_ID,
         case
           when dd.RG_RULE_ID = '' then
            null
           else
            dd.RG_RULE_ID
         end RG_RULE_ID,
         case
           when dd.RG_REASON_ID = '' then
            null
           else
            dd.RG_REASON_ID
         end RG_REASON_ID,
         case
           when dd.PASS_RULE_ID = '' then
            null
           else
            dd.PASS_RULE_ID
         end PASS_RULE_ID,
         t.FINAL_DES_TIME,
         t.FINAL_DES_REMARK
      from (select bp_id,
                   user_id,
                   max(case when data_no = 'userName' then data_value end) USER_NAME,
                   max(case when data_no = 'realName' then data_value end) REAL_NAME,
                   max(case when data_no = 'queryName' then data_value end) QUERY_NAME,
                   max(case when data_no = 'userAge' then data_value end) USER_AGE,
                   max(case when data_no = 'userCensusAddress' then data_value end) USER_CENSUS_ADDRESS,
                   max(case when data_no = 'currentAddress' then data_value end) CURRENT_ADDRESS,
                   max(case when data_no = 'homeAddress' then data_value end) HOME_ADDRESS,
                   max(case when data_no = 'provinceCode' then data_value end) PROVINCE_CODE,
                   max(case when data_no = 'provinceName' then data_value end) PROVINCE_NAME,
                   max(case when data_no = 'email' then data_value end) EMAIL,
                   max(case when data_no = 'userGender' then data_value end) USER_GENDER,
                   max(case when data_no = 'userIdNumber' then data_value end) USER_ID_NUMBER,
                   max(case when data_no = 'userMobile' then data_value end) USER_MOBILE,
                   max(case when data_no = 'userKinMobile' then data_value end) USER_KIN_MOBILE,
                   max(case when data_no = 'schoolAcademy' then data_value end) SCHOOL_ACADEMY,
                   max(case when data_no = 'schoolCompanyAddress' then data_value end) SCHOOL_COMPANY_ADDRESS,
                   max(case when data_no = 'schoolCompanyName' then data_value end) SCHOOL_COMPANY_NAME,
                   max(case when data_no = 'schoolCompanyPhone' then data_value end) SCHOOL_COMPANY_PHONE,
                   max(case when data_no = 'studentEducation' then data_value end) STUDENT_EDUCATION,
                   max(case when data_no = 'studentEduStartDate' then data_value end) STUDENT_EDU_START_DATE,
                   max(case when data_no = 'studentGrade' then data_value end) STUDENT_GRADE,
                   max(case when data_no = 'studentSchoolType' then data_value end) STUDENT_SCHOOL_TYPE,
                   max(case when data_no = 'studentTermProcess' then data_value end) STUDENT_TERM_PROCESS,
                   max(case when data_no = 'userSchoolProvince' then data_value end) USER_SCHOOL_PROVINCE,
                   max(case when data_no = 'vocationalSchoolThree' then data_value end) VOCATIONAL_SCHOOL_THREE,
                   max(case when data_no = 'friendMobile' then data_value end) FRIEND_MOBILE,
                   max(case when data_no = 'friend2Mobile' then data_value end) FRIEND2_MOBILE,
                   max(case when data_no = 'friend3Mobile' then data_value end) FRIEND3_MOBILE,
                   max(case when data_no = 'friendPhoneCallResultStatus' then data_value end) FRIEND_PHONE_CALL_RESULT_STATUS,
                   max(case when data_no = 'friendPhoneCallResultStatusDes' then data_value end) FRIEND_PHONE_CALL_RESULT_STATUS_DES,
                   max(case when data_no = 'parentMobile' then data_value end) PARENT_MOBILE,
                   max(case when data_no = 'parentMobileInTheContact' then data_value end) PARENT_MOBILE_IN_THE_CONTACT,
                   max(case when data_no = 'parentName' then data_value end) PARENT_NAME,
                   max(case when data_no = 'parentPhoneCallResultStatus' then data_value end) PARENT_PHONE_CALL_RESULT_STATUS,
                   max(case when data_no = 'parentPhoneCallResultStatusDes' then data_value end) PARENT_PHONE_CALL_RESULT_STATUS_DES,
                   max(case when data_no = 'techMobile' then data_value end) TECH_MOBILE,
                   max(case when data_no = 'techPhoneCallResultStatus' then data_value end) TECH_PHONE_CALL_RESULT_STATUS,
                   max(case when data_no = 'techPhoneCallResultStatusDes' then data_value end) TECH_PHONE_CALL_RESULT_STATUS_DES,
                   max(case when data_no = 'lastLoanAmt' then data_value end) LAST_LOAN_AMT,
                   max(case when data_no = 'lastLoanTime' then data_value end) LAST_LOAN_TIME,
                   max(case when data_no = 'lastMobile' then data_value end) LAST_MOBILE,
                   max(case when data_no = 'latestRtnLoanDate' then data_value end) LATEST_RTN_LOAN_DATE,
                   max(case when data_no = 'loanStatusNormal' then data_value end) LOAN_STATUS_NORMAL,
                   max(case when data_no = 'loanStatusOverdue' then data_value end) LOAN_STATUS_OVERDUE,
                   max(case when data_no = 'maxOverDueDays' then data_value end) MAX_OVERDUE_DAYS,
                   max(case when data_no = 'overdueTerm' then data_value end) OVERDUE_TERM,
                   max(case when data_no = 'overDue7Days4Times' then data_value end) OVERDUE_7DAYS_4TIMES,
                   max(case when data_no = 'overDue30Days1Times' then data_value end) OVERDUE_30DAYS_1TIMES,
                   max(case when data_no = 'previousIsRepayed' then data_value end) PREVIOUS_IS_REPAYED,
                   max(case when data_no = 'rejectIn30Days' then data_value end) REJECT_IN_30DAYS,
                   max(case when data_no = 'rtnTerm' then data_value end) RTN_TERM,
                   max(case when data_no = 'boId' then data_value end) BO_ID,
                   max(case when data_no = 'auditAmt' then data_value end) AUDIT_AMT,
                   max(case when data_no = 'type' then data_value end) TYPE,
                   max(case when data_no = 'term' then data_value end) TERM,
                   max(case when data_no = 'productId' then data_value end) PRODUCT_ID,
                   max(case when data_no = 'loanAmt' then data_value end) LOAN_AMT,
                   max(case when data_no = 'loanApplyDate' then data_value end) LOAN_APPLY_DATE,
                   max(case when data_no = 'channelCode' then data_value end) CHANNEL_CODE,
                   max(case when data_no = 'isJxhj' then data_value end) IS_JXHJ,
                   max(case when data_no = 'isStockCampaign' then data_value end) IS_STOCK_CAMPAIGN,
                   max(case when data_no = 'isNewUser' then data_value end) IS_NEW_USER,
                   max(case when data_no = 'isRetainedUser' then data_value end) IS_RETAINED_USER,
                   max(case when data_no = 'lbsCity' then data_value end) LBS_CITY,
                   max(case when data_no = 'lbsCodeNotPeerNumTopThree3m' then data_value end) LBS_CODE_NOT_PEER_NUM_TOP_THREE_3M,
                   max(case when data_no = 'lbsCodeNotPeerNumTopThree6m' then data_value end) LBS_CODE_NOT_PEER_NUM_TOP_THREE_6M,
                   max(case when data_no = 'zhimaUuid' then data_value end) ZHIMA_UUID,
                   max(case when data_no = 'zhiMaScore' then data_value end) ZHIMA_SCORE,
                   max(case when data_no = 'tongdunUuid' then data_value end) TONGDUN_UUID,
                   max(case when data_no = 'hitTongDunRepeateLoanOneMonth' then data_value end) HIT_TONGDUN_REPEATE_LOAN_ONE_MONTH,
                   max(case when data_no = 'hitTongDunRepeateLoanOneWeekend' then data_value end) HIT_TONGDUN_REPEATE_LOAN_ONE_WEEKEND,
                   max(case when data_no = 'hitTongDunRepeateLoansixMonth' then data_value end) HIT_TONGDUN_REPEATE_LOAN_SIX_MONTH,
                   max(case when data_no = 'hitTongDunRepeateLoanThreeMonth' then data_value end) HIT_TONGDUN_REPEATE_LOAN_THREE_MONTH,
                   max(case when data_no = 'idHitTongDunCourtBlackList' then data_value end) ID_HIT_TONGDUN_COURT_BLACK_LIST,
                   max(case when data_no = 'idHitTongDunCourtExecuteList' then data_value end) ID_HIT_TONGDUN_COURT_EXECUTE_LIST,
                   max(case when data_no = 'idHitTongDunCrimeBlackList' then data_value end) ID_HIT_TONGDUN_CRIME_BLACK_LIST,
                   max(case when data_no = 'idHitTongDunLegalPersonBlackList' then data_value end) ID_HIT_TONGDUN_LEGAL_PERSON_BLACK_LIST,
                   max(case when data_no = 'idHitTongDunLoanBlackList' then data_value end) ID_HIT_TONGDUN_LOAN_BLACK_LIST,
                   max(case when data_no = 'idHitTongDunLostContactList' then data_value end) ID_HIT_TONGDUN_LOST_CONTACT_LIST,
                   max(case when data_no = 'idNameHitTongDunFuzzyCourtBlackList' then data_value end) ID_NAME_HIT_TONGDUN_FUZZY_COURT_BLACK_LIST,
                   max(case when data_no = 'idNameHitTongDunFuzzyCourtExecuteList' then data_value end) ID_NAME_HIT_TONGDUN_FUZZY_COURT_EXECUTE_LIST,
                   max(case when data_no = 'idNameHitTongDunFuzzyLoanBlackList' then data_value end) ID_NAME_HIT_TONGDUN_FUZZY_LOAN_BLACK_LIST,
                   max(case when data_no = 'mobileHitTongDunLegalPersonBlackList' then data_value end) MOBILE_HIT_TONGDUN_LEGAL_PERSON_BLACK_LIST,
                   max(case when data_no = 'mobileHitTongDunLoanBlackIntermediary' then data_value end) MOBILE_HIT_TONGDUN_LOAN_BLACK_INTERMEDIARY,
                   max(case when data_no = 'mobileHitTongDunLoanBlackList' then data_value end) MOBILE_HIT_TONGDUN_LOAN_BLACK_LIST,
                   max(case when data_no = 'mobileHitTongDunLostContactList' then data_value end) MOBILE_HIT_TONGDUN_LOST_CONTACT_LIST,
                   max(case when data_no = 'moveDistanceExceptionInDevice' then data_value end) MOVE_DISTANCE_EXCEPTION_IN_DEVICE,
                   max(case when data_no = 'oneDayManyAccountInDevice' then data_value end) ONE_DAY_MANY_ACCOUNT_IN_DEVICE,
                   max(case when data_no = 'oneDayMuchAccountAll' then data_value end) ONE_DAY_MUCH_ACCOUNT_ALL,
                   max(case when data_no = 'oneDayMuchAccountInDevice' then data_value end) ONE_DAY_MUCH_ACCOUNT_IN_DEVICE,
                   max(case when data_no = 'oneHourManyAccountInDevice' then data_value end) ONE_HOUR_MANY_ACCOUNT_IN_DEVICE,
                   max(case when data_no = 'oneHourMuchAccountAll' then data_value end) ONE_HOUR_MUCH_ACCOUNT_ALL,
                   max(case when data_no = 'oneHourMuchAccountInDevice' then data_value end) ONE_HOUR_MUCH_ACCOUNT_IN_DEVICE,
                   max(case when data_no = 'sevenDayMuchAccountAll' then data_value end) SEVEN_DAY_MUCH_ACCOUNT_ALL,
                   max(case when data_no = 'sevenDayMuchAccountInDevice' then data_value end) SEVEN_DAY_MUCH_ACCOUNT_IN_DEVICE,
                   max(case when data_no = 'tongdunFinalScore' then data_value end) TONGDUN_FINAL_SCORE,
                   max(case when data_no = 'tongDunRepeateLoanOneWeekendDivOneMonth' then data_value end) TONGDUN_REPEATE_LOAN_ONE_WEEKEND_DIV_ONE_MONTH,
                   max(case when data_no = 'borrowTimeShortInDevice' then data_value end) BORROW_TIME_SHORT_IN_DEVICE,
                   max(case when data_no = 'contactMobileHitTongDunLoanBlackIntermediary' then data_value end) CONTACT_MOBILE_HIT_TONGDUN_LOAN_BLACK_INTERMEDIARY,
                   max(case when data_no = 'createTime' then data_value end) CREATE_TIME,
                   max(case when data_no = 'faceSimilarPercent' then data_value end) FACE_SIMILAR_PERCENT,
                   max(case when data_no = 'idCardSimilarPercent' then data_value end) IDCARD_SIMILAR_PERCENT,
                   max(case when data_no = 'userRiskBill' then data_value end) USER_RISK_BILL,
                   max(case when data_no = 'idHitOurBlackList' then data_value end) ID_HIT_OUR_BLACK_LIST,
                   max(case when data_no = 'immediateFamilyMobileHitOurBlackList' then data_value end) IMMEDIATE_FAMILY_MOBILE_HIT_OUR_BLACK_LIST,
                   max(case when data_no = 'mobileHitOurBlackList' then data_value end) MOBILE_HIT_OUR_BLACK_LIST,
                   max(case when data_no = 'scoreLevel' then data_value end) SCORE_LEVEL,
                   max(case when data_no = 'scoreResult' then data_value end) SCORE_RESULT,
                   max(case when data_no = 'isNeedTelephoneAudit' then data_value end) IS_NEED_TELEPHONE_AUDIT,
                   max(case when data_no = 'finalDes' then data_value end) FINAL_DES,
                   max(case when data_no = 'finalDes' then create_time end) FINAL_DES_TIME,
                   max(case when data_no = 'finalDes' then remark end) FINAL_DES_REMARK
              from (select bp_id,
                           user_id,
                           data_no,
                           data_value,
                           create_time,
                           remark,
                           row_number() over(partition by bp_id, data_no order by id desc) rn
                      from ods.t_des_main_hist) s
             where s.rn = 1
             group by bp_id, user_id) t
      join ods.t_borrows_prepare_hist bp
        on t.bp_id = bp.id
      join idw.dim_asset_product p
        on bp.p_id = p.p_id
      left join (select bp_id,
                        concat_ws(',',
                                  collect_set(case
                                                when rule_result_code like 'ED%' or rule_result_code like 'TM%' then
                                                 rule_id
                                              end)) ED_RULE_ID,
                        concat_ws(',',
                                  collect_set(case
                                                when rule_result_code like 'ED%' or rule_result_code like 'TM%' then
                                                 rule_result_code
                                              end)) ED_REASON_ID,
                        concat_ws(',',
                                  collect_set(case
                                                when rule_result_code like 'RG%' or rule_result_code like 'NM%' then
                                                 rule_id
                                              end)) RG_RULE_ID,
                        concat_ws(',',
                                  collect_set(case
                                                when rule_result_code like 'RG%' or rule_result_code like 'NM%' then
                                                 rule_result_code
                                              end)) RG_REASON_ID,
                        concat_ws(',',
                                  collect_set(case
                                                when rule_result_status = 6 and rule_type = 2 then
                                                 rule_id
                                              end)) PASS_RULE_ID
                   from ods.t_des_dcin_hist
                  group by bp_id) dd
        on t.bp_id = dd.bp_id;