CREATE TABLE IDW.FACT_MLD_ORDER_CREDIT (
  `ORDER_ID` INT COMMENT '订单ID', 
  `ORDER_NO` STRING COMMENT '订单号', 
  `NONO_BOID` STRING COMMENT 'NONO申请号', 
  `USER_ID` INT COMMENT '用户ID',
  `NONO_USERID` INT COMMENT 'NONO用户ID',
  `ORDER_CREATE_DATE` STRING COMMENT '订单创建时间',
  `ORDER_STATUS` INT    COMMENT '订单状态',
  `APPLY_STAUS` INT   COMMENT '发标状态',
  `PRODUCT_ID` INT COMMENT '产品ID',
  `NONO_PRODUCT_ID`  INT COMMENT 'NONO产品ID', 
  `HOR_TYPE_ID`  INT COMMENT '征信类型ID', 
  `HOR_TYPE_NAME`  STRING COMMENT '征信类型', 
  `DH_UUID` STRING COMMENT 'DATA_HEAD.UUID'
  ,DW_CREATE_BY          STRING    COMMENT '系统字段-创建者'
  ,DW_CREATE_TIME        STRING    COMMENT '系统字段-创建时间'
  ,DW_UPDATE_BY          STRING    COMMENT '系统字段-修改者'
  ,DW_UPDATE_TIME        STRING    COMMENT '系统字段-修改时间')
COMMENT 'MLD订单征信'
STORED AS PARQUET 
TBLPROPERTIES ('parquet.compression'='SNAPPY');
