drop table if exists idw.FACT_BORROWS_AUDIT;
create table if not exists idw.FACT_BORROWS_AUDIT
(
   DW_CREATE_BY         string comment '系统字段-创建者',
   DW_CREATE_TIME       string comment '系统字段-创建时间',
   DW_UPDATE_BY         string comment '系统字段-修改者',
   DW_UPDATE_TIME       string comment '系统字段-修改时间',
   BO_ID                bigint comment '借款ID',
   USER_ID              bigint comment '用户ID',
   P_ID                 bigint comment '产品ID',
   CATEGORY_NAME_01     string comment '产品分类01',
   BIZ_CODE_01          string comment '业务线编码01',
   BIZ_NAME_01          string comment '业务线名称01',
   DEPOSITORY_FLAG      int comment '存管标记 0:初始 1:走存管 2:不走存管',
   ML_TIME              string comment '进件时间',
   AUDIT_REJECT_TIME    string comment '初审拒绝时间',
   CONFIRM_REJECT_TIME  string comment '终审拒绝时间',
   AUDIT_CANCEL_TIME    string comment '初审取消时间',
   CONFIRM_CANCEL_TIME  string comment '终审取消时间',
   FIRST_AUDIT_TIME     string comment '首次初审时间',
   LAST_AUDIT_PASS_TIME string comment '最近初审通过时间',
   LAST_CONFIRM_TIME    string comment '最近终审时间',
   CONFIRM_PASS_TIME    string comment '终审通过时间',
   IS_AUDIT             int comment '初审状态',
   IS_CONFIRM           int comment '终审状态',
   AUDIT_STATUS         string comment '审核状态',
   TONGDUN_UUID         string comment '同盾征信UUID',
   NFCS_UUID            string comment '上海咨询信用UUID',
   ZHIMA_IVS_UUID       string comment '芝麻反欺诈UUID',
   ZHIMA_FOCUS_UUID     string comment '芝麻行业关注UUID',
   ZZC_APPLICATIONS_UUID string comment '中智诚反欺诈UUID',
   ZZC_BLACKLIST_UUID   string comment '中智诚黑名单UUID',
   BAIQISHI_IVS_RISK_USER_UUID string comment '白骑士反欺诈风险用户UUID',
   FUSHU_FUND_RAWDATA_UUID string comment '富数公积金UUID',
   EDUCATION_UUID       string comment '鹏元学历UUID',
   EMAY_BLACKLIST_UUID  string comment '亿美黑名单UUID',
   BD_RISK_LIST_UUID    string comment '百度金融风险名单UUID',
   BR_CREDIT_REPORT_UUID string comment '百融信用报告UUID',
   MOXIE_REPORT_DATA_BANKHONOR_UUID string comment '魔蝎人行征信报告UUID',
   MOXIE_REPORT_DATA_JINGDONG_UUID string comment '魔蝎京东报告UUID',
   GXB_ECOMMERCE_UUID   string comment '公信宝支付宝淘宝报告UUID',
   MOXIE_REPORT_DATA_CARRIER_UUID string comment '魔蝎运营商数据报告UUID',
   MOXIE_BASIC_DATA_CARRIER_UUID string comment '魔蝎运营商数据聚合UUID',
   REJECT_REASON        string comment '拒绝原因',
   BANK_HONOR_UPLOAD_TIME string comment '人行报告上传时间',
   BACKGROUND_SURVEY_TIME string comment '背调时间',
   VISIT_RSLT           string comment '外访结果',
   VISIT_TIME           string comment '外访时间',
   PASS_TIME            string comment '审核通过时间',
   VIDEO_AUDIT_TIME     string comment '视频提交时间',
   ML_PRICE             decimal(38,10) comment '进件金额',
   CONFIRM_PASS_PRICE   decimal(38,10) comment '审批金额')
COMMENT '借款审核事实表'
ROW FORMAT DELIMITED
  NULL DEFINED AS ''
STORED AS PARQUET 
TBLPROPERTIES ("parquet.compression"="SNAPPY");
