DROP TABLE IF EXISTS IDW.FACT_NONO_AUM_SNAPSHOT;
CREATE TABLE IF NOT EXISTS IDW.FACT_NONO_AUM_SNAPSHOT
(
   USER_ID              bigint comment '用户ID',
   INVEST_AMT           decimal(38,10) comment '原始投资金额',
   AUM                  decimal(38,10) comment 'AUM',
   MAX_AUM              decimal(38,10) comment '历史最高AUM',
   MAX_AUM_DATE         string comment '最高AUM出现日期',
   ZZ_INVEST_AMT        decimal(38,10) comment '债转原始投资金额',
   ZZ_AUM               decimal(38,10) comment '债转在投金额',
   ZZ_MAX_AUM           decimal(38,10) comment '债转历史最高金额',
   ZZ_MAX_AUM_DATE      string comment '债转历史最高出现日期',
   ST_INVEST_AMT        decimal(38,10) comment '散投原始投资金额',
   ST_AUM               decimal(38,10) comment '散投在投金额',
   ST_MAX_AUM           decimal(38,10) comment '散投历史最高金额',
   ST_MAX_AUM_DATE      string comment '散投历史最高出现日期',
   JX_INVEST_AMT        decimal(38,10) comment '精选计划原始投资金额',
   JX_AUM               decimal(38,10) comment '精选计划在投金额',
   JX_MAX_AUM           decimal(38,10) comment '精选计划历史最高金额',
   JX_MAX_AUM_DATE      string comment '精选计划历史最高出现日期',
   XK_INVEST_AMT        decimal(38,10) comment '新客专项计划原始投资金额',
   XK_AUM               decimal(38,10) comment '新客专项计划在投金额',
   XK_MAX_AUM           decimal(38,10) comment '新客专项计划历史最高金额',
   XK_MAX_AUM_DATE      string comment '新客专项计划历史最高出现日期',
   JGJX_INVEST_AMT      decimal(38,10) comment '机构精选计划原始投资金额',
   JGJX_AUM             decimal(38,10) comment '机构精选计划在投金额',
   JGJX_MAX_AUM         decimal(38,10) comment '机构精选计划历史最高金额',
   JGJX_MAX_AUM_DATE    string comment '机构精选计划历史最高出现日期',
   TX_INVEST_AMT        decimal(38,10) comment '贴心计划原始投资金额',
   TX_AUM               decimal(38,10) comment '贴心计划在投金额',
   TX_MAX_AUM           decimal(38,10) comment '贴心计划历史最高金额',
   TX_MAX_AUM_DATE      string comment '贴心计划历史最高出现日期',
   LR_INVEST_AMT        decimal(38,10) comment '懒人计划原始投资金额',
   LR_AUM               decimal(38,10) comment '懒人计划在投金额',
   LR_MAX_AUM           decimal(38,10) comment '懒人计划历史最高金额',
   LR_MAX_AUM_DATE      string comment '懒人计划历史最高出现日期',
   ZY_INVEST_AMT        decimal(38,10) comment '0元计划原始投资金额',
   ZY_AUM               decimal(38,10) comment '0元计划在投金额',
   ZY_MAX_AUM           decimal(38,10) comment '0元计划历史最高金额',
   ZY_MAX_AUM_DATE      string comment '0元计划历史最高出现日期',
   YYS_INVEST_AMT       decimal(38,10) comment '月月升计划原始投资金额',
   YYS_AUM              decimal(38,10) comment '月月升计划在投金额',
   YYS_MAX_AUM          decimal(38,10) comment '月月升计划历史最高金额',
   YYS_MAX_AUM_DATE     string comment '月月升计划历史最高出现日期',
   OTHER_INVEST_AMT     decimal(38,10) comment '其他原始投资金额',
   OTHER_AUM            decimal(38,10) comment '其他在投金额',
   DW_CREATE_BY         string comment '系统字段-创建者',
   DW_CREATE_TIME       string comment '系统字段-创建时间',
   DW_UPDATE_BY         string comment '系统字段-修改者',
   DW_UPDATE_TIME       string comment '系统字段-修改时间',
   IN_INVEST_AMT        decimal(38,10) comment '在投金额',
   MAX_IN_INVEST_AMT    decimal(38,10) comment '历史最高在投金额',
   MAX_IN_INVEST_AMT_DATE string comment '最高在投金额出现日期')
COMMENT '诺诺AUM快照表'
PARTITIONED BY (STAT_DATE STRING COMMENT '统计日期 年-月-日')
ROW FORMAT DELIMITED
  NULL DEFINED AS ''
STORED AS PARQUET 
TBLPROPERTIES ("parquet.compression"="SNAPPY");
