drop table if exists idw.fact_user_info;
create table if not exists idw.fact_user_info
(
   DW_CREATE_BY         string comment '系统字段-创建者',
   DW_CREATE_TIME       string comment '系统字段-创建时间',
   DW_UPDATE_BY         string comment '系统字段-修改者',
   DW_UPDATE_TIME       string comment '系统字段-修改时间',
   USER_ID              bigint comment '用户ID',
   USER_NAME            string comment '用户名',
   REAL_NAME            string comment '姓名',
   GENDER               int comment '性别 1:男 2:女',
   MOBILE_NUM           string comment '手机号',
   EMAIL                string comment '电子邮箱',
   IS_EMAIL             int comment '是否邮件认证 0:否 1:是',
   REGISTER_TIME        string comment '注册时间',
   IS_AUTHENTICATION    int comment '是否身份认证 0:否 1:是',
   IS_PHOTO             int comment '是否图像认证 0:否 1:是',
   IS_EDUCATION_AUTH    int comment '是否学历认证 0:否 1:是 2:拒绝',
   IS_STUDENT_AUTH      int comment '是否学籍认证 0:否 1:是',
   IS_SPECIAL           int comment '是否特殊用户 0:否 1:是',
   IS_CHEAT             int comment '是否欺诈 0:否 1:是',
   STATUS               int comment '状态 0:无效用户 1:有效用户 2:锁定用户',
   STATUS_DESC          string comment '状态描述 0:无效用户 1:有效用户 2:锁定用户',
   PC_ID                bigint comment '所属公司ID',
   PC_ID_DESC           string comment '所属公司名称',
   RECOMMENDER          string comment '推荐人',
   USER_TYPE            int comment '用户类型 0:未知 1:理财 2:贷款 3:白领 4:微企业主 5:学生 6:企业主 7:vip企业主 8:企业',
   ID_NUM               string comment '身份证号',
   COU_ADDRESS          string comment '身份证归属地',
   FINANCE_ADVISOR      bigint comment '理财顾问',
   BIRTHDAY             string comment '生日',
   MOBILE_ADDRESS       string comment '手机归属市',
   MOBILE_ADDRESS_PROVINCE string comment '手机归属省',
   REGISTER_BIZ         string comment '注册业务线',
   ENGLISH_NAME         string comment '英文名',
   AGE                  int comment '年龄',
   CONSTELLATION        string comment '星座',
   QQ                   string comment 'QQ号码',
   CURRENT_MOBILE_NO    string comment '当前手机号',
   HJ_PROVINCE          string comment '户籍省',
   HJ_PROVINCE_NAME     string comment '户籍省名称',
   HJ_CITY              string comment '户籍市',
   HJ_CITY_NAME         string comment '户籍市名称',
   HJ_ADDRESS           string comment '户籍地址',
   CURRENT_PROVINCE     string comment '当前所在省',
   CURRENT_PROVINCE_NAME string comment '当前所在省名称',
   CURRENT_CITY         string comment '当前所在市',
   CURRENT_CITY_NAME    string comment '当前所在市名称',
   BIRTH_PROVINCE       string comment '出生省份',
   BIRTH_PROVINCE_NAME  string comment '出生省份名称',
   CONTACT_ADDRESS      string comment '联系地址',
   MARRIAGE_STATUS      int comment '婚姻状况 0:未知 1:已婚 2:未婚 3:已婚已育 4:已婚未育 5:未婚已育 6:丧偶 7:离婚',
   MARRIAGE_STATUS_DESC string comment '婚姻状态描述',
   IS_HAVE_PASSPORT     int comment '是否持有护照 0:未知 1:有 2:无',
   IS_SOCIAL_SECURITY   int comment '是否有社保 0:未知 1:有 2:无',
   IS_DRIVING_LICENSE   int comment '是否有驾照 0:未知 1:有 2:无',
   HOUSE_STATUS         int comment '现居住地状况 0:未知 1:自购房(无房贷) 2:自购房(有按揭) 3:自建房 4:亲属房产 5:租房 6:其他',
   EDUCATION            string comment '学历',
   CHANNEL_ID           bigint comment '注册渠道ID',
   CHANNEL_NAME         string comment '注册渠道名称',
   AD_PLAN              string comment '广告计划',
   AD_UNIT              string comment '广告单元',
   CHANNEL_DETAIL       string comment '渠道明细',
   UNIFI_REGISTER_COUNTRY_CODE int comment 'unifi注册所在国编码',
   UNIFI_REGISTER_COUNTRY_NAME string comment 'unifi注册所在国名称',
   REGISTER_TERMINAL    string comment '注册终端',
   REGISTER_IP          string comment '注册ip地址',
   USER_RANK            string comment '会员等级 0:普通会员 1:VIP1 2:VIP2 3:VIP3',
   USER_RANK_DESC       string comment '会员等级描述',
   EDU_START_DATE       string comment '入学时间',
   EDU_GRADUATE_DATE    string comment '毕业时间',
   MXD_EDUCATION        string comment '按照名校贷业务要求清洗后的学历，来源于db_nono.user_student_info',
   ACADEMY              string comment '就读院校',
   MAJOR                string comment '专业',
   IS_GRADUATE          int comment '是否已毕业 0:未毕业 1:已毕业',
   CAMPUS_APPROACH      int comment '用户来源',
   CAMPUS_APPROACH_DESC string comment '用户来源描述',
   STUDENT_NO           string comment '学号',
   CAMPUS               string comment '校区',
   FAMILY_INCOME        int comment '家庭收入 0:未设置 1:5万以下 2:5-10万 3:10-20万 4:20万以上',
   FAMILY_INCOME_DESC   string comment '家庭收入描述',
   SCHOOL_TYPE          string comment '学校类别',
   SCHOOL_TYPE_DESC     string comment '学校类别描述',
   SCHOOL_PROVINCE_ID   bigint comment '学校省份ID',
   SCHOOL_PROVINCE_NAME string comment '学校省份名称',
   SCHOOL_CITY_ID       bigint comment '学校城市ID',
   SCHOOL_CITY_NAME     string comment '学校城市名称',
   ADDRESS_HOME         string comment '家庭住址',
   INSTRUCTOR_NAME      string comment '辅导员姓名',
   INSTRUCTOR_MOBILE    string comment '辅导员手机',
   INSTRUCTOR_MOBILE_STATE string comment '辅导员手机状态',
   INSTRUCTOR_MOBILE_ADDRESS string comment '辅导员手机归属地',
   PARENT_NAME          string comment '父母姓名',
   PARENT_MOBILE        string comment '父母手机',
   PARENT_MOBILE_STATE  string comment '父母手机状态',
   PARENT_MOBILE_ADDRESS string comment '父母手机归属地',
   FRIEND1_NAME         string comment '好友1姓名',
   FRIEND1_MOBILE       string comment '好友1手机',
   FRIEND1_MOBILE_STATE string comment '好友1手机状态',
   FRIEND1_MOBILE_ADDRESS string comment '好友1手机归属地',
   FRIEND2_NAME         string comment '好友2姓名',
   FRIEND2_MOBILE       string comment '好友2手机',
   FRIEND2_MOBILE_STATE string comment '好友2手机状态',
   FRIEND2_MOBILE_ADDRESS string comment '好友2手机归属地',
   FRIEND3_NAME         string comment '好友3姓名',
   FRIEND3_MOBILE       string comment '好友3手机',
   FRIEND3_MOBILE_STATE string comment '好友3手机状态',
   FRIEND3_MOBILE_ADDRESS string comment '好友3手机归属地',
   JOB                  string comment '职业',
   CURRENT_JOB_TIME     string comment '工作年限',
   TOTAL_JOB_TIME       string comment '总工作年限',
   COMPANY_NAME         string comment '公司名称',
   COMPANY_TYPE         string comment '公司类型',
   COMPANY_BUSINESS_TYPE int comment '工作单位性质',
   COMPANY_TEL          string comment '公司电话号码',
   IS_DFD_ADMIN_MEMBER  int comment '是否大房东协议用户',
   KNOW_APPROACH_CODE   string comment '客户获知渠道编码',
   KNOW_APPROACH_NAME   string comment '客户获知渠道名称',
   COMPANY_BUSINESS_SORT string comment '企业类别',
   COMPANY_ADDRESS      string comment '单位地址',
   SPOUSE_NAME          string comment '配偶名字',
   SPOUSE_IDNUM         string comment '配偶身份证号',
   SPOUSE_MOBILE        string comment '配偶手机号',
   SPOUSE_COMPANY       string comment '配偶公司',
   MONTHLY_SALARY       string comment '月薪',
   IS_DEPOSIT int comment '是否通过存管认证：0:否，1:是',
   BIRTHDAY_AGE int comment '年龄-从身份证取生日，再除以365')
COMMENT '用户信息表'
ROW FORMAT DELIMITED
  NULL DEFINED AS ''
STORED AS PARQUET 
TBLPROPERTIES ("parquet.compression"="SNAPPY");