drop table if exists idw.FACT_IN_REPAY_BORROWS_SNAPSHOT_H6;
create table if not exists idw.FACT_IN_REPAY_BORROWS_SNAPSHOT_H6
(
   BO_ID                bigint comment '借款ID',
   P_ID                 bigint comment '产品ID',
   BUSI_LINE            string comment '所属业务线',
   USER_ID              bigint comment '用户ID',
   BO_RATE              decimal(38,10) comment '借款年利率',
   INTEREST_RATE_CUT    decimal(38,10) comment '减息',
   BO_AUDIT_TIME        string comment '审核时间',
   BO_AGREE_TIME        string comment '协议生成时间',
   SHOULD_REPAY_CNT     int comment '应还期数',
   REPAYED_CNT          int comment '已还期数',
   UNREPAY_CNT          int comment '未还期数',
   REPAYED_CNT_THIS_MONTH int comment '本月已还期数',
   SHOULD_REPAY_PRICE   decimal(38,10) comment '应还金额',
   REPAYED_PRICE        decimal(38,10) comment '已还金额',
   UNREPAY_PRICE        decimal(38,10) comment '未还金额',
   REPAYED_PRICE_THIS_MONTH decimal(38,10) comment '本月已还金额',
   SHOULD_REPAY_PRICE_B decimal(38,10) comment '应还本金',
   REPAYED_PRICE_B      decimal(38,10) comment '已还本金',
   UNREPAY_PRICE_B      decimal(38,10) comment '未还本金',
   REPAYED_PRICE_B_THIS_MONTH decimal(38,10) comment '本月已还本金',
   SHOULD_REPAY_PRICE_L decimal(38,10) comment '应还利息',
   REPAYED_PRICE_L      decimal(38,10) comment '已还利息',
   UNREPAY_PRICE_L      decimal(38,10) comment '未还利息',
   REPAYED_PRICE_L_THIS_MONTH decimal(38,10) comment '本月已还利息',
   SHOULD_REPAY_PRICE_PUNISH decimal(38,10) comment '应还罚息',
   REPAYED_PRICE_PUNISH decimal(38,10) comment '已还罚息',
   UNREPAY_PRICE_PUNISH decimal(38,10) comment '未还罚息',
   REPAYED_PRICE_PUNISH_THIS_MONTH decimal(38,10) comment '本月已还罚息',
   SHOULD_REPAY_SERVICE_FEE decimal(38,10) comment '应还服务费',
   REPAYED_SERVICE_FEE  decimal(38,10) comment '已还服务费',
   UNREPAY_SERVICE_FEE  decimal(38,10) comment '未还服务费',
   REPAYED_SERVICE_FEE_THIS_MONTH decimal(38,10) comment '本月已还服务费',
   REPAY_BEGIN_DAY      string comment '起始还款日',
   LAST_REPAYED_TIME    string comment '最近还款时间',
   IS_FIRST_REPAY_OVERDUE int comment '是否首还逾期',
   FIRST_REPAY_OVERDUE_DAYS int comment '首还逾期天数',
   IS_OVERDUE           int comment '是否有过逾期',
   MAX_OVERDUE_DAYS     int comment '最大逾期天数',
   IS_OVERDUE_UNREPAY   int comment '是否逾期未还',
   IS_DUNNING           int comment '是否在催收',
   DUN_TYPE             int comment '催收类型 0:委外 1:内催',
   DUN_COMPANY          bigint comment '催收服务商',
   DUN_COMPANY_NAME     string comment '催收服务商名称',
   DUN_START_TIME       string comment '催收开始时间',
   DUN_END_TIME         string comment '催收结束时间',
   OVERDUE_EXPECT_CNT   int comment '当前逾期期数',
   OVERDUE_REPAYED_PRICE decimal(38,10) comment '逾期已还金额',
   OVERDUE_UNREPAY_EXPECT_CNT int comment '当前逾期未还期数',
   OVERDUE_UNREPAY_DAYS int comment '当前逾期未还天数',
   AGING                string comment '账龄',
   OVERDUE_UNREPAY_PRICE decimal(38,10) comment '逾期未还金额',
   OVERDUE_UNREPAY_PRICE_B decimal(38,10) comment '逾期未还本金',
   OVERDUE_UNREPAY_PRICE_L decimal(38,10) comment '逾期未还利息',
   OVERDUE_UNREPAY_PRICE_PUNISH decimal(38,10) comment '逾期未还罚息',
   OVERDUE_UNREPAY_SERVICE_FEE decimal(38,10) comment '逾期未还服务费',
   DW_CREATE_BY         string comment '系统字段-创建者',
   DW_CREATE_TIME       string comment '系统字段-创建时间',
   DW_UPDATE_BY         string comment '系统字段-修改者',
   DW_UPDATE_TIME       string comment '系统字段-修改时间',
   REPAY_END_DAY        string comment '最终还款日',
   BO_FINISH_PRICE      decimal(38,10) comment '完成金额',
   BO_EXPECT            int comment '借款期限',
   BO_EXPECT_CAT        int comment '借款期限单位',
   CUR_PRICE            decimal(38,10) comment '当期应还金额',
   CUR_PRICE_B          decimal(38,10) comment '当期应还本金',
   CUR_PRICE_L          decimal(38,10) comment '当期应还利息',
   CUR_SERVICE_FEE      decimal(38,10) comment '当期应还平台服务费',
   FIRST_REPAY_TIME     string comment '首次还款时间',
   SHOULD_RETURN_PRICE  decimal(38,10) comment '应返还金额',
   RETURNED_PRICE       decimal(38,10) comment '已返还金额',
   UNRETURNED_PRICE     decimal(38,10) comment '未返还金额',
   RETURNED_PRICE_THIS_MONTH decimal(38,10) comment '本月已返还金额',
   OVERDUE_RETURNED_PRICE decimal(38,10) comment '逾期已返还金额',
   OVERDUE_UNRETURNED_PRICE decimal(38,10) comment '逾期未返还金额',
   OVERDUE_UNREPAY_EARLIEST_BR_TIME string comment '逾期未还最早还应还时间',
   CATEGORY_NAME_01     string comment '产品分类01',
   BIZ_CODE_01          string comment '业务线编码01',
   BIZ_NAME_01          string comment '业务线名称01',
   DEPOSITORY_FLAG      int comment '存管标记 0:初始 1:走存管 2:不走存管',
   FIRST_OVERDUE_EXPECT_NUM int comment '首次逾期期数',
   FIRST_OVERDUE_BR_TIME string comment '首次逾期应还时间',
   TRANSFER_ACCOUNT_TIME string comment '实际划转成功时间',
   P_NAME               string comment '产品名称',
   MONTHLY_REPAYMENT_AMT decimal(38,10) comment '月还款金额',
   SETTLEMENT_SHOULD_REPAY_AMT decimal(38,10) comment '提前结清需还金额',
   POSTED_BILL_NUM      int comment '已出账单期数')
COMMENT '在还借款快照 基于6点BR表统计'
PARTITIONED BY (STAT_DATE STRING COMMENT '统计日期 年-月-日')
ROW FORMAT DELIMITED
  NULL DEFINED AS ''
STORED AS PARQUET 
TBLPROPERTIES ("parquet.compression"="SNAPPY");