drop table if exists idw.FACT_BORROWS_PREPARE;
CREATE TABLE IF NOT EXISTS IDW.FACT_BORROWS_PREPARE
(
   BP_ID                bigint comment '预发标ID',
   USER_ID              bigint comment '用户ID',
   ML_ID                bigint comment '进件ID',
   P_ID                 bigint comment '借款产品ID',
   BUSI_LINE            string comment '所属业务线',
   BP_AIM               string comment '借款目的',
   BP_TITLE             string comment '借款标题',
   BP_PRICE             decimal(38,10) comment '借款金额',
   BP_EXPECT            int comment '借款期限',
   BP_EXPECT_CAT        int comment '借款期限单位 1:天 2:月 3:年',
   BP_RATE              decimal(38,10) comment '借款年利率',
   BP_BIDDING_TYPE      int comment '标类型 0：v3即协议用户 1：促销标 2：vip用户',
   BP_PROMOTION_TIME    string comment '促销时间',
   BP_REPAYSRC          string comment '还款来源',
   BP_PLEDGE            int comment '是否抵押',
   BP_HOUSE             string comment '房产信息',
   BP_PLEDGE_TYPE       int comment '抵押类型  1:借出者 2:但保者',
   FLAG_BORROWS         int comment '借款模式  0:竞标 1:亲友',
   IS_ASSURANCE         int comment '是否请求担保',
   IS_PART              int comment '是否接受部分借款',
   PART_PRICE           int comment '部分借款最低接受金额',
   BP_TIME              string comment '预发标时间',
   BP_PAYTYPE           string comment '还款方式',
   BP_BEN_PAYTYPE       string comment '本金还款方式',
   BP_XI_PAYTYPE        string comment '利息还款方式',
   BP_ACCTYPE           string comment '收款方式',
   BP_BEN_ACCTYPE       string comment '本金收款方式',
   BP_XI_ACCTYPE        string comment '利息收款方式',
   BP_IS_STATE          int comment '借款状态 0:草稿 1:发布',
   BP_HURRY             int comment '是否加急终审取现',
   BP_IS_INDEX          int comment '是否推荐 1:初始状态 2:正在出售中 3:下架 4:等待上架 5:已打包',
   BP_PUBLISH_TIME      string comment '发布时间',
   BP_LAST_MODIFED_TIME string comment '修改时间',
   BP_UPLOADS_FINISH    int comment '用户是否上传完成',
   BP_PRE_APPROVAL_AM_ID bigint comment '前置审批人员',
   BP_PRE_APPROVAL_STATUS int comment '前置审批状态 0:未提交 1:已通过 2:拒绝 3:已提交 4:已回退 5:自己撤回',
   BP_PRE_APPROVAL_TIME string comment '前置审批时间',
   BP_PRE_APPROVAL_OP_ID int comment '前置审批操作人员',
   BP_PRE_APPROVAL_REMARK string comment '前置审批备注',
   BP_PRE_APPROVAL_ASSIGN_TIME string comment '前置审批分配时间',
   BP_VISIT_AM_ID       bigint comment '外访人员',
   BP_VISIT_AM_ID_BK    bigint comment '随访人员',
   BP_VISIT_STATUS      int comment '外访状态',
   BP_VISIT_TIME        string comment '外访时间',
   BP_VISIT_OP_ID       bigint comment '外访操作人员',
   BP_VISIT_REMARK      string comment '外访备注',
   BP_VISIT_ASSIGN_TIME string comment '外访分配时间',
   BP_LACKED_UPLOADS    string comment '缺少的资料列表',
   BP_APPROVAL_AM_ID    bigint comment '审批人员',
   BP_APPROVAL_STATUS   int comment '审批状态',
   BP_APPROVAL_TIME     string comment '审批时间',
   BP_APPROVAL_REMARK   string comment '审批备注',
   BP_APPROVAL_OP_ID    bigint comment '审批操作人员',
   BP_APPROVAL_ASSIGN_TIME string comment '审批分配时间',
   BP_APPROVAL_SIGN_REMARK string comment '审核面签要求',
   BP_APPROVAL_LOAN_REMARK string comment '审核放款要求',
   BP_IS_SUCCESS        int comment '是否确认通过 0:表示待确认 1:表示用户确认 2:表示用户拒绝 3:表示超时确认',
   BP_SEND_SMS_TIME     string comment '确认消息发送时间',
   BP_PRICE_AUDIT       decimal(38,10) comment '审批金额',
   BP_EXPECT_AUDIT      int comment '审批期限',
   BP_RATE_AUDIT        decimal(38,10) comment '审批利率',
   BP_REVIEW_AM_ID      bigint comment '复审人员',
   BP_REVIEW_STATUS     int comment '复审状态',
   BP_REVIEW_TIME       string comment '复审时间',
   BP_REVIEW_REMARK     string comment '复审备注',
   BP_REVIEW_OP_ID      bigint comment '复审操作人员',
   BP_REVIEW_SIGN_REMARK string comment '复审签约备注',
   BP_REVIEW_LOAN_REMARK string comment '复审放款备注',
   BP_REVIEW_PS_REMARK  string comment '复审补充备注',
   BP_REVIEW_ASSIGN_TIME string comment '复审分配时间',
   BP_PROTOCOL_TEMPLATE int comment '借款担保协议模板',
   IS_ILLEGAL           int comment '违例',
   BP_ILLEGAL_REMARK    string comment '违例备注',
   BP_RESOURCE          string comment '据件/回退原因',
   BP_NEED_HTSB         int comment '是否需要附加做活体识别',
   BP_NEED_JXL          int comment '是否需要附加做聚信立',
   BP_RATE_LENDER       decimal(38,10) comment '借出者利率',
   BP_REPEAT_RESULT     string comment '重复性检查',
   BP_CHANNEL           int comment '申请渠道 0:APP 1:PC',
   CREATOR              bigint comment '创建人',
   UPDATOR              bigint comment '更新人',
   CREATE_TIME          string comment '创建时间',
   UPDATE_TIME          string comment '更新时间',
   DW_CREATE_BY         string comment '系统字段-创建者',
   DW_CREATE_TIME       string comment '系统字段-创建时间',
   DW_UPDATE_BY         string comment '系统字段-修改者',
   DW_UPDATE_TIME       string comment '系统字段-修改时间',
   P_KEY                int comment '产品代理键')
    COMMENT '预发标'
    ROW FORMAT DELIMITED
      NULL DEFINED AS ''
    STORED AS PARQUET TBLPROPERTIES ("parquet.compression"="SNAPPY");