drop table if exists idw.FACT_RM_USER_CREDIT;
create table if not exists idw.FACT_RM_USER_CREDIT
(
   DW_CREATE_BY         string comment '系统字段-创建者',
   DW_CREATE_TIME       string comment '系统字段-创建时间',
   DW_UPDATE_BY         string comment '系统字段-修改者',
   DW_UPDATE_TIME       string comment '系统字段-修改时间',
   AUTH_ID              string comment '授信ID',
   USER_ID              bigint comment '用户ID',
   USER_ID_NUMBER       string comment '用户身份证号',
   REAL_NAME            string comment '用户真实姓名',
   USER_MOBILE          string comment '用户手机号',
   USER_AGE             int comment '年龄',
   USER_GENDER          int comment '性别 1:男 2:女',
   ID_HIT_OUR_BLACK_LIST int comment '身份证号是否命中内部黑名单',
   MOBILE_HIT_OUR_BLACK_LIST int comment '手机号是否命中内部黑名单',
   ZHIMA_SCORE_UUID     string comment '芝麻分UUID',
   ZHIMA_SCORE          int comment '芝麻分',
   HDYM_BLACK_UUID      string comment '华道亿美黑名单UUID',
   EMAY_IS_BLACK        int comment '华道亿美黑名单',
   ZZC_BLACK_UUID       string comment '中智诚黑名单UUID',
   HIT_ZZC_BLACK_LIST_CNT int comment '中智诚黑名单数量',
   HIT_ZZC_TENANT_CNT   int comment '中智诚黑名单跨机构数',
   BDJR_RISK_UUID       string comment '百度金融风险名单UUID',
   BDJR_BLACK_LEVEL     string comment '百度风险等级',
   BDJR_BLACK_REASON    string comment '百度加黑原因',
   TONGDUN_UUID         string comment '同盾采集UUID',
   MOBILE_HIT_TONGDUN_LOST_CONTACT_LIST int comment '手机号命中失联名单',
   ID_NAME_HIT_TONGDUN_FUZZY_LOAN_BLACK_LIST int comment '身份证_姓名命中网贷模糊黑名单',
   ID_NAME_HIT_TONGDUN_FUZZY_COURT_BLACK_LIST int comment '身份证_姓名命中法院失信模糊名单',
   ID_NAME_HIT_TONGDUN_FUZZY_COURT_EXECUTE_LIST int comment '身份证_姓名命中法院执行模糊名单',
   ID_HIT_TONGDUN_LOAN_BLACK_LIST int comment '身份证命中网贷黑名单',
   MOBILE_HIT_TONGDUN_LOAN_BLACK_LIST int comment '手机号命中网贷黑名单',
   ID_HIT_TONGDUN_COURT_BLACK_LIST int comment '身份证命中法院失信名单',
   ID_HIT_TONGDUN_CRIME_BLACK_LIST int comment '身份证命中犯罪通缉名单',
   ID_HIT_TONGDUN_COURT_EXECUTE_LIST int comment '身份证命中法院执行名单',
   ID_HIT_TONGDUN_LOST_CONTACT_LIST int comment '身份证号命中失联名单',
   ID_HIT_TONGDUN_LEGAL_PERSON_BLACK_LIST int comment '身份证命中公司法人失信名单',
   MOBILE_HIT_TONGDUN_LEGAL_PERSON_BLACK_LIST int comment '手机号命中公司法人失信名单',
   MOBILE_HIT_TONGDUN_LOAN_BLACK_INTERMEDIARY int comment '申请人手机号命中贷款黑中介',
   CONTACT_MOBILE_HIT_TONGDUN_LOAN_BLACK_INTERMEDIARY int comment '手机号命中贷款黑中介',
   HIT_TONGDUN_REPEATE_LOAN_ONE_WEEKEND int comment '7天内多头',
   HIT_TONGDUN_REPEATE_LOAN_ONE_MONTH int comment '1个月内多头',
   HIT_TONGDUN_REPEATE_LOAN_THREE_MONTH int comment '3个月内多头',
   HIT_TONGDUN_REPEATE_LOAN_SIX_MONTH int comment '6个月内多头',
   TONGDUN_REPEATE_LOAN_ONE_WEEKEND_DIV_ONE_MONTH decimal(38,10) comment '同盾7天内多头/1个月内多头占比',
   BORROW_TIME_SHORT_IN_DEVICE int comment '设备或账户两次借款时间间隔极短',
   MOVE_DISTANCE_EXCEPTION_IN_DEVICE int comment '设备或账户在短时间内移动距离异常拒绝',
   ONE_HOUR_MANY_ACCOUNT_IN_DEVICE int comment '1小时内设备使用过多账户进行借款',
   ONE_DAY_MANY_ACCOUNT_IN_DEVICE int comment '1天内设备使用过多账户进行借款',
   ONE_HOUR_MUCH_ACCOUNT_IN_DEVICE int comment '1小时内设备上进行借款的账户极多',
   ONE_DAY_MUCH_ACCOUNT_IN_DEVICE int comment '1天内设备上进行借款的账户极多',
   SEVEN_DAY_MUCH_ACCOUNT_IN_DEVICE int comment '7天内设备上进行借款的账户极多',
   ONE_HOUR_MUCH_ACCOUNT_ALL int comment '1小时内设备上在全局进行借款的账户极多_排除本合作方',
   ONE_DAY_MUCH_ACCOUNT_ALL int comment '1天内设备上在全局进行借款的账户极多_排除本合作方',
   SEVEN_DAY_MUCH_ACCOUNT_ALL int comment '7天内设备上在全局进行借款的账户极多_排除本合作方',
   TONGDUN_FINAL_SCORE  int comment '同盾风险分数',
   BQS_FRAUD_UUID       string comment '白骑士反欺诈UUID',
   HIT_BQS_RISK_USER_DECISION_REJECT int comment '白骑士风险名单比对结果',
   FOCUS_UUID           string comment '芝麻行业关注UUID',
   HIT_ZHIMA_FOCUS      int comment '芝麻行业关注名单是否在风险名单中',
   USER_EDU_UUID        string comment '用户学历信息UUID',
   IDENTITY_TYPE        int comment '用户身份 1:无业 2::白领 3::蓝领',
   COLLEGE              string comment '用户学校',
   IS_211               int comment '用户学校是否是211',
   START_DATE           int comment '用户入学年份',
   GRADUATE_DATE        int comment '毕业年份',
   EDU_DEGREE           int comment '用户学历 0:未知 1:专科以下 2:专科 3:本科 4:硕士研究生 5.:博士 6:211本科',
   BRXY_UUID            string comment '百融信用UUID',
   SHZX_UUID            string comment '上海资信UUID',
   USER_CONTACT_CNT     int comment '通讯录联系人个数',
   USER_CONTACT_HIGH_DANGER_CNT int comment '通讯录中高危联系人个数',
   USER_CONTACT_HIGH_DANGER_RATE decimal(38,10) comment '通讯录高危联系人个数占比',
   NEED_MOXIE_110       int comment '大额借是否需要魔蝎运营商授权 0:否 1:是',
   NEED_MOXIE_111       int comment '闪电借是否需要魔蝎运营商授权 0:否 1:是',
   ZHIMA_FOCUS_DCIN     int comment '芝麻Focus决策结果 0:拒绝 1:准入',
   SCORE_LEVEL          string comment '大额白领评分卡评级',
   WIDE_ACCESS_DCIN_110 int comment '大额借大准入决策结果 0:拒绝 1:准入',
   NARROW_ACCESS_DCIN_110 int comment '大额借小准入决策结果 0:否 1:是',
   WIDE_ACCESS_DCIN_111 int comment '闪电借大准入决策结果 0:拒绝 1:准入',
   NARROW_ACCESS_DCIN_111 int comment '闪电借小准入决策结果 0:否 1:是',
   REJECT_RULE_ID       string comment '拒绝规则码',
   REJECT_REASON_ID     string comment '拒绝原因码')
COMMENT '风控用户授信事实表'
ROW FORMAT DELIMITED
  NULL DEFINED AS ''
STORED AS PARQUET 
TBLPROPERTIES ("parquet.compression"="SNAPPY");