drop table if exists idw.FACT_MAIYA_ORDER;
create table if not exists idw.FACT_MAIYA_ORDER
(
   DW_CREATE_BY         string comment '系统字段-创建者',
   DW_CREATE_TIME       string comment '系统字段-创建时间',
   DW_UPDATE_BY         string comment '系统字段-修改者',
   DW_UPDATE_TIME       string comment '系统字段-修改时间',
   ORDER_ID             int comment '订单ID',
   CREATE_USER          int comment '下单用户',
   CREATE_TIME          string comment '下单时间',
   UPDATE_USER          int comment '更新用户',
   UPDATE_TIME          string comment '更新时间',
   ORDER_NO             string comment '订单号',
   STATUS               int comment '订单状态',
   STATUS_DESC          string comment '订单状态描述',
   SHOP_ID              int comment '商户ID',
   SHOP_NAME            string comment '商户名称',
   SHOP_COMPANY_TYPE    string comment '商户行业',
   FACE_ID              int comment '门店ID',
   FACE_NAME            string comment '门店名称',
   APPLY_AMOUNT         decimal(38,10) comment '申请金额',
   APPLY_PARTS          int comment '申请期数',
   PRACTICAL_MONEY      decimal(38,10) comment '实际放款金额',
   PRINCIPAL            decimal(38,10) comment '本金',
   YEAR_RATE            decimal(38,10) comment '年利率',
   SERVICE_MONEY        decimal(38,10) comment '服务费',
   TOTAL_PARTS          int comment '订单总期数',
   ORDER_BEGIN_DATE     string comment '订单开始时间',
   ORDER_END_DATE       string comment '订单结束时间',
   PASS_TIME            string comment '审核通过时间',
   USER_CONFIRM_TIME    string comment '用户确认时间',
   SHOP_CONFIRM_TIME    string comment '商户确认时间',
   LENDING_TIME         string comment '放款时间',
   ORDER_TYPE           int comment '订单类型',
   LBS_Y                string comment '纬度',
   LBS_X                string comment '经度',
   EMPLOYEE_ID          int comment '员工ID',
   GOODS_ID             int comment '商品ID',
   CHANNEL_ID           int comment '渠道ID',
   IS_CALL              int comment '是否拨打电话',
   NONOBANK_USERID      bigint comment '诺诺用户ID',
   SHOP_DEDUCTION       decimal(38,10) comment '商户分息',
   BO_ID                bigint comment '借款ID',
   SHOP_BANKNO          string comment '商户银行卡号',
   SHOP_RATE            decimal(38,10) comment '商户砍头息',
   IS_ONLINE            int comment '线上还是线下 1:线上 2:线下',
   CREDIT_LEVEL         string comment '用户信用等级',
   REPAYMENT_TYPE       int comment '还款方式 1:等本等息 2:前低后高',
   HILO_STR             string comment '低高还款方式间隔字符串',
   APPLY_HILO_STR       string comment '申请先低后高',
   PEND_FLAG            string comment '待放款订单子状态',
   OLD_ORDER_ID         int comment '原来的订单ID',
   SOURCE               int comment '标的来源',
   REJECT_REASON_1      string comment '人工拒绝一级原因码',
   REJECT_REASON_DESC_1 string comment '人工拒绝一级原因描述',
   REJECT_REASON_2      string comment '人工拒绝二级原因码',
   REJECT_REASON_DESC_2 string comment '人工拒绝二级原因描述',
   RETURN_REASON        string comment '回退原因',
   RETURN_REASON_DESC   string comment '回退原因描述',
   CANCEL_REASON        string comment '取消原因',
   CANCEL_REMARK        string comment '取消备注',
   TONGDUN_SCORE        string comment '同盾分',
   CREDIT_NODE          string comment '信用评级node',
   BD_NAME              string comment 'bd姓名',
   AUTO_REJECT_REASON_DESC   string comment '自动审批拒绝原因描述',
   REVIEW_SOURCE string comment '是否渠道审核（0是麦芽审核，1是代渠道审核）',
   QD_PASS string comment '渠道是否审核通过/渠道担保成功 1 ',
   FACHANNEL_NAME string comment '父渠道名',
   SUBCHANNEL_NAME string COMMENT '子渠道名')
COMMENT '麦芽订单表'
ROW FORMAT DELIMITED
  NULL DEFINED AS ''
STORED AS PARQUET 
TBLPROPERTIES ("parquet.compression"="SNAPPY");
