DROP TABLE  IF EXISTS IDW.FACT_IPC_PRODUCT;


CREATE TABLE  IF NOT EXISTS IDW.`FACT_IPC_PRODUCT`(
  `DW_CREATE_BY` STRING COMMENT '系统字段-创建者', 
  `DW_CREATE_TIME` STRING COMMENT '系统字段-创建时间', 
  `DW_UPDATE_BY` STRING COMMENT '系统字段-修改者', 
  `DW_UPDATE_TIME` STRING COMMENT '系统字段-修改时间', 
  `SRC_ID` STRING COMMENT '数据源表ID', 
  `RUN_ID` STRING COMMENT '任务ID', 
  `PLATFORM_NAME` STRING COMMENT '平台名称', 
  `PLATFORM_URL` STRING COMMENT '平台URL', 
  `CATEGORY_NAME` STRING COMMENT '品类名称', 
  `CATEGORY_URL` STRING COMMENT '品类URL', 
  `PRODUCT_NAME` STRING COMMENT '产品名称',
   DIM_PRODUCT_NAME STRING COMMENT '产品统一名称:新手、月月升、活期、定期',
  `PRODUCT_URL` STRING COMMENT '产品URL', 
  `PRODUCT_INFO` STRING COMMENT '产品信息', 
  `PROFIT` STRING COMMENT '收益率', 
  `PROFIT_LOWER` DECIMAL(38,10) COMMENT '', 
  `PROFIT_UPPER` DECIMAL(38,10) COMMENT '', 
  `PROFIT_INFO` STRING COMMENT '收利率相关信息', 
  `THE_INVEST_AMOUNT` INT COMMENT '投资金额', 
   DIM_THE_INVEST_TYPE STRING COMMENT '期限类别：天、月',
  `THE_INVEST_TERM` STRING COMMENT '投资期限', 
  `THE_INVEST_TERM_LOWER` DECIMAL(38,10) COMMENT '', 
  `THE_INVEST_TERM_UPPER` DECIMAL(38,10) COMMENT '', 
  `BANLANCE` STRING COMMENT '剩余金额', 
  `OTHER_INFO` STRING COMMENT '其他信息', 
  `INSERT_TIME` STRING COMMENT '插入时间', 
  `STATUS` STRING COMMENT '产品状态')
COMMENT '竞品整合表'
PARTITIONED BY(DAY_ID STRING COMMENT '日期 ID')
STORED AS PARQUET 
TBLPROPERTIES ('parquet.compression'='SNAPPY');