drop table if exists idw.FACT_BORROWS;
create table if not exists idw.FACT_BORROWS
(
   BO_ID                bigint comment '借款ID',
   P_ID                 bigint comment '产品ID',
   BUSI_LINE            string comment '所属业务线',
   BP_ID                bigint comment '预发标ID',
   USER_ID              bigint comment '用户ID',
   BO_AIM               string comment '借款目的',
   BO_TITLE             string comment '借款标题',
   BO_REPAYSRC          string comment '还款来源',
   BO_PRICE             decimal(38,10) comment '借款金额',
   BO_FINISH_PRICE      decimal(38,10) comment '完成金额',
   BO_EXPECT            int comment '借款期限',
   BO_EXPECT_CAT        int comment '借款期限单位',
   BO_BIDDING_TYPE      int comment '标的类型',
   BO_SAFEGUARD_TYPE    int comment '保障方式',
   BO_TYPE              int comment '借款类型',
   IS_ASSURANCE         int comment '是否请求担保',
   BO_RATE              decimal(38,10) comment '借款年利率',
   BO_TIME              int comment '有效时间',
   BO_PAYTYPE           string comment '还款方式',
   BO_IS_INDEX          int comment '是否推荐',
   BO_IS_STATE          int comment '借款状态',
   PUBLISH_TIME         string comment '发布时间',
   BO_FINISH_RATE       decimal(38,10) comment '完成度',
   BO_IS_FINISH         int comment '是否完成',
   BO_FINISH_TIME       string comment '完成时间',
   BO_SIGN_AM_ID        bigint comment '签约人员',
   BO_SIGN_TIME         string comment '签约时间',
   BO_SIGN_RESULT       int comment '签约结果',
   BO_AUDIT_AM_ID       bigint comment '审核人员',
   BO_AUDIT_TIME        string comment '审核时间',
   BO_AUDIT_REMARK      string comment '审核备注',
   BO_IS_SUCCESS        int comment '是否审核通过 1:通过 2:拒绝 3:超时流标 4:回退',
   BO_CAN_SUCCESS       int comment '是否可以审核通过',
   BO_IS_REPUBLISH      int comment '是否已重发',
   BO_IS_CASE           int comment '是否推荐案例',
   BO_GUID              string comment '电子协议guid',
   BO_EXTNO             string comment '协议编号',
   BO_AGREE_GENERATED   int comment '协议是否生成',
   BO_AGREE_TIME        string comment '协议生成时间',
   BO_ALL_REPAYED       int comment '借款还款结束',
   ALL_REPAYED_TIME     string comment '还款结束时间',
   BO_SORCE_TALK        int comment '谈吐分值',
   BO_SORCE_INSTRUMENT  int comment '仪表分值',
   BO_SORCE_FACE        int comment '面相分值',
   BO_SORCE_COOPERATION int comment '配合度分值',
   BO_PLEDGE            int comment '是否抵押',
   BO_HOUSE             string comment '房产信息',
   CREATOR              bigint comment '创建人',
   UPDATOR              bigint comment '更新人',
   CREATE_TIME          string comment '创建时间',
   UPDATE_TIME          string comment '更新时间',
   BO_PURPOSE           string comment '借款用途',
   ZX_PRICE             decimal(38,10) comment '咨询费',
   ZX_STATUS            int comment '咨询费状态 0:暂扣 1:退换 2:逾期扣除',
   IS_REPEAT_BORROW     int comment '是否复借',
   IS_VIDEO_AUDIT       int comment '是否提交视频',
   VIDEO_AUDIT_TIME     string comment '视频提交时间',
   FIRST_AUDIT_TIME     string comment '首次初审时间',
   LAST_AUDIT_PASS_TIME string comment '最近初审通过时间',
   LAST_CONFIRM_TIME    string comment '最近终审时间',
   CONFIRM_PASS_TIME    string comment '终审通过时间',
   REPAY_BEGIN_DAY      string comment '起始还款日',
   IS_FIRST_REPAY_OVERDUE int comment '是否首还逾期',
   FIRST_REPAY_OVERDUE_DAYS int comment '首还逾期天数',
   INTEREST_RATE_CUT    decimal(38,10) comment '减息',
   REPAYMENT_COUPON     decimal(38,10) comment '还款券金额',
   DW_CREATE_BY         string comment '系统字段-创建者',
   DW_CREATE_TIME       string comment '系统字段-创建时间',
   DW_UPDATE_BY         string comment '系统字段-修改者',
   DW_UPDATE_TIME       string comment '系统字段-修改时间',
   CUR_STATUS           string comment '当前状态',
   AUDIT_STATUS         string comment '初审状态',
   CONFIRM_STATUS       string comment '终审状态',
   AUDIT_REJECT_TIME    string comment '初审拒绝时间',
   CONFIRM_REJECT_TIME  string comment '终审拒绝时间',
   REJECT_TIME          string comment '拒绝时间',
   AUDIT_CANCEL_TIME    string comment '初审取消时间',
   CONFIRM_CANCEL_TIME  string comment '终审取消时间',
   FAIL_TIME            string comment '流标时间',
   CATEGORY_NAME_01     string comment '产品分类01',
   BIZ_CODE_01          string comment '业务线编码01',
   BIZ_NAME_01          string comment '业务线名称01',
   DEPOSITORY_FLAG      int comment '存管标记 0:初始 1:走存管 2:不走存管',
   FIRST_OVERDUE_EXPECT_NUM int comment '首次逾期期数',
   FIRST_OVERDUE_BR_TIME string comment '首次逾期应还时间',
   TRANSFER_ACCOUNT_TIME string comment '实际划转成功时间',
   P_NAME               string comment '产品名称',
   MONTHLY_REPAYMENT_AMT decimal(38,10) comment '月还款金额',
   BO_SUCCESS_TIME      string comment '放款时间',
   BO_SUCCESS_NUM       int comment '成功放款批次',
   BO_CONFIRM_NUM       int comment '终审通过批次',
   USER_IDENTITY_TYPE int COMMENT '用户身份： 1-无业，2-白领，3-蓝领', 
   TOTAL_AMOUNT decimal(38,10) COMMENT '总额度', 
   BASE_AMOUNT decimal(38,10) COMMENT '基础额度', 
   USED_AMOUNT decimal(38,10) COMMENT '已使用可借额度', 
   INCREASE_AMOUNT decimal(38,10) COMMENT '增信额度', 
   TOP_AMOUNT decimal(38,10) COMMENT '额度上限:个人最高额度限制', 
   LBS_ACCESS_CITY string COMMENT '准入时获取的LBS地址', 
   LBS_COMPLETE_DATA_CITY string COMMENT '生成正式标的LBS地址',
   CREDIT_TYPE          int comment '授信模式类型 1-基础项提额项模式, 2-高学历模式, 3-消费能力模式',
   BP_CHANNEL           int comment '申请渠道',
   RC_ID                bigint comment '资方id',
   RC_NAME              string comment '资方名称',
   P_KEY                int comment '产品代理键',
   PASS_TIME            string comment '审核通过时间',
   ML_TIME              string comment '进件时间',
   BO_LAST_REPAYED_TIME string comment '最近还款时间',
   ML_PRICE             decimal(38,10) comment '进件金额',
   CONFIRM_PASS_PRICE   decimal(38,10) comment '审批金额',
   IS_BORROWS_RAISE     int comment '是否一键再借',
   IS_STOCK_CAMPAIGN    int comment '是否存量战役')
COMMENT '借款表'
ROW FORMAT DELIMITED
  NULL DEFINED AS ''
STORED AS PARQUET 
TBLPROPERTIES ("parquet.compression"="SNAPPY");