drop table if exists idw.FACT_REPAYED_BORROWS_STAT;
create table if not exists idw.FACT_REPAYED_BORROWS_STAT
(
   BO_ID                bigint comment '借款ID',
   P_ID                 bigint comment '产品ID',
   BUSI_LINE            string comment '所属业务线',
   USER_ID              bigint comment '用户ID',
   BO_RATE              decimal(38,10) comment '借款年利率',
   INTEREST_RATE_CUT    decimal(38,10) comment '减息',
   BO_FINISH_PRICE      decimal(38,10) comment '完成金额',
   BO_EXPECT            int comment '借款期限',
   BO_EXPECT_CAT        int comment '借款期限单位',
   IS_FIRST_REPAY_OVERDUE int comment '是否首还逾期',
   FIRST_REPAY_OVERDUE_DAYS int comment '首还逾期天数',
   BO_AUDIT_TIME        string comment '审核时间',
   BO_AGREE_TIME        string comment '协议生效时间',
   ALL_REPAYED_TIME     string comment '还款结束时间',
   OVERDUE_CNT          int comment '逾期期数',
   OVERDUE_PRICE        decimal(38,10) comment '逾期金额',
   OVERDUE_PRICE_B      decimal(38,10) comment '逾期本金',
   OVERDUE_PRICE_L      decimal(38,10) comment '逾期利息',
   OVERDUE_PRICE_PUNISH decimal(38,10) comment '逾期罚息',
   OVERDUE_SERVICE_FEE  decimal(38,10) comment '逾期服务费',
   MAX_OVERDUE_DAYS     int comment '最大逾期天数',
   TOTAL_OVERDUE_DAYS   int comment '累计逾期天数',
   DW_CREATE_BY         string comment '系统字段-创建者',
   DW_CREATE_TIME       string comment '系统字段-创建时间',
   DW_UPDATE_BY         string comment '系统字段-修改者',
   DW_UPDATE_TIME       string comment '系统字段-修改时间',
   IS_OVERDUE           int comment '是否有过逾期',
   FIRST_REPAY_TIME     string comment '首次还款时间',
   REPAY_BEGIN_DAY      string comment '起始还款日',
   REPAY_END_DAY        string comment '最终还款日',
   PREPAYMENT_PRICE     decimal(38,10) comment '提前还款金额',
   RETURNED_PRICE       decimal(38,10) comment '返还金额',
   REPAYED_PRICE        decimal(38,10) comment '已还金额',
   REPAYED_PRICE_B      decimal(38,10) comment '已还本金',
   REPAYED_PRICE_L      decimal(38,10) comment '已还利息',
   REPAYED_PRICE_PUNISH decimal(38,10) comment '已还罚息',
   MAX_CONTINUOUS_OVERDUE_PRICE_B decimal(38,10) comment '最大连续逾期本金',
   MAX_CONTINUOUS_OVERDUE_CNT int comment '最大连续逾期期数',
   CATEGORY_NAME_01     string comment '产品分类01',
   BIZ_CODE_01          string comment '业务线编码01',
   BIZ_NAME_01          string comment '业务线名称01',
   DEPOSITORY_FLAG      int comment '存管标记 0:初始 1:走存管 2:不走存管',
   FIRST_OVERDUE_EXPECT_NUM int comment '首次逾期期数',
   FIRST_OVERDUE_BR_TIME string comment '首次逾期应还时间',
   TRANSFER_ACCOUNT_TIME string comment '实际划转成功时间',
   P_NAME               string comment '产品名称',
   MONTHLY_REPAYMENT_AMT decimal(38,10) comment '月还款金额',
   REPAYED_EXTRA_FEE    decimal(38,10) comment '已还额外费用',
   P_KEY                int comment '产品代理键')
COMMENT '已还借款统计'
ROW FORMAT DELIMITED
  NULL DEFINED AS ''
STORED AS PARQUET 
TBLPROPERTIES ("parquet.compression"="SNAPPY");
