DROP TABLE IF EXISTS IDW.DIM_DES_MAIN;
CREATE TABLE IF NOT EXISTS IDW.DIM_DES_MAIN
(
USER_ID bigint comment '用户ID'
,bp_id bigint comment '预标ID'
,auditAmt    STRING    COMMENT '[审批额度]'
,contactMobileHitTongDunLoanBlackIntermediary    STRING    COMMENT '手机号命中贷款黑中介'
,faceSimilarPercent    STRING    COMMENT '[活体识别分数]'
,finalDes    STRING    COMMENT '决策最终结果为 通过'
,hitTongDunRepeateLoanOneMonth    STRING    COMMENT '1个月内申请人在多个平台申请借款'
,hitTongDunRepeateLoansixMonth    STRING    COMMENT '6个月内申请人在多个平台申请借款'
,idCardSimilarPercent    STRING    COMMENT '[身份证识别分数]'
,idHitOurBlackList    STRING    COMMENT '[申请人的身份证号命中我方黑名单]'
,idHitTongDunCourtBlackList    STRING    COMMENT '身份证命中法院失信名单'
,idHitTongDunCourtExecuteList    STRING    COMMENT '身份证命中法院执行名单'
,idHitTongDunCrimeBlackList    STRING    COMMENT '身份证命中犯罪通缉名单'
,idHitTongDunLegalPersonBlackList    STRING    COMMENT '身份证命中公司法人失信名单'
,idHitTongDunLoanBlackList    STRING    COMMENT '身份证命中网贷黑名单'
,idHitTongDunLostContactList    STRING    COMMENT '身份证号命中失联名单'
,idNameHitTongDunFuzzyCourtBlackList    STRING    COMMENT '身份证_姓名命中法院失信模糊名单'
,idNameHitTongDunFuzzyCourtExecuteList    STRING    COMMENT '身份证_姓名命中法院执行模糊名单'
,idNameHitTongDunFuzzyLoanBlackList    STRING    COMMENT '身份证_姓名命中网贷模糊黑名单'
,immediateFamilyMobileHitOurBlackList    STRING    COMMENT '[直系亲属手机号命中我方黑名单]'
,isJxhj    STRING    COMMENT '[借新还旧标志(是否一件再借)]'
,isNeedTelephoneAudit    STRING    COMMENT '字段Key:[maxOverDueDays]value[最大逾期天数]无法获取,字段Key:[maxOverDueDayLessThanSeven]value[最大逾期天数<=7天]无法获取,字段Key:[lastLoanAmt]value[上次贷款金额]无法获取,字段Key:[loanAmtLessThanLastLoanAmtOnePointFive]value[贷款金额<=上次贷款金额*1.5]无法获取,免电核最终结果为 未通过'
,isNewUser    STRING    COMMENT '[新增用户标志]'
,isRetainedUser    STRING    COMMENT '[是否存量用户]'
,lastLoanAmt    STRING    COMMENT '[上次贷款金额]'
,lastLoanTime    STRING    COMMENT '[上次贷款时间]'
,latestRtnLoanDate    STRING    COMMENT '[最近一次实际还款日期]'
,loanAmt    STRING    COMMENT '[贷款金额]'
,loanApplyDate    STRING    COMMENT '[贷款申请日期]'
,loanStatusNormal    STRING    COMMENT '[贷款是否正常]'
,loanStatusOverdue    STRING    COMMENT '[贷款是否逾期]'
,maxOverDueDays    STRING    COMMENT '[最大逾期天数]'
,mobileHitOurBlackList    STRING    COMMENT '[申请人的手机号命中我方黑名单]'
,mobileHitTongDunLegalPersonBlackList    STRING    COMMENT '手机号命中公司法人失信名单'
,mobileHitTongDunLoanBlackIntermediary    STRING    COMMENT '申请人手机号命中贷款黑中介'
,mobileHitTongDunLoanBlackList    STRING    COMMENT '手机号命中网贷黑名单'
,mobileHitTongDunLostContactList    STRING    COMMENT '手机号命中失联名单'
,overDue30Days1Times    STRING    COMMENT '[逾期天数>30天的次数大于1]'
,overDue7Days4Times    STRING    COMMENT '[逾期天数>7天的次数大于4]'
,overdueTerm    STRING    COMMENT '[逾期期数]'
,productId    STRING    COMMENT '[产品编号]'
,rtnTerm    STRING    COMMENT '[已还期数]'
,schoolAcademy    STRING    COMMENT '学校'
,scoreLevel    STRING    COMMENT '评级'
,scoreResult    STRING    COMMENT '评分'
,studentEducation    STRING    COMMENT '学历'
,studentEduStartDate    STRING    COMMENT '入学时间'
,studentGrade    STRING    COMMENT '用户年级'
,studentSchoolType    STRING    COMMENT '学校类别'
,studentTermProcess    STRING    COMMENT '学期进度'
,term    STRING    COMMENT '[贷款期限]'
,tongdunFinalScore    STRING    COMMENT '同盾风险分数'
,tongdunUuid    STRING    COMMENT '同盾采集uuid'
,userAge    STRING    COMMENT '用户年龄'
,userCensusAddress    STRING    COMMENT '户籍地址'
,userGender    STRING    COMMENT '用户性别'
,userIdNumber    STRING    COMMENT '用户身份证号'
,userKinMobile    STRING    COMMENT '直接亲属手机号'
,userMobile    STRING    COMMENT '用户手机号'
,userRiskBill    STRING    COMMENT '是否风险名单'
,userSchoolProvince    STRING    COMMENT '学校省份'
,vocationalSchoolThree    STRING    COMMENT '专三'
,zhiMaScore    STRING    COMMENT '[芝麻分]'
,zhimaUuid    STRING    COMMENT '芝麻采集uuid'


   ,DW_CREATE_BY         STRING COMMENT '系统字段-创建者'
   ,DW_CREATE_TIME       STRING COMMENT '系统字段-创建时间'
   ,DW_UPDATE_BY         STRING COMMENT '系统字段-修改者'
   ,DW_UPDATE_TIME       STRING COMMENT '系统字段-修改时间'
) COMMENT '风控DES_MAIN维表'
STORED AS PARQUET TBLPROPERTIES ("parquet.compression"="SNAPPY");
