drop table if exists idw.user_tag_finance;
create table if not exists idw.user_tag_finance
(
    dw_create_by  string COMMENT '系统字段-创建者',  
    dw_create_time  string COMMENT '系统字段-创建时间',  
    dw_update_by  string COMMENT '系统字段-修改者',  
    dw_update_time  string COMMENT '系统字段-修改时间',  
    user_id  bigint COMMENT '用户id',  
    --nono
    nono_first_invest_time  string COMMENT '诺诺首次投资时间',  
    nono_first_invest_amt  decimal(38,10) COMMENT '诺诺首次投资金额',  
    nono_first_invest_product_scope  string COMMENT '诺诺首次投资产品',  
    nono_first_invest_amt_yearly  decimal(38,10) COMMENT '诺诺首次投资年化金额',  
    nono_first_invest_expect  string COMMENT '诺诺首次投资期限',  
    nono_second_invest_time  string COMMENT '诺诺2次投资时间',  
    nono_second_invest_amt  decimal(38,10) COMMENT '诺诺2次投资金额',  
    nono_second_invest_product_scope  string COMMENT '诺诺2次投资产品',  
    nono_second_invest_amt_yearly  decimal(38,10) COMMENT '诺诺2次投资年化金额',  
    nono_second_invest_expect  string COMMENT '诺诺2次投资期限',  
    nono_third_invest_time  string COMMENT '诺诺3次投资时间',  
    nono_third_invest_amt  decimal(38,10) COMMENT '诺诺3次投资金额',  
    nono_third_invest_product_scope  string COMMENT '诺诺3次投资产品',  
    nono_third_invest_amt_yearly  decimal(38,10) COMMENT '诺诺3次投资年化金额',  
    nono_third_invest_expect  string COMMENT '诺诺3次投资期限',  
    nono_last_invest_time  string COMMENT '诺诺最近投资时间',  
    nono_last_invest_amt  decimal(38,10) COMMENT '诺诺最近投资金额',  
    nono_last_invest_product_scope  string COMMENT '诺诺最近投资产品',  
    nono_last_invest_amt_yearly  decimal(38,10) COMMENT '诺诺最近投资年化金额',  
    nono_last_invest_expect  string COMMENT '诺诺最近投资期限',  
    nono_last_cash_time  string COMMENT '诺诺最近兑付时间',  
    nono_last_cash_principal_amt  decimal(38,10) COMMENT '诺诺最近兑付本金',  
    nono_last_cash_amt  decimal(38,10) COMMENT '诺诺最近兑付金额',  
    nono_last_cash_product_scope  string COMMENT '诺诺最近兑付产品',  
    nono_last_cash_fp_id  bigint COMMENT '诺诺最近兑付计划id',  
    nono_aum  decimal(38,10) COMMENT '诺诺当前aum',  
    nono_max_aum  decimal(38,10) COMMENT '诺诺历史最大aum',  
    nono_max_aum_date  string COMMENT '诺诺历史最大aum日期',  
    nono_last_30_days_invest_cnt  int COMMENT '诺诺过去30天投资次数',  
    nono_invest_cnt  int COMMENT '诺诺累计投资次数',  
    nono_total_invest_amt  decimal(38,10) COMMENT '诺诺累计投资金额',  
    nono_total_invest_amt_yearly  decimal(38,10) COMMENT '诺诺累计年化投资金额',  
    nono_total_plan_invest_cnt  int COMMENT '诺诺累计精选投资次数',  
    nono_total_plan_invest_amt  decimal(38,10) COMMENT '诺诺累计精选投资金额',  
    nono_total_plan_invest_amt_yearly  decimal(38,10) COMMENT '诺诺累计精选年化投资金额',  
    nono_in_invest_amt  decimal(38,10) COMMENT '诺诺在投金额',  
    nono_max_in_invest_amt  decimal(38,10) COMMENT '诺诺最高在投金额',  
    nono_max_in_invest_amt_date  string COMMENT '诺诺最高在投金额出现日期',
    nono_last_withdraw_time  string COMMENT '诺诺最近提现时间',  
    nono_last_withdraw_amt  decimal(38,10) COMMENT '诺诺最近提现金额',  
    nono_last_90_days_withdraw_cnt  int COMMENT '诺诺过去90天提现次数',  
    nono_last_90_days_withdraw_amt  decimal(38,10) COMMENT '诺诺过去90天提现金额',  
    nono_7days_recharge_amt  decimal(38,10) COMMENT '诺诺7日内成功充值金额',  
    nono_7days_withdraw_amt  decimal(38,10) COMMENT '诺诺7日内成功取现金额',  
    nono_7days_eta_amt  decimal(38,10) COMMENT '诺诺7日内预计到期金额',  
    nono_last_30_days_login_cnt  int COMMENT '诺诺过去30天登录次数',  
    nono_last_60_days_login_cnt  int COMMENT '诺诺过去60天登录次数',  
    nono_user_lost_status  string COMMENT '诺诺用户流失状态',  
    nono_prolocutor_invite_register_cnt  int COMMENT '镑客大使邀请注册成功次数',  
    
    --nono_new_20180817
    nono_aum_yearly decimal(38,10) COMMENT '在投年化金额（计划类产品）',
    nono_max_aum_year decimal(38,10) COMMENT '近一年最高在投',
    nono_invet_cnt_month int COMMENT '近一月投资次数',
    nono_bbs_active_30 int COMMENT '最近30天论坛登录活跃度',
    nono_shop_active_90 int COMMENT '最近90天商城兑换活跃度',
    nono_invest_active_90 int COMMENT '最近90天投资活跃度',
    nono_login_active_30 int COMMENT '最近30天登录活跃度',
    nono_login_interval int COMMENT '最近登录间隔天数',
    nono_sign_m int COMMENT '当月累计签到次数',
    nono_sign_last_time string COMMENT '最近一次签到时间',
    nono_no_invest_reason string COMMENT '未投资原因',
    nono_tel_cnt int COMMENT '电话咨询次数',
    nono_lost_ratio decimal(38,10) COMMENT '潜在流失系数',
    nono_invest_ratio decimal(38,10) COMMENT '当日在投与前一日在投系数',
    nono_lost_rank int COMMENT '流失用户等级',
    nono_bt_coupon_cnt int COMMENT '可用补贴券数',
    nono_bt_coupon_lost_time string COMMENT '补贴券最近失效时间',
    nono_dy_coupon_cnt int COMMENT '可用抵用券金额',
    nono_dy_coupon_lost_time string COMMENT '抵用券最近失效时间',
    nono_cash_packet_wait decimal(38,10) COMMENT '待激活现金红包金额',
    nono_money int COMMENT '可用诺币',
    nono_tqbj_wait_money decimal(38,10) COMMENT '待激活特权本金金额',
    nono_tqbj_lost_time string COMMENT '特权本金最近失效时间',

    --csyy
    csyy_first_invest_time  string COMMENT '财神首次投资时间',  
    csyy_first_invest_amt  decimal(38,10) COMMENT '财神首次投资金额',  
    csyy_first_invest_product_code  string COMMENT '财神首次投资产品',  
    csyy_first_invest_amt_yearly  decimal(38,10) COMMENT '财神首次投资年化金额',  
    csyy_first_invest_expect  string COMMENT '财神首次投资期限',  
    csyy_second_invest_time  string COMMENT '财神2次投资时间',  
    csyy_second_invest_amt  decimal(38,10) COMMENT '财神2次投资金额',  
    csyy_second_invest_product_code  string COMMENT '财神2次投资产品',  
    csyy_second_invest_amt_yearly  decimal(38,10) COMMENT '财神2次投资年化金额',  
    csyy_second_invest_expect  string COMMENT '财神2次投资期限',  
    csyy_third_invest_time  string COMMENT '财神3次投资时间',  
    csyy_third_invest_amt  decimal(38,10) COMMENT '财神3次投资金额',  
    csyy_third_invest_product_code  string COMMENT '财神3次投资产品',  
    csyy_third_invest_amt_yearly  decimal(38,10) COMMENT '财神3次投资年化金额',  
    csyy_third_invest_expect  string COMMENT '财神3次投资期限',  
    csyy_last_invest_time  string COMMENT '财神最近投资时间',  
    csyy_last_invest_amt  decimal(38,10) COMMENT '财神最近投资金额',  
    csyy_last_invest_product_code  string COMMENT '财神最近投资产品',  
    csyy_last_invest_amt_yearly  decimal(38,10) COMMENT '财神最近投资年化金额',  
    csyy_last_invest_expect  string COMMENT '财神最近投资期限',  
    csyy_last_cash_time  string COMMENT '财神最近兑付时间',  
    csyy_last_cash_principal_amt  decimal(38,10) COMMENT '财神最近兑付本金',  
    csyy_last_cash_amt  decimal(38,10) COMMENT '财神最近兑付金额',  
    csyy_last_cash_product_code  string COMMENT '财神最近兑付产品',  
    csyy_aum  decimal(38,10) COMMENT '财神当前aum',  
    csyy_max_aum  decimal(38,10) COMMENT '财神历史最大aum',  
    csyy_max_aum_date  string COMMENT '财神历史最大aum日期',  
    csyy_last_30_days_invest_cnt  int COMMENT '财神过去30天投资次数',  
    csyy_invest_cnt  int COMMENT '财神累计投资次数',  
    csyy_total_invest_amt  decimal(38,10) COMMENT '财神累计投资金额',  
    csyy_total_invest_amt_yearly  decimal(38,10) COMMENT '财神累计年化投资金额',  
    csyy_balance_amt  decimal(38,10) COMMENT '财神账户余额',  
    csyy_invite_user_id  bigint COMMENT '财神邀请用户id',  
    csyy_channel_id  int COMMENT '财神渠道id',  
    csyy_channel_name  string COMMENT '财神渠道名称',  
    csyy_7days_recharge_amt  decimal(38,10) COMMENT '财神7日内成功充值金额',  
    csyy_7days_withdraw_amt  decimal(38,10) COMMENT '财神7日内成功取现金额',  
    csyy_7days_eta_amt  decimal(38,10) COMMENT '财神7日内预计到期金额'
)
COMMENT '用户理财标签'
PARTITIONED BY (stat_date string COMMENT '统计日期 年-月-日')
ROW FORMAT DELIMITED
  NULL DEFINED AS ''
STORED AS PARQUET 
TBLPROPERTIES ("parquet.compression"="SNAPPY");
