DROP TABLE IF EXISTS IDW.USER_TAG_HIST;
CREATE TABLE IF NOT EXISTS IDW.USER_TAG_HIST
(   
   USER_ID              BIGINT COMMENT '用户唯一标识',  
   TAG_VALUE            STRING COMMENT '用户标签值',
   DW_CREATE_BY         STRING COMMENT '系统字段-创建者',
   DW_CREATE_TIME       STRING COMMENT '系统字段-创建时间',
   DW_UPDATE_BY         STRING COMMENT '系统字段-修改者',
   DW_UPDATE_TIME       STRING COMMENT '系统字段-修改时间'
) COMMENT '用户标签事实表'
PARTITIONED BY (TAG_ID INT COMMENT '用户标签编码', HASH_PARTITION_ID INT COMMENT '用户唯一标识哈希值')
STORED AS PARQUET TBLPROPERTIES ("parquet.compression"="SNAPPY");
;
