drop table if exists idw.user_info;
create table if not exists idw.user_info
(
   dw_create_by         string comment '系统字段-创建者',
   dw_create_time       string comment '系统字段-创建时间',
   dw_update_by         string comment '系统字段-修改者',
   dw_update_time       string comment '系统字段-修改时间',
   user_id              bigint comment '用户id',
   user_name            string comment '用户名',
   real_name            string comment '姓名',
   gender               int comment '性别 1:男 2:女',
   mobile_num           string comment '手机号',
   email                string comment '电子邮箱',
   is_email             int comment '是否邮件认证 0:否 1:是',
   register_time        string comment '注册时间',
   is_authentication    int comment '是否身份认证 0:否 1:是',
   is_photo             int comment '是否图像认证 0:否 1:是',
   is_education_auth    int comment '是否学历认证 0:否 1:是 2:拒绝',
   is_student_auth      int comment '是否学籍认证 0:否 1:是',
   is_special           int comment '是否特殊用户 0:否 1:是',
   is_cheat             int comment '是否欺诈 0:否 1:是',
   status               int comment '状态 0:无效用户 1:有效用户 2:锁定用户',
   status_desc          string comment '状态描述 0:无效用户 1:有效用户 2:锁定用户',
   pc_id                bigint comment '所属公司id',
   recommender          string comment '推荐人',
   user_type            int comment '用户类型 0:未知 1:理财 2:贷款 3:白领 4:微企业主 5:学生 6:企业主 7:vip企业主 8:企业',
   id_num               string comment '身份证号',
   finance_advisor      bigint comment '理财顾问',
   birthday             string comment '生日',
   mobile_address       string comment '手机归属市',
   mobile_address_province string comment '手机归属省',
   register_biz         string comment '注册业务线',
   english_name         string comment '英文名',
   age                  int comment '年龄',
   constellation        string comment '星座',
   qq                   string comment 'qq号码',
   current_mobile_no    string comment '当前手机号',
   hj_province          string comment '户籍省',
   hj_province_name     string comment '户籍省名称',
   hj_city              string comment '户籍市',
   hj_city_name         string comment '户籍市名称',
   hj_address           string comment '户籍地址',
   current_province     string comment '当前所在省',
   current_province_name string comment '当前所在省名称',
   current_city         string comment '当前所在市',
   current_city_name    string comment '当前所在市名称',
   birth_province       string comment '出生省份',
   contact_address      string comment '联系地址',
   marriage_status      int comment '婚姻状况 0:未知 1:已婚 2:未婚 3:已婚已育 4:已婚未育 5:未婚已育 6:丧偶 7:离婚',
   marriage_status_desc string comment '婚姻状态描述',
   is_have_passport     int comment '是否持有护照 0:未知 1:有 2:无',
   is_social_security   int comment '是否有社保 0:未知 1:有 2:无',
   is_driving_license   int comment '是否有驾照 0:未知 1:有 2:无',
   house_status         int comment '现居住地状况 0:未知 1:自购房(无房贷) 2:自购房(有按揭) 3:自建房 4:亲属房产 5:租房 6:其他',
   education            string comment '学历',
   channel_id           bigint comment '注册渠道id',
   channel_name         string comment '注册渠道名称',
   ad_plan              string comment '广告计划',
   ad_unit              string comment '广告单元',
   channel_detail       string comment '渠道明细',
   register_country_code int comment 'unifi注册所在国编码',
   register_country_name string comment 'unifi注册所在国名称',
   register_terminal    string comment '注册终端',
   register_ip          string comment '注册ip地址',
   job                  string comment '职业',
   current_job_time     string comment '工作年限',
   total_job_time       string comment '总工作年限',
   company_name         string comment '公司名称',
   company_type         string comment '公司类型',
   company_business_type int comment '工作单位性质',
   company_tel          string comment '公司电话号码',
   know_approach_code   string comment '客户获知渠道编码',
   know_approach_name   string comment '客户获知渠道名称',
   company_business_sort string comment '企业类别',
   company_address      string comment '单位地址',
   spouse_name          string comment '配偶名字',
   spouse_idnum         string comment '配偶身份证号',
   spouse_mobile        string comment '配偶手机号',
   spouse_company       string comment '配偶公司',
   monthly_salary       string comment '月薪',
   register_phone_model string comment '注册手机类型',
   register_phone_brand string comment '注册手机品牌',
   register_network     string comment '注册网络',
   account_id           bigint comment '账户号',
   balance_amt          decimal(38,10) comment '账户余额',
   balance_locking_amt  decimal(38,10) comment '账户锁定金额',
   balance_total_amt    decimal(38,10) comment '账户总额',
   hsb_account_no       string comment '徽商电子账号',
   hsb_status           string comment '徽商账户状态',
   hsb_balance          decimal(38,10) comment '徽商账户余额',
   hsb_freeze_amount    decimal(38,10) comment '徽商账户冻结额度',
   hsb_mobile           string comment '徽商手机号',
   hsb_bank_card        string comment '徽商银行卡号',
   industry     string comment '工作行业')
COMMENT '用户基础信息表'
PARTITIONED BY (stat_date string COMMENT '统计日期 年-月-日')
ROW FORMAT DELIMITED
  NULL DEFINED AS ''
STORED AS PARQUET 
TBLPROPERTIES ("parquet.compression"="SNAPPY");
