USE IDW ;
DROP TABLE IF EXISTS IDW.USER_TAG_TMP_02;
CREATE TABLE IDW.USER_TAG_TMP_02
( 
USER_ID BIGINT COMMENT'用户ID' 
,TAG_VALUE STRING COMMENT'用户标签值'
,TAG_COVER_TYPE_IND STRING COMMENT'用户标签覆盖方式'
)COMMENT'用户标签增量表' 
PARTITIONED BY(TAG_ID INT) 
CLUSTERED BY (USER_ID) SORTED BY (USER_ID ASC) INTO 10 BUCKETS
STORED AS PARQUET; 