set mapreduce.job.name = IDW_FACT_RM_USER_CREDIT;
set mapreduce.job.queuename = etl-dw;
set hive.exec.parallel=true;

INSERT OVERWRITE TABLE IDW.FACT_RM_USER_CREDIT
  select 'SYS' as dw_create_by,
         from_unixtime(unix_timestamp(), 'yyyy-MM-dd HH:mm:ss') as dw_create_time,
         'SYS' as dw_update_by,
         from_unixtime(unix_timestamp(), 'yyyy-MM-dd HH:mm:ss') as dw_update_time,
         duc.auth_id,
         duc.user_id,
         max(case when data_no = 'userIdNumber' then data_value end) USER_ID_NUMBER,
         max(case when data_no = 'realName' then data_value end) REAL_NAME,
         max(case when data_no = 'userMobile' then data_value end) USER_MOBILE,
         max(case when data_no = 'userAge' then data_value end) USER_AGE,
         max(case when data_no = 'userGender' then data_value end) USER_GENDER,
         max(case when data_no = 'idHitOurBlackList' then data_value end) ID_HIT_OUR_BLACK_LIST,
         max(case when data_no = 'mobileHitOurBlackList' then data_value end) MOBILE_HIT_OUR_BLACK_LIST,
         max(case when data_no = 'zhiMaScoreUUID' then data_value end) ZHIMA_SCORE_UUID,
         max(case when data_no = 'zhiMaScore' then data_value end) ZHIMA_SCORE,
         max(case when data_no = 'hdymBlackUUID' then data_value end) HDYM_BLACK_UUID,
         max(case when data_no = 'emayIsBlack' then data_value end) EMAY_IS_BLACK,
         max(case when data_no = 'zzcBlackUUID' then data_value end) ZZC_BLACK_UUID,
         max(case when data_no = 'hitZhongzhichengBlackListCount' then data_value end) HIT_ZZC_BLACK_LIST_CNT,
         max(case when data_no = 'hitZhongzhichengTenantCount' then data_value end) HIT_ZZC_TENANT_CNT,
         max(case when data_no = 'bdjrRiskUUID' then data_value end) BDJR_RISK_UUID,
         max(case when data_no = 'baiduBlackLevel' then data_value end) BDJR_BLACK_LEVEL,
         max(case when data_no = 'baiduBlackReason' then data_value end) BDJR_BLACK_REASON,
         max(case when data_no = 'tongdunUUID' then data_value end) TONGDUN_UUID,
         max(case when data_no = 'mobileHitTongDunLostContactList' then data_value end) MOBILE_HIT_TONGDUN_LOST_CONTACT_LIST,
         max(case when data_no = 'idNameHitTongDunFuzzyLoanBlackList' then data_value end) ID_NAME_HIT_TONGDUN_FUZZY_LOAN_BLACK_LIST,
         max(case when data_no = 'idNameHitTongDunFuzzyCourtBlackList' then data_value end) ID_NAME_HIT_TONGDUN_FUZZY_COURT_BLACK_LIST,
         max(case when data_no = 'idNameHitTongDunFuzzyCourtExecuteList' then data_value end) ID_NAME_HIT_TONGDUN_FUZZY_COURT_EXECUTE_LIST,
         max(case when data_no = 'idHitTongDunLoanBlackList' then data_value end) ID_HIT_TONGDUN_LOAN_BLACK_LIST,
         max(case when data_no = 'mobileHitTongDunLoanBlackList' then data_value end) MOBILE_HIT_TONGDUN_LOAN_BLACK_LIST,
         max(case when data_no = 'idHitTongDunCourtBlackList' then data_value end) ID_HIT_TONGDUN_COURT_BLACK_LIST,
         max(case when data_no = 'idHitTongDunCrimeBlackList' then data_value end) ID_HIT_TONGDUN_CRIME_BLACK_LIST,
         max(case when data_no = 'idHitTongDunCourtExecuteList' then data_value end) ID_HIT_TONGDUN_COURT_EXECUTE_LIST,
         max(case when data_no = 'idHitTongDunLostContactList' then data_value end) ID_HIT_TONGDUN_LOST_CONTACT_LIST,
         max(case when data_no = 'idHitTongDunLegalPersonBlackList' then data_value end) ID_HIT_TONGDUN_LEGAL_PERSON_BLACK_LIST,
         max(case when data_no = 'mobileHitTongDunLegalPersonBlackList' then data_value end) MOBILE_HIT_TONGDUN_LEGAL_PERSON_BLACK_LIST,
         max(case when data_no = 'mobileHitTongDunLoanBlackIntermediary' then data_value end) MOBILE_HIT_TONGDUN_LOAN_BLACK_INTERMEDIARY,
         max(case when data_no = 'contactMobileHitTongDunLoanBlackIntermediary' then data_value end) CONTACT_MOBILE_HIT_TONGDUN_LOAN_BLACK_INTERMEDIARY,
         max(case when data_no = 'hitTongDunRepeateLoanOneWeekend' then data_value end) HIT_TONGDUN_REPEATE_LOAN_ONE_WEEKEND,
         max(case when data_no = 'hitTongDunRepeateLoanOneMonth' then data_value end) HIT_TONGDUN_REPEATE_LOAN_ONE_MONTH,
         max(case when data_no = 'hitTongDunRepeateLoanThreeMonth' then data_value end) HIT_TONGDUN_REPEATE_LOAN_THREE_MONTH,
         max(case when data_no = 'hitTongDunRepeateLoansixMonth' then data_value end) HIT_TONGDUN_REPEATE_LOAN_SIX_MONTH,
         max(case when data_no = 'tongDunRepeateLoanOneWeekendDivOneMonth' then data_value end) TONGDUN_REPEATE_LOAN_ONE_WEEKEND_DIV_ONE_MONTH,
         max(case when data_no = 'borrowTimeShortInDevice' then data_value end) BORROW_TIME_SHORT_IN_DEVICE,
         max(case when data_no = 'moveDistanceExceptionInDevice' then data_value end) MOVE_DISTANCE_EXCEPTION_IN_DEVICE,
         max(case when data_no = 'oneHourManyAccountInDevice' then data_value end) ONE_HOUR_MANY_ACCOUNT_IN_DEVICE,
         max(case when data_no = 'oneDayManyAccountInDevice' then data_value end) ONE_DAY_MANY_ACCOUNT_IN_DEVICE,
         max(case when data_no = 'oneHourMuchAccountInDevice' then data_value end) ONE_HOUR_MUCH_ACCOUNT_IN_DEVICE,
         max(case when data_no = 'oneDayMuchAccountInDevice' then data_value end) ONE_DAY_MUCH_ACCOUNT_IN_DEVICE,
         max(case when data_no = 'sevenDayMuchAccountInDevice' then data_value end) SEVEN_DAY_MUCH_ACCOUNT_IN_DEVICE,
         max(case when data_no = 'oneHourMuchAccountAll' then data_value end) ONE_HOUR_MUCH_ACCOUNT_ALL,
         max(case when data_no = 'oneDayMuchAccountAll' then data_value end) ONE_DAY_MUCH_ACCOUNT_ALL,
         max(case when data_no = 'sevenDayMuchAccountAll' then data_value end) SEVEN_DAY_MUCH_ACCOUNT_ALL,
         max(case when data_no = 'tongdunFinalScore' then data_value end) TONGDUN_FINAL_SCORE,
         max(case when data_no = 'bqsFraudUUID' then data_value end) BQS_FRAUD_UUID,
         max(case when data_no = 'hitBaiqishiRiskUserDecisionReject' then data_value end) HIT_BQS_RISK_USER_DECISION_REJECT,
         max(case when data_no = 'focusUUID' then data_value end) FOCUS_UUID,
         max(case when data_no = 'hitZhiMaFocus' then data_value end) HIT_ZHIMA_FOCUS,
         max(case when data_no = 'userEduUUID' then data_value end) USER_EDU_UUID,
         max(case when data_no = 'identityType' then data_value end) IDENTITY_TYPE,
         max(case when data_no = 'college' then data_value end) COLLEGE,
         max(case when data_no = 'is211' then data_value end) IS_211,
         max(case when data_no = 'startDate' then data_value end) START_DATE,
         max(case when data_no = 'graduateDate' then data_value end) GRADUATE_DATE,
         max(case when data_no = 'eduDegree' then data_value end) EDU_DEGREE,
         max(case when data_no = 'brxyUUID' then data_value end) BRXY_UUID,
         max(case when data_no = 'shzxUUID' then data_value end) SHZX_UUID,
         max(case when data_no = 'userContactCount' then data_value end) USER_CONTACT_CNT,
         max(case when data_no = 'userContactHighDangerCount' then data_value end) USER_CONTACT_HIGH_DANGER_CNT,
         max(case when data_no = 'userContactHighDangerRate' then data_value end) USER_CONTACT_HIGH_DANGER_RATE,
         max(case when data_no = 'needMoxie110' then data_value end) NEED_MOXIE_110,
         max(case when data_no = 'needMoxie111' then data_value end) NEED_MOXIE_111,
         max(case when data_no = 'zhimaFocusDcin' then data_value end) ZHIMA_FOCUS_DCIN,
         max(case when data_no = 'scoreLevel' then data_value end) SCORE_LEVEL,
         max(case when data_no = '110wideAccessDcin' then data_value end) WIDE_ACCESS_DCIN_110,
         max(case when data_no = '110narrowAccessDcin' then data_value end) NARROW_ACCESS_DCIN_110,
         max(case when data_no = '111wideAccessDcin' then data_value end) WIDE_ACCESS_DCIN_111,
         max(case when data_no = '111narrowAccessDcin' then data_value end) NARROW_ACCESS_DCIN_111,
         REJECT_RULE_ID,
         REJECT_REASON_ID
    from ods.t_des_user_credit_hist duc
    left join (select auth_id,
                      user_id,
                      concat_ws(',', collect_set(rule_id)) REJECT_RULE_ID,
                      concat_ws(',', collect_set(rule_result_code)) REJECT_REASON_ID
                 from ods.t_des_access_dcin_hist
                where rule_result_code not in ('UNHIT', '-1')
                group by auth_id, user_id) dad
      on duc.auth_id = dad.auth_id
     and duc.user_id = dad.user_id
   group by duc.auth_id, duc.user_id, REJECT_RULE_ID, REJECT_REASON_ID;