CREATE TABLE `DQ_COLUMN_SCRIPT` (
  `ID` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
  `COLUMN_ID` int(11) NOT NULL COMMENT '字段ID',
  `SCRIPT_ID` int(11) NOT NULL COMMENT '字段ID',
  `COLUMN_INDEX` int(11) DEFAULT NULL COMMENT '没用',
  `IS_VALID` int(1) NOT NULL DEFAULT '1' COMMENT '1:有效,0:无效',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `COLUMN_ID` (`COLUMN_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='字段和脚步对应关系';