CREATE TABLE `DQ_DATASOURCE` (
  `ID` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
  `JDBC_ID` int(11) NOT NULL COMMENT 'JDBC_ID',
  `JDBC_TYPE` int(2) NOT NULL COMMENT '1:HIVE,2:MYSQL',
  `TABLE_NAME` varchar(32) NOT NULL DEFAULT '' COMMENT '校验的数据表',
  `DATA_CONSTRAINTS` varchar(64) DEFAULT NULL COMMENT '查询查询条件',
  `IS_VALID` int(1) NOT NULL DEFAULT '1' COMMENT '1:有效,0:无效',
  `DATA_SCOPE` int(2) NOT NULL COMMENT '校验的数据范围:1全量、2增量',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='验证的数据表范围';