CREATE TABLE `DQ_DATASOURCE_COLUMN` (
  `ID` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
  `TABLE_ID` int(11) NOT NULL COMMENT '校验数据表ID',
  `COLUMN_NAME` varchar(64) NOT NULL DEFAULT '' COMMENT '校验的字段',
  `COLUMN_EXPRESSION` varchar(64) DEFAULT NULL COMMENT '字段函数',
  `STATISTICAL_MODE` int(11) NOT NULL DEFAULT '1' COMMENT '统计方式，1：COUNT(对字段进行数量校验) 2:SUM(对字段进行汇总校验) 3:COUNT DISITNCT 4:自定义SQL',
  `IS_VALID` int(1) NOT NULL DEFAULT '1' COMMENT '1:有效,0:无效',
  `DESC` varchar(128) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8 COMMENT='定义数据清洗的表字段';