CREATE TABLE `DQ_RULE_SCRIPT` (
  `ID` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
  `SCRIPT_TEXT` text COMMENT '可以直接执行的SQL内容(SELECT列名和COLUMN_NAME相同)',
  `IS_VALID` int(1) NOT NULL DEFAULT '1' COMMENT '1:有效,0:无效',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='自定义脚步SQL';