set mapreduce.job.name = IDW_FACT_MLD_ORDER_CREDIT;
set mapreduce.job.queuename = etl-dw;
set hive.exec.parallel=true;
set hive.exec.max.created.files=100000000;
set hive.groupby.skewindata=true;

INSERT OVERWRITE TABLE IDW.FACT_MLD_ORDER_CREDIT
SELECT T1.ID AS ORDER_ID,T1.ORDER_NO,T1.NONO_BOID,T2.ID AS USER_ID,T2.NONO_USERID,T1.CREATE_TIME AS ORDER_CREATE_DATE,T1.STATUS AS ORDER_STATUS,T1.LOAN_APPLY_STAUS AS APPLY_STAUS
,T1.PRODUCT_HISTORY_ID AS PRODUCT_ID,T1.PRODUCT_CODE AS NONO_PRODUCT_ID
,T5.DIC_ITEM_VALUE HOR_TYPE_ID,T5.DIC_ITEM_NAME as HOR_TYPE_NAME,T4.TOKEN AS DH_UUID
,'SYS' AS DW_CREATE_BY,FROM_UNIXTIME(UNIX_TIMESTAMP(),'yyyy-MM-dd HH:mm:ss') AS DW_CREATE_TIME
,'SYS' AS DW_UPDATE_BY,FROM_UNIXTIME(UNIX_TIMESTAMP(),'yyyy-MM-dd HH:mm:ss') AS DW_UPDATE_TIME
FROM ODSOPR.KERNEL_ORDER_ORD_ORDER T1 INNER JOIN ODSOPR.USR_USER T2
ON T1.DISABLED = 0
AND T2.DISABLED=0
AND T1.CREATE_USER=T2.ID
LEFT OUTER JOIN ODSOPR.ORD_ORDER_CREDIT_RELA T3
ON  T3.DISABLED=0
AND T3.ORDER_ID=T1.ID
LEFT OUTER JOIN ODSOPR.USR_AUTH_CREDIT T4
ON T4.DISABLED=0
AND T3.CREDIT_ID=T4.ID
LEFT OUTER JOIN ODSOPR.KERNEL_SYSTEM_SYS_DIC_ITEM T5
ON T5.DIC_ID=91
AND T4.AUTH_TYPE=T5.DIC_ITEM_VALUE;
