drop table if exists idw.fact_user_info;
create table if not exists idw.fact_user_info
(
 `dw_create_by` string COMMENT '系统字段-创建者',   
  `dw_create_time` string COMMENT '系统字段-创建时间',  
  `dw_update_by` string COMMENT '系统字段-修改者',   
  `dw_update_time` string COMMENT '系统字段-修改时间',  
  `user_id` bigint COMMENT '用户ID',  
  `user_name` string COMMENT '用户名',   
  `real_name` string COMMENT '姓名',  
  `gender` int COMMENT '性别 1:男 2:女',  
  `mobile_num` string COMMENT '手机号',  
  `email` string COMMENT '电子邮箱',  
  `is_email` int COMMENT '是否邮件认证 0:否 1:是',  
  `register_time` string COMMENT '注册时间',  
  `is_authentication` int COMMENT '是否身份认证 0:否 1:是',   
  `is_photo` int COMMENT '是否图像认证 0:否 1:是',  
  `is_education_auth` int COMMENT '是否学历认证 0:否 1:是 2:拒绝',  
  `is_student_auth` int COMMENT '是否学籍认证 0:否 1:是',   
  `is_special` int COMMENT '是否特殊用户 0:否 1:是',  
  `is_cheat` int COMMENT '是否欺诈 0:否 1:是',  
  `status` int COMMENT '状态 0:无效用户 1:有效用户 2:锁定用户',   
  `status_desc` string COMMENT '状态描述 0:无效用户 1:有效用户 2:锁定用户',   
  `pc_id` bigint COMMENT '所属公司ID',  
  `pc_id_desc` string COMMENT '所属公司名称',   
  `recommender` string COMMENT '推荐人',   
  `user_type` int COMMENT '用户类型 0:未知 1:理财 2:贷款 3:白领 4:微企业主 5:学生 6:企业主 7:vip企业主 8:企业',   
  `id_num` string COMMENT '身份证号',   
  `cou_address` string COMMENT '身份证归属地',  
  `finance_advisor` bigint COMMENT '理财顾问',  
  `birthday` string COMMENT '生日',   
  `mobile_address` string COMMENT '手机归属市',  
  `mobile_address_province` string COMMENT '手机归属省',   
  `register_biz` string COMMENT '注册业务线',  
  `english_name` string COMMENT '英文名',  
  `age` int COMMENT '年龄',   
  `constellation` string COMMENT '星座',  
  `qq` string COMMENT 'QQ号码',   
  `current_mobile_no` string COMMENT '当前手机号',   
  `hj_province` string COMMENT '户籍省',   
  `hj_province_name` string COMMENT '户籍省名称',  
  `hj_city` string COMMENT '户籍市',   
  `hj_city_name` string COMMENT '户籍市名称',  
  `hj_address` string COMMENT '户籍地址',   
  `current_province` string COMMENT '当前所在省',  
  `current_province_name` string COMMENT '当前所在省名称',   
  `current_city` string COMMENT '当前所在市',  
  `current_city_name` string COMMENT '当前所在市名称',   
  `birth_province` string COMMENT '出生省份',   
  `birth_province_name` string COMMENT '出生省份名称',  
  `contact_address` string COMMENT '联系地址',  
  `marriage_status` int COMMENT '婚姻状况 0:未知 1:已婚 2:未婚 3:已婚已育 4:已婚未育 5:未婚已育 6:丧偶 7:离婚',   
  `marriage_status_desc` string COMMENT '婚姻状态描述',   
  `is_have_passport` int COMMENT '是否持有护照 0:未知 1:有 2:无',   
  `is_social_security` int COMMENT '是否有社保 0:未知 1:有 2:无',  
  `is_driving_license` int COMMENT '是否有驾照 0:未知 1:有 2:无',  
  `house_status` int COMMENT '现居住地状况 0:未知 1:自购房(无房贷) 2:自购房(有按揭) 3:自建房 4:亲属房产 5:租房 6:其他',  
  `education` string COMMENT '学历',  
  `channel_id` bigint COMMENT '注册渠道ID',   
  `channel_name` string COMMENT '注册渠道名称',   
  `ad_plan` string COMMENT '广告计划',  
  `ad_unit` string COMMENT '广告单元',  
  `channel_detail` string COMMENT '渠道明细',   
  `unifi_register_country_code` int COMMENT 'unifi注册所在国编码',   
  `unifi_register_country_name` string COMMENT 'unifi注册所在国名称',  
  `register_terminal` string COMMENT '注册终端',  
  `register_ip` string COMMENT '注册ip地址',  
  `user_rank` string COMMENT '会员等级 0:普通会员 1:VIP1 2:VIP2 3:VIP3',  
  `user_rank_desc` string COMMENT '会员等级描述',   
  `edu_start_date` string COMMENT '入学时间',   
  `edu_graduate_date` string COMMENT '毕业时间',  
  `mxd_education` string COMMENT '按照名校贷业务要求清洗后的学历，来源于db_nono.user_student_info',  
  `is_graduate` int COMMENT '是否已毕业 0:未毕业 1:已毕业',  
  `campus_approach` int COMMENT '用户来源',   
  `campus_approach_desc` string COMMENT '用户来源描述',   
  `student_no` string COMMENT '学号',   
  `campus` string COMMENT '校区',   
  `family_income` int COMMENT '家庭收入 0:未设置 1:5万以下 2:5-10万 3:10-20万 4:20万以上',   
  `family_income_desc` string COMMENT '家庭收入描述',   
  `school_type` string COMMENT '学校类别',  
  `school_type_desc` string COMMENT '学校类别描述',   
  `school_province_id` bigint COMMENT '学校省份ID',   
  `school_province_name` string COMMENT '学校省份名称',   
  `school_city_id` bigint COMMENT '学校城市ID',   
  `school_city_name` string COMMENT '学校城市名称',   
  `address_home` string COMMENT '家庭住址',   
  `academy` string COMMENT '就读院校',  
  `major` string COMMENT '专业',  
  `instructor_name` string COMMENT '辅导员姓名',   
  `instructor_mobile` string COMMENT '辅导员手机',   
  `instructor_mobile_state` string COMMENT '辅导员手机状态',   
  `instructor_mobile_address` string COMMENT '辅导员手机归属地',  
  `parent_name` string COMMENT '父母姓名',  
  `parent_mobile` string COMMENT '父母手机',  
  `parent_mobile_state` string COMMENT '父母手机状态',  
  `parent_mobile_address` string COMMENT '父母手机归属地',   
  `friend1_name` string COMMENT '好友1姓名',  
  `friend1_mobile` string COMMENT '好友1手机',  
  `friend1_mobile_state` string COMMENT '好友1手机状态',  
  `friend1_mobile_address` string COMMENT '好友1手机归属地',   
  `friend2_name` string COMMENT '好友2姓名',  
  `friend2_mobile` string COMMENT '好友2手机',  
  `friend2_mobile_state` string COMMENT '好友2手机状态',  
  `friend2_mobile_address` string COMMENT '好友2手机归属地',   
  `friend3_name` string COMMENT '好友3姓名',  
  `friend3_mobile` string COMMENT '好友3手机',  
  `friend3_mobile_state` string COMMENT '好友3手机状态',  
  `friend3_mobile_address` string COMMENT '好友3手机归属地',   
  `job` string COMMENT '职业',  
  `current_job_time` string COMMENT '工作年限',   
  `total_job_time` string COMMENT '总工作年限',  
  `company_name` string COMMENT '公司名称',   
  `company_type` string COMMENT '公司类型',   
  `company_business_type` int COMMENT '工作单位性质',   
  `company_tel` string COMMENT '公司电话号码',  
  `is_dfd_admin_member` int COMMENT '是否大房东协议用户',  
  `know_approach_code` string COMMENT '客户获知渠道编码',   
  `know_approach_name` string COMMENT '客户获知渠道名称',   
  `company_business_sort` string COMMENT '企业类别',  
  `company_address` string COMMENT '单位地址',  
  `spouse_name` string COMMENT '配偶名字',  
  `spouse_idnum` string COMMENT '配偶身份证号',   
  `spouse_mobile` string COMMENT '配偶手机号',   
  `spouse_company` string COMMENT '配偶公司',   
  `monthly_salary` string COMMENT '月薪',
  `is_deposit` int comment '是否通过存管认证：0:否，1:是',
  `birthday_age` int comment '年龄-从身份证取生日，再除以365')
COMMENT '用户信息表'
ROW FORMAT DELIMITED
  NULL DEFINED AS ''
STORED AS PARQUET 
TBLPROPERTIES ("parquet.compression"="SNAPPY");
