drop table if exists idw.FACT_BORROWS;
create table if not exists idw.FACT_BORROWS
(
  `bo_id` bigint COMMENT '借款ID',
  `p_id` bigint COMMENT '产品ID',
  `bp_id` bigint COMMENT '预发标ID',
  `user_id` bigint COMMENT '用户ID',
  `bo_aim` string COMMENT '借款目的',
  `bo_title` string COMMENT '借款标题',
  `bo_repaysrc` string COMMENT '还款来源',
  `bo_price` decimal(38,10) COMMENT '借款金额',
  `bo_finish_price` decimal(38,10) COMMENT '完成金额',
  `bo_expect` int COMMENT '借款期限',
  `bo_expect_cat` int COMMENT '借款期限单位',
  `bo_bidding_type` int COMMENT '标的类型',
  `bo_safeguard_type` int COMMENT '保障方式',
  `bo_type` int COMMENT '借款类型',
  `is_assurance` int COMMENT '是否请求担保',
  `bo_rate` decimal(38,10) COMMENT '借款年利率',
  `bo_time` int COMMENT '有效时间',
  `bo_paytype` string COMMENT '还款方式',
  `bo_is_index` int COMMENT '是否推荐',
  `bo_is_state` int COMMENT '借款状态',
  `publish_time` string COMMENT '发布时间',
  `bo_finish_rate` decimal(38,10) COMMENT '完成度',
  `bo_is_finish` int COMMENT '是否完成',
  `bo_finish_time` string COMMENT '完成时间',
  `bo_sign_am_id` bigint COMMENT '签约人员',
  `bo_sign_time` string COMMENT '签约时间',
  `bo_sign_result` int COMMENT '签约结果',
  `bo_sign_remark` string COMMENT '签约备注',
  `bo_audit_am_id` bigint COMMENT '审核人员',
  `bo_audit_time` string COMMENT '审核时间',
  `bo_audit_remark` string COMMENT '审核备注',
  `bo_is_success` int COMMENT '是否审核通过',
  `bo_can_success` int COMMENT '是否可以审核通过',
  `bo_is_republish` int COMMENT '是否已重发',
  `bo_is_case` int COMMENT '是否推荐案例',
  `bo_guid` string COMMENT '电子协议guid',
  `bo_extno` string COMMENT '协议编号',
  `bo_agree_generated` int COMMENT '协议是否生成',
  `bo_agree_time` string COMMENT '协议生成时间',
  `bo_all_repayed` int COMMENT '借款还款结束',
  `bo_last_repayed_time` string COMMENT '最近还款时间',
  `bo_sorce_talk` int COMMENT '谈吐分值',
  `bo_sorce_instrument` int COMMENT '仪表分值',
  `bo_sorce_face` int COMMENT '面相分值',
  `bo_sorce_cooperation` int COMMENT '配合度分值',
  `bo_pledge` int COMMENT '是否抵押',
  `bo_house` string COMMENT '房产信息',
  `bo_overdue_day_count` int COMMENT '逾期天数',
  `bo_overdue_remark` string COMMENT '逾期备注',
  `zx_price` decimal(38,10) COMMENT '咨询费',
  `creator` bigint COMMENT '创建人',
  `updator` bigint COMMENT '更新人',
  `create_time` string COMMENT '创建时间',
  `update_time` string COMMENT '更新时间',
  `bo_purpose` string COMMENT '借款用途',
  `is_video_audit` int COMMENT '是否提交视频',
  `video_audit_time` string COMMENT '视频提交时间',
  `is_repeat_borrow` int COMMENT '是否复借',
  `dw_create_by` string COMMENT '系统字段-创建者',
  `dw_create_time` string COMMENT '系统字段-创建时间',
  `dw_update_by` string COMMENT '系统字段-修改者',
  `dw_update_time` string COMMENT '系统字段-修改时间')
COMMENT '借款表'
ROW FORMAT DELIMITED
  NULL DEFINED AS ''
STORED AS PARQUET 
TBLPROPERTIES ("parquet.compression"="SNAPPY");
