CREATE TABLE DMT.fact_repay_borrows_snapshot (
  bo_id BIGINT COMMENT '借款ID',
  p_id BIGINT COMMENT '产品ID',
  busi_line STRING COMMENT '所属业务线',
  user_id BIGINT COMMENT '用户ID',
  bo_rate DECIMAL (38, 10) COMMENT '借款年利率',
  bo_finish_price DECIMAL (38, 10) COMMENT '完成金额',
  bo_expect INT COMMENT '借款期限',
  bo_expect_cat INT COMMENT '借款期限单位',
  interest_rate_cut DECIMAL (38, 10) COMMENT '减息',
  bo_audit_time STRING COMMENT '审核时间',
  bo_agree_time STRING COMMENT '协议生成时间',
  should_repay_cnt INT COMMENT '应还期数',
  repayed_cnt INT COMMENT '已还期数',
  unrepay_cnt INT COMMENT '未还期数',
  should_repay_cnt_this_month INT COMMENT '当月应还期数 月底之前该还并且未还的期数总和',
  repayed_cnt_this_month INT COMMENT '本月已还期数',
  should_repay_price DECIMAL (38, 10) COMMENT '应还金额',
  repayed_price DECIMAL (38, 10) COMMENT '已还金额',
  unrepay_price DECIMAL (38, 10) COMMENT '未还金额',
  should_repay_price_this_month DECIMAL (38, 10) COMMENT '当月应还金额 月底之前该还并且未还的金额总和',  
  repayed_price_this_month DECIMAL (38, 10) COMMENT '本月已还金额',
  should_repay_price_b DECIMAL (38, 10) COMMENT '应还本金',
  repayed_price_b DECIMAL (38, 10) COMMENT '已还本金',
  unrepay_price_b DECIMAL (38, 10) COMMENT '未还本金',
  should_repay_price_b_this_month DECIMAL (38, 10) COMMENT '当月应还本金 月底之前该还并且未还的本金总和',  
  repayed_price_b_this_month DECIMAL (38, 10) COMMENT '本月已还本金',
  should_repay_price_l DECIMAL (38, 10) COMMENT '应还利息',
  repayed_price_l DECIMAL (38, 10) COMMENT '已还利息',
  unrepay_price_l DECIMAL (38, 10) COMMENT '未还利息',
  should_repay_price_l_this_month DECIMAL (38, 10) COMMENT '当月应还利息 月底之前该还并且未还的利息总和',
  repayed_price_l_this_month DECIMAL (38, 10) COMMENT '本月已还利息',
  should_repay_price_punish DECIMAL (38, 10) COMMENT '应还罚息',
  repayed_price_punish DECIMAL (38, 10) COMMENT '已还罚息',
  unrepay_price_punish DECIMAL (38, 10) COMMENT '未还罚息',
  should_repay_price_punish_this_month DECIMAL (38, 10) COMMENT '当月应还罚息 月底之前该还并且未还的罚息总和',
  repayed_price_punish_this_month DECIMAL (38, 10) COMMENT '本月已还罚息',
  should_repay_service_fee DECIMAL (38, 10) COMMENT '应还服务费',
  repayed_service_fee DECIMAL (38, 10) COMMENT '已还服务费',
  unrepay_service_fee DECIMAL (38, 10) COMMENT '未还服务费',
  should_repay_service_fee_this_month DECIMAL (38, 10) COMMENT '当月应还服务费 月底之前该还并且未还的服务费总和',
  repayed_service_fee_this_month DECIMAL (38, 10) COMMENT '本月已还服务费',
  repay_begin_day STRING COMMENT '起始还款日',
  repay_end_day STRING COMMENT '最终还款日',
  last_repayed_time STRING COMMENT '最近还款时间',
  compensate_amt DECIMAL (38, 10) COMMENT '代偿金额',
  repayed_compensate_amt DECIMAL (38, 10) COMMENT '已还代偿金额',
  is_first_repay_overdue INT COMMENT '是否首还逾期',
  first_repay_overdue_days INT COMMENT '首还逾期天数',
  is_overdue INT COMMENT '是否有过逾期',
  max_overdue_days INT COMMENT '最大逾期天数',
  is_overdue_unrepay INT COMMENT '是否逾期未还',
  is_dunning INT COMMENT '是否在催收',
  dun_type INT COMMENT '催收类型 0:委外 1:内催',
  dun_company BIGINT COMMENT '催收服务商',
  dun_company_name STRING COMMENT '催收服务商名称',
  dun_start_time STRING COMMENT '催收开始时间',
  dun_end_time STRING COMMENT '催收结束时间',
  DUN_CLOSE_TIME STRING COMMENT '催收结案时间',
  DUN_STATUS int comment '状态 0:委外在案 1:委外结案 2:委外退案 3:提前退案 4:延期案件',
  overdue_expect_cnt INT COMMENT '当前逾期期数',
  overdue_repayed_price DECIMAL (38, 10) COMMENT '逾期已还金额',
  overdue_unrepay_expect_cnt INT COMMENT '当前逾期未还期数',
  overdue_unrepay_days INT COMMENT '当前逾期未还天数',
  aging STRING COMMENT '账龄',
  overdue_unrepay_price DECIMAL (38, 10) COMMENT '逾期未还金额',
  overdue_unrepay_price_b DECIMAL (38, 10) COMMENT '逾期未还本金',
  overdue_unrepay_price_l DECIMAL (38, 10) COMMENT '逾期未还利息',
  overdue_unrepay_price_punish DECIMAL (38, 10) COMMENT '逾期未还罚息',
  overdue_unrepay_service_fee DECIMAL (38, 10) COMMENT '逾期未还服务费',
  compensate_price_b DECIMAL (38, 10) COMMENT '代偿本金',
  repayed_compensate_price_b DECIMAL (38, 10) COMMENT '已还代偿本金',
  cur_price DECIMAL (38, 10) COMMENT '当期应还金额',
  cur_price_b DECIMAL (38, 10) COMMENT '当期应还本金',
  cur_price_l DECIMAL (38, 10) COMMENT '当期应还利息',
  cur_service_fee DECIMAL (38, 10) COMMENT '当期应还平台服务费',
  first_repay_time STRING COMMENT '首次还款时间',
  should_return_price DECIMAL (38, 10) COMMENT '应返还金额',
  returned_price DECIMAL (38, 10) COMMENT '已返还金额',
  unreturned_price DECIMAL (38, 10) COMMENT '未返还金额',
  should_returned_price_this_month DECIMAL (38, 10) COMMENT '当月应返还金额 月底之前该还并且未返还的返还金额总和',
  returned_price_this_month DECIMAL (38, 10) COMMENT '本月已返还金额',
  overdue_returned_price DECIMAL (38, 10) COMMENT '逾期已返还金额',
  overdue_unreturned_price DECIMAL (38, 10) COMMENT '逾期未返还金额',
  unrepay_br_time_min string COMMENT '未还最早逾期计划时间',
  overdue_term_max INT COMMENT '最大逾期期数',
  overdue_price_b_max DECIMAL (38, 10)  COMMENT '最大连续逾期本金',
  is_all_repayed int COMMENT '是否还清',
  dw_create_by STRING COMMENT '系统字段-创建者',
  dw_create_time STRING COMMENT '系统字段-创建时间',
  dw_update_by STRING COMMENT '系统字段-修改者',
  dw_update_time STRING COMMENT '系统字段-修改时间'
) COMMENT '还款快照表'
PARTITIONED BY (STAT_DATE STRING COMMENT '统计日期 年-月-日')
ROW FORMAT DELIMITED
NULL DEFINED AS ''
STORED AS PARQUET 
TBLPROPERTIES ("PARQUET.COMPRESSION"="SNAPPY");
