CREATE TABLE IF NOT EXISTS  DMT.FACT_FINANCE_ACCOUNT_SNAPSHOT (   
DW_CREATE_BY STRING COMMENT '系统字段-创建者',    
DW_CREATE_TIME STRING COMMENT '系统字段-创建时间',    
DW_UPDATE_BY STRING COMMENT '系统字段-修改者',    
DW_UPDATE_TIME STRING COMMENT '系统字段-修改时间',    
ID BIGINT,    
ROLE_ID BIGINT COMMENT '资金角色',
USER_ID BIGINT COMMENT '会员ID',    
OWNER_ID BIGINT COMMENT '所有者ID',    
BALANCE DECIMAL(38,10) COMMENT '余额',
LOCKING DECIMAL(38,10) COMMENT '锁定金额',
VERSION INT COMMENT '版本',
CREATE_TIME STRING COMMENT '创建时间',
UPDATE_TIME STRING ) 
COMMENT '资金账户余额快照表'
PARTITIONED BY (STAT_DATE STRING COMMENT '统计日期 年-月-日')
ROW FORMAT DELIMITED
  NULL DEFINED AS ''
STORED AS PARQUET 
TBLPROPERTIES ("PARQUET.COMPRESSION"="SNAPPY");
