CREATE TABLE IF NOT EXISTS  DMT.FACT_CSYY_FINANCE_ACCOUNT_SNAPSHOT (   
USER_ID BIGINT COMMENT '用户ID',    
USER_CODE BIGINT COMMENT '用户USERCODE-MERCHANTUSERID',
AMOUNT DECIMAL(38,10) COMMENT '账号余额', 
DW_CREATE_BY STRING COMMENT '系统字段-创建者',    
DW_CREATE_TIME STRING COMMENT '系统字段-创建时间',    
DW_UPDATE_BY STRING COMMENT '系统字段-修改者',    
DW_UPDATE_TIME STRING COMMENT '系统字段-修改时间'
) 
COMMENT '财神爷爷资金账户余额快照表'
PARTITIONED BY (STAT_DATE STRING COMMENT '统计日期 年-月-日')
ROW FORMAT DELIMITED
  NULL DEFINED AS ''
STORED AS PARQUET 
TBLPROPERTIES ("PARQUET.COMPRESSION"="SNAPPY");
