
-- 创建ODS层数据库
    CREATE DATABASE IF NOT EXISTS ODS COMMENT 'ODS层源业务数据库';

-- 创建APP用户行为数据日志表
    --1) textfile 格式的表
    CREATE TABLE IF NOT EXISTS LOG_DEMO_TEXT
    (
     LOG_ID STRING COMMENT '日志ID'
    ,LOG_TIME STRING COMMENT '日志时间'
    )
    COMMENT 'LOG_DEMO表(textfile格式)'
    PARTITIONED BY (DAY STRING COMMENT '分区键:日期')
     ROW FORMAT DELIMITED
       FIELDS TERMINATED BY '\001'
       COLLECTION ITEMS TERMINATED BY '\002'
       MAP KEYS TERMINATED BY '\003'
       NULL DEFINED AS ''
     STORED AS TEXTFILE;

    --2) parquet 格式的表
    CREATE TABLE IF NOT EXISTS LOG_DEMO_PARQUET
    (
     LOG_ID STRING COMMENT '日志ID'
    ,LOG_TIME STRING COMMENT '日志时间'
    )
    COMMENT 'LOG_DEMO表(parquet格式)'
    PARTITIONED BY (DAY STRING COMMENT '分区键:日期')
    ROW FORMAT DELIMITED
      NULL DEFINED AS ''
    STORED AS PARQUET TBLPROPERTIES ("parquet.compression"="SNAPPY");

    --3) external 表
    CREATE EXTERNAL TABLE IF NOT EXISTS LOG_DEMO_TEXT_EXT
    (
     LOG_ID STRING COMMENT '日志ID'
    ,LOG_TIME STRING COMMENT '日志时间'
    )
    COMMENT 'LOG_DEMO表(textfile格式外部表)'
    PARTITIONED BY (DAY STRING COMMENT '分区键:日期')
     ROW FORMAT DELIMITED
       FIELDS TERMINATED BY '\001'
       COLLECTION ITEMS TERMINATED BY '\002'
       MAP KEYS TERMINATED BY '\003'
       NULL DEFINED AS ''
     STORED AS TEXTFILE
     LOCATION '/user/sqoop/ods/log_demo';




