drop table if exists DMT_BF.NONO_PROLOCUTOR_EARNINGS_TYPE3;
create table if not exists DMT_BF.NONO_PROLOCUTOR_EARNINGS_TYPE3
( 
   NONO_PROLOCUTOR_ID  bigint   COMMENT '磅客大使ID', 
   NONO_PROLOCUTOR_NAME  string   COMMENT'镑客大使名称',
   PAYED          decimal(38,10)   COMMENT 'TYPE3累积收益',
   DW_CREATE_BY     STRING COMMENT '系统字段-创建者',
   DW_CREATE_TIME   STRING COMMENT '系统字段-创建时间',
   DW_UPDATE_BY     STRING COMMENT '系统字段-修改者',
   DW_UPDATE_TIME   STRING COMMENT '系统字段-修改时间'
)COMMENT '镑客大使TYPE3累积收益固化表'
ROW FORMAT DELIMITED
  NULL DEFINED AS ''
STORED AS PARQUET 
TBLPROPERTIES ("parquet.compression"="SNAPPY");