DROP TABLE IF EXISTS DMT_BF.NONO_V3USER_UNPACKAGE_DEBT;
CREATE TABLE IF NOT EXISTS DMT_BF.NONO_V3USER_UNPACKAGE_DEBT
(
   BO_ID              BIGINT COMMENT '标的',
   TOTAL_PRICE DECIMAL(38,10) COMMENT '本金合计',
   BO_EXPECT    INT COMMENT '借款期限', 
   BO_SIGN_TIME   STRING COMMENT '签约时间',
   REMAININGPERIOD   INT COMMENT '债权数',
   BO_EXTNO   STRING COMMENT '协议号',
   BO_AIM             STRING COMMENT '借款目的',
   PER_PRICE              DECIMAL(38,10) COMMENT '每期本金',
   LAST_PLAN_TIME                   STRING COMMENT '最后计划还款日',
   REAL_NAME                 STRING COMMENT '真实姓名',
   USER_NAME          STRING COMMENT '用户名', 
   ID_NUM          STRING COMMENT '身份证',
   BRITHDAY          STRING COMMENT '出生年月',
   MOBILE_NUM          STRING COMMENT '手机号',
   ACADEMY          STRING COMMENT '学校',
   MAJOR          STRING COMMENT '专业',
   EDUCATION          STRING COMMENT '学历',
   EDU_START_DATE          STRING COMMENT '入学年份',
   CAMPUS  STRING COMMENT '校区',
   GENDER          STRING COMMENT '性别',
   EMERGENCY_PARENT          STRING COMMENT '父母',
   EMERGENCY_COUNSELOR          STRING COMMENT '辅导员',
   EMERGENCY_OTHER          STRING COMMENT '好友',
   ADDRESS          STRING COMMENT '住址',
   DW_CREATE_BY         STRING COMMENT '系统字段-创建者',
   DW_CREATE_TIME       STRING COMMENT '系统字段-创建时间',
   DW_UPDATE_BY         STRING COMMENT '系统字段-修改者',
   DW_UPDATE_TIME       STRING COMMENT '系统字段-修改时间'
) COMMENT '债权回流表'
PARTITIONED BY (STAT_DATE STRING COMMENT '数据所属日期')
ROW FORMAT DELIMITED
  NULL DEFINED AS ''
STORED AS PARQUET 
TBLPROPERTIES ("parquet.compression"="SNAPPY");
;