-- ## 建表
DROP TABLE IF EXISTS DMT_BF.USER_EXPECTED_REVENUE_YDAY;
CREATE TABLE IF NOT EXISTS DMT_BF.USER_EXPECTED_REVENUE_YDAY
(   
   USER_ID              BIGINT COMMENT '用户唯一标识',  
   EXPECTED_REVENUE     STRING COMMENT '昨日收益',
  -- PRO_TYPE              STRING COMMENT '产品类型',
   DW_CREATE_BY         STRING COMMENT '系统字段-创建者',
   DW_CREATE_TIME       STRING COMMENT '系统字段-创建时间',
   DW_UPDATE_BY         STRING COMMENT '系统字段-修改者',
   DW_UPDATE_TIME       STRING COMMENT '系统字段-修改时间'
) COMMENT '用户昨日收益表'
PARTITIONED BY (STAT_DATE STRING, PRO_TYPE STRING COMMENT '分区键:统计日期产品类型')
STORED AS PARQUET TBLPROPERTIES ("parquet.compression"="SNAPPY")
;

