DROP TABLE IF EXISTS DMT_BF.WDZJ_NPL_BO_LEGACY;
CREATE TABLE DMT_BF.WDZJ_NPL_BO_LEGACY(
    ID bigint COMMENT '标的ID'
)COMMENT '不良标的表'
PARTITIONED BY (STAT_DATE STRING COMMENT '统计日期 年-月-日')
ROW FORMAT DELIMITED
NULL DEFINED AS ''
STORED AS PARQUET 
TBLPROPERTIES ("parquet.compression"="SNAPPY");
